Repository l2beat/l2beat, pull requests merged in 2024-12, with the labels that each got.

#5995 Starknet uses compressed state diffs for DA
  packages/config/src/projects/layer2s/starknet.ts
Labels: trivial, research

#6011 Update FAQ
  packages/frontend/src/app/(top-nav)/faq/faq-items.tsx
Labels: trivial

#6000 Trivial discovery updates 12/02
  packages/backend/discovery/inevm/arbitrum/diffHistory.md
  packages/backend/discovery/inevm/arbitrum/discovered.json
  packages/backend/discovery/loopring/ethereum/config.jsonc
  packages/backend/discovery/loopring/ethereum/diffHistory.md
  packages/backend/discovery/loopring/ethereum/discovered.json
  packages/backend/discovery/oevnetwork/ethereum/diffHistory.md
  packages/backend/discovery/oevnetwork/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/layer2s/loopring.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#6010 Add Muster Network (full)
  packages/backend/discovery/muster/arbitrum/config.jsonc
  packages/backend/discovery/muster/arbitrum/diffHistory.md
  packages/backend/discovery/muster/arbitrum/discovered.json
  packages/config/src/projects/layer3s/muster.ts
  packages/config/src/projects/other/da-beat/dac/muster.ts
  packages/config/src/projects/other/da-beat/index.ts
  packages/config/src/test/snapshots/muster.riskView.snapshot
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#6023 Trivial discovery updates 12/04
  packages/backend/discovery/blobstream/arbitrum/diffHistory.md
  packages/backend/discovery/blobstream/arbitrum/discovered.json
  packages/backend/discovery/blobstream/base/diffHistory.md
  packages/backend/discovery/blobstream/base/discovered.json
  packages/backend/discovery/blobstream/ethereum/diffHistory.md
  packages/backend/discovery/blobstream/ethereum/discovered.json
  packages/backend/discovery/immutablex/ethereum/config.jsonc
  packages/backend/discovery/immutablex/ethereum/diffHistory.md
  packages/backend/discovery/immutablex/ethereum/discovered.json
  packages/backend/discovery/kinto/kinto/config.jsonc
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/backend/discovery/layerzerov2oft/ethereum/discovered.json
  packages/backend/discovery/muster/arbitrum/diffHistory.md
  packages/backend/discovery/muster/arbitrum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/backend/discovery/zircuit/ethereum/diffHistory.md
  packages/backend/discovery/zircuit/ethereum/discovered.json
  packages/config/src/projects/layer2s/zircuit.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/base/verified.json
  packages/config/src/verification/ethereum/verified.json
Labels: research

#6026 New tokens (base and arbitrum)
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6031 Archive projects (hook, dydx, parallel)
  packages/config/src/projects/layer2s/dydx.ts
  packages/config/src/projects/layer2s/parallel.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer2s/templates/underReview.ts
  packages/config/src/projects/layer3s/hook.ts
Labels: research

#6037 add Usdc escrow to lisk, track dydx updates post-archiving
  packages/backend/discovery/_templates/circle/L1OpUSDCBridgeAdapter/shape/L1OpUSDCBridgeAdapter.sol
  packages/backend/discovery/_templates/circle/L1OpUSDCBridgeAdapter/template.jsonc
  packages/backend/discovery/dydx/ethereum/diffHistory.md
  packages/backend/discovery/dydx/ethereum/discovered.json
  packages/backend/discovery/lisk/ethereum/config.jsonc
  packages/backend/discovery/lisk/ethereum/diffHistory.md
  packages/backend/discovery/lisk/ethereum/discovered.json
  packages/backend/discovery/worldchain/ethereum/config.jsonc
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/config/src/onChainProjects.ts
  packages/config/src/projects/layer2s/lisk.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#6040 Add BTC wrapper tokens to BOB with doublecounting warning
  packages/config/src/projects/layer2s/bob.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6049 Trivial discovery updates 12/08
  packages/backend/discovery/blobstream/arbitrum/diffHistory.md
  packages/backend/discovery/blobstream/arbitrum/discovered.json
  packages/backend/discovery/blobstream/base/diffHistory.md
  packages/backend/discovery/blobstream/base/discovered.json
  packages/backend/discovery/blobstream/ethereum/diffHistory.md
  packages/backend/discovery/blobstream/ethereum/discovered.json
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/config.jsonc
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/config/scripts/socketconvert/convertedVaults.txt
  packages/config/scripts/socketconvert/input.json
  packages/config/scripts/socketcrawl/index.ts
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/projects/layer2s/common/stages/getStage.ts
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/projects/layer2s/lisk.ts
  packages/config/src/projects/layer2s/lyra.ts
  packages/config/src/projects/layer2s/polynomial.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#6055 Add ZEROnetwork liveness config
  packages/config/src/projects/layer2s/zeronetwork.ts
Labels: research

#6056 Add new tokens from the script (some preminted on arb)
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6051 Add more socket tokens to derive L2 (mainly from arb, base)
  packages/config/scripts/socketconvert/convertedVaults.txt
  packages/config/scripts/socketconvert/input.json
  packages/config/src/projects/layer2s/lyra.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6059 Add associated BNRY token
  packages/config/src/projects/layer2s/thebinaryholdings.ts
Labels: trivial

#6060 Trivial discovery updates 12/09
  packages/backend/discovery/_templates/eigenlayer/Strategy/shape/StrategyBase.sol
  packages/backend/discovery/_templates/opstack/OptimismPortal_zircuit/shape/OptimismPortal_v1_8_0_zircuit.sol
  packages/backend/discovery/_templates/opstack/OptimismPortal_zircuit/template.jsonc
  packages/backend/discovery/alephzero/ethereum/diffHistory.md
  packages/backend/discovery/alephzero/ethereum/discovered.json
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/eigenda/ethereum/config.jsonc
  packages/backend/discovery/eigenda/ethereum/diffHistory.md
  packages/backend/discovery/eigenda/ethereum/discovered.json
  packages/backend/discovery/everclear/ethereum/diffHistory.md
  packages/backend/discovery/everclear/ethereum/discovered.json
  packages/backend/discovery/fluence/ethereum/diffHistory.md
  packages/backend/discovery/fluence/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/sxnetwork/ethereum/diffHistory.md
  packages/backend/discovery/sxnetwork/ethereum/discovered.json
  packages/backend/discovery/zircuit/ethereum/diffHistory.md
  packages/backend/discovery/zircuit/ethereum/discovered.json
  packages/backend/discovery/zksync/ethereum/diffHistory.md
  packages/backend/discovery/zksync/ethereum/discovered.json
  packages/config/src/projects/layer2s/alephzero.ts
  packages/config/src/projects/layer2s/everclear.ts
  packages/config/src/projects/layer2s/fluence.ts
  packages/config/src/projects/layer2s/sxnetwork.ts
  packages/config/src/projects/layer2s/witness.ts
  packages/config/src/projects/layer3s/degen.ts
  packages/config/src/test/snapshots/degen.riskView.snapshot
Labels: research

#6067 Degen: upgrade EOA removed
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/config/src/projects/layer3s/degen.ts
Labels: research

#6085 Kinto: KintoID upgrade includes EXIT_WINDOW_PERIOD
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
Labels: research

#6036 Add treasure (full)
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/treasure/ethereum/config.jsonc
  packages/backend/discovery/treasure/ethereum/diffHistory.md
  packages/backend/discovery/treasure/ethereum/discovered.json
  packages/backend/src/modules/tvl/modules/ElasticChainModule.ts
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/projects/layer2s/templates/zkStack.ts
  packages/config/src/projects/layer2s/treasure.ts
  packages/config/src/projects/layer2s/zeronetwork.ts
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/config/src/test/constants.ts
  packages/config/src/test/snapshots/treasure.riskView.snapshot
  packages/config/src/verification/ethereum/verified.json
Labels: research

#6146 Trivial discovery updates 12/16
  packages/backend/discovery/_templates/opstack/BalanceClaimer/shape/BalanceClaimer.sol
  packages/backend/discovery/_templates/opstack/BalanceClaimer/template.jsonc
  packages/backend/discovery/_templates/opstack/L1StandardBridge_PGN_withdraw/shape/L1StandardBridge.sol
  packages/backend/discovery/_templates/opstack/L1StandardBridge_PGN_withdraw/template.jsonc
  packages/backend/discovery/_templates/opstack/OptimismPortal/shape/OptimismPortal_v1_7_0_MNT.sol
  packages/backend/discovery/_templates/opstack/OptimismPortal_PGN_withdraw/shape/OptimismPortal_v1_7_0_PGN_WITHDRAW.sol
  packages/backend/discovery/_templates/opstack/OptimismPortal_PGN_withdraw/template.jsonc
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/publicgoodsnetwork/ethereum/diffHistory.md
  packages/backend/discovery/publicgoodsnetwork/ethereum/discovered.json
  packages/config/src/projects/layer2s/publicgoodsnetwork.ts
Labels: trivial-discovery

#6178 Fix link
  packages/config/src/projects/layer2s/degenlayer.ts
Labels: trivial

#5575 Add sophon (full)
  packages/backend/discovery/_templates/shared-zk-stack/L1USDCBridge/shape/L1USDCBridge.sol
  packages/backend/discovery/_templates/shared-zk-stack/L1USDCBridge/template.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/sophon/ethereum/config.jsonc
  packages/backend/discovery/sophon/ethereum/diffHistory.md
  packages/backend/discovery/sophon/ethereum/discovered.json
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/projects/layer2s/sophon.ts
  packages/config/src/test/constants.ts
  packages/config/src/test/snapshots/sophon.riskView.snapshot
  packages/frontend/public/images/architecture/sophon.png
Labels: research

#6189 Discovery updates 12/18
  packages/backend/discovery/_templates/opstack/SystemConfig/shape/SystemConfig_v2_3_0_beta_5.sol
  packages/backend/discovery/bobanetwork/ethereum/diffHistory.md
  packages/backend/discovery/bobanetwork/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/kinto/kinto/config.jsonc
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/omni/ethereum/config.jsonc
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/playblock/nova/diffHistory.md
  packages/backend/discovery/playblock/nova/discovered.json
  packages/backend/discovery/publicgoodsnetwork/ethereum/diffHistory.md
  packages/backend/discovery/publicgoodsnetwork/ethereum/discovered.json
  packages/backend/discovery/reya/ethereum/diffHistory.md
  packages/backend/discovery/reya/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/sophon/ethereum/config.jsonc
  packages/backend/discovery/sophon/ethereum/diffHistory.md
  packages/backend/discovery/sophon/ethereum/discovered.json
  packages/backend/discovery/thebinaryholdings/ethereum/diffHistory.md
  packages/backend/discovery/thebinaryholdings/ethereum/discovered.json
  packages/backend/discovery/treasure/ethereum/config.jsonc
  packages/backend/discovery/treasure/ethereum/diffHistory.md
  packages/backend/discovery/treasure/ethereum/discovered.json
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/backend/discovery/xdai/ethereum/config.jsonc
  packages/backend/discovery/xdai/ethereum/diffHistory.md
  packages/backend/discovery/xdai/ethereum/discovered.json
  packages/config/scripts/socketcrawl/index.ts
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/omni.ts
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/projects/bridges/xdai.ts
  packages/config/src/projects/layer2s/sophon.ts
  packages/config/src/projects/layer2s/thebinaryholdings.ts
  packages/config/src/projects/layer2s/treasure.ts
Labels: trivial-discovery, research

#6155 Linea alphav4 upgrade review
  packages/backend/discovery/_templates/linea/LineaRollup/shape/LineaRollup.sol
  packages/backend/discovery/_templates/linea/LineaRollup/template.jsonc
  packages/backend/discovery/_templates/linea/Timelock/shape/Timelock.sol
  packages/backend/discovery/_templates/linea/Timelock/template.jsonc
  packages/backend/discovery/_templates/linea/TokenBridge/shape/TokenBridge.sol
  packages/backend/discovery/_templates/linea/TokenBridge/template.jsonc
  packages/backend/discovery/linea/ethereum/config.jsonc
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/projects/layer2s/linea.ts
  packages/config/src/test/snapshots/linea.riskView.snapshot
  packages/discovery-types/src/Discovery.ts
  packages/discovery/schemas/contract.v2.schema.json
  packages/discovery/src/discovery/config/RawDiscoveryConfig.ts
  packages/frontend/public/images/architecture/linea.png
Labels: research

#6203 Add Avail DA to Sophon
  packages/config/src/common/dataAvailability.ts
  packages/config/src/common/riskView.ts
  packages/config/src/common/technologyDataAvailability.ts
  packages/config/src/projects/layer2s/sophon.ts
Labels: research

#6215 add FUEL, BGB, degen stargate tokens
  packages/config/src/projects/layer3s/degen.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6216 Add FUEL as associated
  packages/config/src/projects/layer2s/fuel.ts
Labels: research

#6214 Rari goes celestia nitro blobstream
  packages/backend/discovery/_templates/orbitstack/OneStepProverHostIo_Celestia/shape/OneStepProverHostIo.sol
  packages/backend/discovery/_templates/orbitstack/OneStepProverHostIo_Celestia/template.jsonc
  packages/backend/discovery/_templates/orbitstack/SequencerInbox_Celestia/shape/SequencerInbox_v32_celestianitro.sol
  packages/backend/discovery/_templates/orbitstack/SequencerInbox_Celestia/template.jsonc
  packages/backend/discovery/globalTypes.jsonc
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/config/src/common/dataAvailability.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer3s/rari.ts
  packages/config/src/projects/other/da-beat/blockchain/celestia/bridges/blobstream/SP1Blobstream.ts
  packages/config/src/projects/other/da-beat/dac/rari.ts
  packages/config/src/projects/other/da-beat/index.ts
  packages/config/src/test/snapshots/rari.riskView.snapshot
Labels: research

#6220 Try different degen multicall
  packages/config/src/chains/index.test.ts
  packages/config/src/projects/layer3s/degen.ts
Labels: code

#6229 Trivial discovery updates 12/24
  packages/backend/discovery/everclear/ethereum/diffHistory.md
  packages/backend/discovery/everclear/ethereum/discovered.json
  packages/backend/discovery/hyperliquid/arbitrum/config.jsonc
  packages/backend/discovery/hyperliquid/arbitrum/diffHistory.md
  packages/backend/discovery/hyperliquid/arbitrum/discovered.json
  packages/backend/discovery/kinto/kinto/config.jsonc
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/playblock/nova/diffHistory.md
  packages/backend/discovery/playblock/nova/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/taiko/ethereum/config.jsonc
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/config/src/projects/layer2s/ink.ts
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/projects/layer2s/taiko.ts
Labels: trivial-discovery

#6240 Trivial discovery updates 12/26
  packages/backend/discovery/_templates/opstack/AnchorStateRegistry/shape/AnchorStateRegistry_v2_0_1_beta3.sol
  packages/backend/discovery/_templates/opstack/PermissionedDisputeGame/shape/PermissionedDisputeGame_v1_3_1_beta3.sol
  packages/backend/discovery/ink/ethereum/config.jsonc
  packages/backend/discovery/ink/ethereum/diffHistory.md
  packages/backend/discovery/ink/ethereum/discovered.json
  packages/backend/discovery/taiko/ethereum/config.jsonc
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/config/src/projects/bridges/ankr.ts
  packages/config/src/projects/layer2s/ink.ts
  packages/config/src/projects/layer2s/taiko.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial-discovery

#6241 add description for Kintos stf-enforced kyc technology
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/projects/layer2s/optimism.ts
Labels: research

#6243 add rsETH to zksync TVL
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6244 Fix formatting for Kinto
  packages/config/src/projects/layer2s/kinto.ts
Labels: research
