Repository l2beat/l2beat, pull requests merged in 2024-09, with the labels that each got.

#4958 Add wasmModuleRoot mapping
  packages/backend/discovery/_templates/orbitstack/RollupProxy/template.jsonc
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/deri/arbitrum/diffHistory.md
  packages/backend/discovery/deri/arbitrum/discovered.json
  packages/backend/discovery/edgeless/ethereum/diffHistory.md
  packages/backend/discovery/edgeless/ethereum/discovered.json
  packages/backend/discovery/galxegravity/ethereum/diffHistory.md
  packages/backend/discovery/galxegravity/ethereum/discovered.json
  packages/backend/discovery/globalTypes.jsonc
  packages/backend/discovery/hychain/ethereum/diffHistory.md
  packages/backend/discovery/hychain/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/l3x/arbitrum/diffHistory.md
  packages/backend/discovery/l3x/arbitrum/discovered.json
  packages/backend/discovery/molten/arbitrum/diffHistory.md
  packages/backend/discovery/molten/arbitrum/discovered.json
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/backend/discovery/parallel/ethereum/diffHistory.md
  packages/backend/discovery/parallel/ethereum/discovered.json
  packages/backend/discovery/playblock/nova/diffHistory.md
  packages/backend/discovery/playblock/nova/discovered.json
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/popboss/arbitrum/diffHistory.md
  packages/backend/discovery/popboss/arbitrum/discovered.json
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
  packages/backend/discovery/reya/ethereum/diffHistory.md
  packages/backend/discovery/reya/ethereum/discovered.json
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/sxnetwork/ethereum/diffHistory.md
  packages/backend/discovery/sxnetwork/ethereum/discovered.json
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
Labels: trivial

#4959 Cleanup Eigenlayer config and treat trivial disco changes
  packages/backend/discovery/_templates/eigenlayer/Strategy/template.jsonc
  packages/backend/discovery/shared-eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
Labels: trivial-discovery

#4957 Add `l2b check-rpc`
  packages/backend-tools/src/logger/LogLevel.ts
  packages/config/package.json
  packages/config/scripts/checkRpc.ts
  packages/l2b/src/commands/CheckRpc.ts
  packages/l2b/src/commands/index.ts
  packages/l2b/src/commands/types.ts
  packages/l2b/src/implementations/checkrpc.ts
Labels: code

#4973 Add Cronos zkEVM (full)
  packages/backend/discovery/cronoszkevm/ethereum/config.jsonc
  packages/backend/discovery/cronoszkevm/ethereum/diffHistory.md
  packages/backend/discovery/cronoszkevm/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend2/public/images/architecture/cronoszkevm.png
Labels: research

#4974 Add CTSI token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4982 Move XCHAIN Under review
  packages/config/src/projects/layer2s/xchain.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4984 Polygon PoS and Plasma - Restore TimeLock in config
  packages/backend/discovery/polygon-plasma/ethereum/config.jsonc
  packages/backend/discovery/polygon-plasma/ethereum/diffHistory.md
  packages/backend/discovery/polygon-plasma/ethereum/discovered.json
  packages/backend/discovery/polygon-pos/ethereum/config.jsonc
  packages/backend/discovery/polygon-pos/ethereum/diffHistory.md
  packages/backend/discovery/polygon-pos/ethereum/discovered.json
  packages/config/src/projects/bridges/polygonplasma.ts
  packages/config/src/projects/bridges/polygonpos.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4985 Trivial discovery updates 09/03
  packages/backend/discovery/nebraupa/ethereum/config.jsonc
  packages/backend/discovery/nebraupa/ethereum/diffHistory.md
  packages/backend/discovery/nebraupa/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/projects/layer2s/galxegravity.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4990 Nitro bianca activation and Stylus support
  packages/config/src/projects/badges/index.ts
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/nova.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer2s/templates/utils.ts
  packages/frontend2/public/images/badges/WasmVM.png
Labels: research

#4994 Trivial discovery updates 09/04
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/mantle/ethereum/diffHistory.md
  packages/backend/discovery/mantle/ethereum/discovered.json
  packages/backend/discovery/polynetwork/ethereum/diffHistory.md
  packages/backend/discovery/polynetwork/ethereum/discovered.json
  packages/backend/discovery/ronin/ethereum/diffHistory.md
  packages/backend/discovery/ronin/ethereum/discovered.json
  packages/backend/discovery/zklinknova/arbitrum/diffHistory.md
  packages/backend/discovery/zklinknova/arbitrum/discovered.json
  packages/backend/discovery/zklinknova/base/diffHistory.md
  packages/backend/discovery/zklinknova/base/discovered.json
  packages/backend/discovery/zklinknova/blast/diffHistory.md
  packages/backend/discovery/zklinknova/blast/discovered.json
  packages/backend/discovery/zklinknova/ethereum/diffHistory.md
  packages/backend/discovery/zklinknova/ethereum/discovered.json
  packages/backend/discovery/zklinknova/linea/diffHistory.md
  packages/backend/discovery/zklinknova/linea/discovered.json
  packages/backend/discovery/zklinknova/mantapacific/diffHistory.md
  packages/backend/discovery/zklinknova/mantapacific/discovered.json
  packages/backend/discovery/zklinknova/mantle/diffHistory.md
  packages/backend/discovery/zklinknova/mantle/discovered.json
  packages/backend/discovery/zklinknova/optimism/diffHistory.md
  packages/backend/discovery/zklinknova/optimism/discovered.json
  packages/backend/discovery/zklinknova/scroll/diffHistory.md
  packages/backend/discovery/zklinknova/scroll/discovered.json
  packages/backend/discovery/zklinknova/zksync2/diffHistory.md
  packages/backend/discovery/zklinknova/zksync2/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4996 Add incidents
  packages/config/src/projects/bridges/multichain.ts
  packages/config/src/projects/bridges/nomad.ts
  packages/config/src/projects/bridges/orbit.ts
  packages/config/src/projects/bridges/polynetwork.ts
  packages/config/src/projects/bridges/portal.ts
  packages/config/src/projects/bridges/ronin.ts
Labels: research

#4999 Add GPTProtocol (full)
  packages/backend/discovery/gpt/ethereum/config.jsonc
  packages/backend/discovery/gpt/ethereum/diffHistory.md
  packages/backend/discovery/gpt/ethereum/discovered.json
  packages/config/src/projects/layer2s/astarzkevm.ts
  packages/config/src/projects/layer2s/gpt.ts
  packages/config/src/projects/layer2s/polygonzkevm.ts
  packages/config/src/projects/layer2s/templates/polygonCDKStack.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/frontend2/public/images/architecture/gpt.png
Labels: research

#5023 Add incidents for kroma, base, scroll
  packages/config/src/projects/layer2s/base.ts
  packages/config/src/projects/layer2s/kroma.ts
  packages/config/src/projects/layer2s/scroll.ts
Labels: research

#5024 Trivial discovery updates 09/06
  packages/backend/discovery/immutablezkevm/ethereum/diffHistory.md
  packages/backend/discovery/immutablezkevm/ethereum/discovered.json
  packages/backend/discovery/nebraupa/ethereum/diffHistory.md
  packages/backend/discovery/nebraupa/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
Labels: trivial-discovery

#5029 ZK stack governance system upgrade
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
Labels: research

#5033 Trivial discovery updates 09/09
  packages/backend/discovery/paradex/ethereum/diffHistory.md
  packages/backend/discovery/paradex/ethereum/discovered.json
  packages/backend/discovery/parallel/ethereum/diffHistory.md
  packages/backend/discovery/parallel/ethereum/discovered.json
  packages/backend/discovery/sanko/arbitrum/config.jsonc
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/zkfair/ethereum/diffHistory.md
  packages/backend/discovery/zkfair/ethereum/discovered.json
  packages/config/src/projects/layer2s/paradex.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer3s/sanko.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
  packages/l2b/src/commands/StarknetProgramHashes.ts
Labels: trivial-discovery

#5042 Zk stack BridgeHub upgrade
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5053 Polygon bridge merge
  packages/backend/discovery/_templates/polygonposbridge/predicate/template.jsonc
  packages/backend/discovery/polygon-plasma/ethereum/config.jsonc
  packages/backend/discovery/polygon-plasma/ethereum/diffHistory.md
  packages/backend/discovery/polygon-plasma/ethereum/discovered.json
  packages/backend/discovery/polygon-pos/ethereum/config.jsonc
  packages/backend/discovery/polygon-pos/ethereum/diffHistory.md
  packages/backend/discovery/polygon-pos/ethereum/discovered.json
  packages/config/src/projects/bridges/index.ts
  packages/config/src/projects/bridges/polygonplasma.ts
  packages/config/src/projects/bridges/polygonpos.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend2/public/icons/polygon-plasma.png
  packages/frontend2/scripts/logos/tinifiedLogos.json
Labels: research

#5065 Trivial discovery updates 09/11
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/scripts/socketcrawl/index.test.ts
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#5060 add AcrossV3 multichain escrows
  packages/config/package.json
  packages/config/scripts/fillts/index.ts
  packages/config/src/projects/bridges/acrossV3.ts
Labels: research

#5109 Trivial discovery updates 09/15
  packages/backend/discovery/_templates/gnosisSafeModules/DeputyGuardianModule/shape/DeputyGuardianModulev1_0_1.sol
  packages/backend/discovery/_templates/gnosisSafeModules/DeputyGuardianModule/shape/DeputyGuardianModulev2_0_0.sol
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/eclipse/ethereum/diffHistory.md
  packages/backend/discovery/eclipse/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/metal/ethereum/diffHistory.md
  packages/backend/discovery/metal/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/nebraupa/ethereum/config.jsonc
  packages/backend/discovery/nebraupa/ethereum/diffHistory.md
  packages/backend/discovery/nebraupa/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-sharp-verifier/ethereum/diffHistory.md
  packages/backend/discovery/shared-sharp-verifier/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/projects/layer2s/base.ts
  packages/config/src/projects/layer2s/metal.ts
  packages/config/src/projects/layer2s/mode.ts
  packages/config/src/projects/layer2s/optimism.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5098 ZK stack - SecurityCouncil Gov upgrade
  packages/backend/discovery/_templates/shared-zk-stack/ZkGovernor/template.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/zksync2/config.jsonc
  packages/backend/discovery/shared-zk-stack/zksync2/diffHistory.md
  packages/backend/discovery/shared-zk-stack/zksync2/discovered.json
  packages/backend/discovery/zksync2/ethereum/config.jsonc
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/common/contracts.ts
  packages/config/src/common/riskView.ts
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/projects/layer2s/optimism.ts
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend/public/images/architecture/cronoszkevm.png
  packages/frontend/public/images/architecture/zksync-era.png
  packages/frontend/public/images/upgrades-and-governance/cronoszkevm.png
  packages/frontend/public/images/upgrades-and-governance/zksync-era.png
Labels: research

#5129 Rename elastic chain operator
  packages/frontend/public/images/upgrades-and-governance/zksync-era.png
Labels: trivial

#5143 Trivial discovery updates 09/18
  packages/backend/discovery/aevo/ethereum/diffHistory.md
  packages/backend/discovery/aevo/ethereum/discovered.json
  packages/backend/discovery/ancient/ethereum/diffHistory.md
  packages/backend/discovery/ancient/ethereum/discovered.json
  packages/backend/discovery/bob/ethereum/diffHistory.md
  packages/backend/discovery/bob/ethereum/discovered.json
  packages/backend/discovery/eclipse/ethereum/diffHistory.md
  packages/backend/discovery/eclipse/ethereum/discovered.json
  packages/backend/discovery/hypr/ethereum/diffHistory.md
  packages/backend/discovery/hypr/ethereum/discovered.json
  packages/backend/discovery/lyra/ethereum/diffHistory.md
  packages/backend/discovery/lyra/ethereum/discovered.json
  packages/backend/discovery/mantapacific/ethereum/diffHistory.md
  packages/backend/discovery/mantapacific/ethereum/discovered.json
  packages/backend/discovery/orderly/ethereum/diffHistory.md
  packages/backend/discovery/orderly/ethereum/discovered.json
  packages/backend/discovery/publicgoodsnetwork/ethereum/diffHistory.md
  packages/backend/discovery/publicgoodsnetwork/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/stack/base/diffHistory.md
  packages/backend/discovery/stack/base/discovered.json
  packages/backend/discovery/syndicateframe/base/diffHistory.md
  packages/backend/discovery/syndicateframe/base/discovered.json
Labels: trivial-discovery

#5144 Add allbridge TokenBridge permissions
  packages/backend/discovery/allbridge/ethereum/diffHistory.md
  packages/backend/discovery/allbridge/ethereum/discovered.json
  packages/config/src/projects/bridges/allbridge.ts
Labels: research

#5150 Add tokens to Mode and Base
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5148 Add ZKstack template, move Cronos out of review
  packages/backend/discovery/cronoszkevm/ethereum/config.jsonc
  packages/backend/discovery/cronoszkevm/ethereum/diffHistory.md
  packages/backend/discovery/cronoszkevm/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/projects/layer2s/templates/zkStack.ts
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/frontend/public/images/architecture/cronoszkevm.png
  packages/frontend/public/images/architecture/zksync-era.png
  packages/frontend/public/images/upgrades-and-governance/cronoszkevm.png
  packages/frontend/public/images/upgrades-and-governance/zksync-era.png
Labels: research

#5151 Add untilTimestamps to era trackedtxs (pauses liveness and costs tracking)
  packages/config/src/projects/layer2s/zksyncera.ts
Labels: research

#5164 Trivial discovery updates 09/19
  packages/backend/discovery/allbridge/ethereum/diffHistory.md
  packages/backend/discovery/allbridge/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
Labels: trivial-discovery

#5167 StargateV2 fix (architecture diagram, description)
  packages/config/src/projects/bridges/stargatev2.ts
  packages/config/src/verification/ethereum/manuallyVerified.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/public/images/architecture/stargatev2.png
Labels: research

#5157 Add DeBank Chain (full)
  packages/backend/discovery/_templates/opstack/L1CrossDomainMessenger/shape/L1CrossDomainMessenger_v2_4_0_allgas.sol
  packages/backend/discovery/_templates/opstack/L1StandardBridge/shape/L1StandardBridge_v2_2_0_allgas.sol
  packages/backend/discovery/_templates/opstack/OptimismPortal/shape/OptimismPortal_v2_8_0.sol
  packages/backend/discovery/_templates/opstack/SystemConfig/shape/SystemConfig_v2_3_0_beta_1.sol
  packages/backend/discovery/dbk/ethereum/config.jsonc
  packages/backend/discovery/dbk/ethereum/diffHistory.md
  packages/backend/discovery/dbk/ethereum/discovered.json
  packages/config/src/projects/layer2s/dbk.ts
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/public/icons/dbk.png
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend/scripts/logos/tinifyLogos.ts
Labels: research

#5158 Add Silicon zkEVM (full)
  packages/backend/discovery/silicon/ethereum/config.jsonc
  packages/backend/discovery/silicon/ethereum/diffHistory.md
  packages/backend/discovery/silicon/ethereum/discovered.json
  packages/config/src/projects/layer2s/silicon.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5179 Remove finality dbk
  packages/config/src/projects/layer2s/dbk.ts
Labels: trivial

#5182 Add Thanos (upcoming)
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/thanos.ts
  packages/config/src/verification/projects.json
  packages/frontend/public/icons/dbk.png
  packages/frontend/public/icons/soon.png
  packages/frontend/public/icons/thanos.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: trivial

#5198 Trivial discovery updates 09/23
  packages/backend/discovery/arbitrum/arbitrum/diffHistory.md
  packages/backend/discovery/arbitrum/arbitrum/discovered.json
  packages/backend/discovery/commonAddressNames.jsonc
  packages/backend/discovery/molten/arbitrum/config.jsonc
  packages/backend/discovery/molten/arbitrum/diffHistory.md
  packages/backend/discovery/molten/arbitrum/discovered.json
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/rari/arbitrum/config.jsonc
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/config/src/projects/bridges/omni.ts
  packages/config/src/projects/layer2s/mode.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5199 add Stargate Hydra tokens
  packages/config/src/projects/layer3s/rari.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5222 Trivial discovery 09/25
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/globalTypes.jsonc
  packages/backend/discovery/nebraupa/ethereum/diffHistory.md
  packages/backend/discovery/nebraupa/ethereum/discovered.json
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/playblock/nova/diffHistory.md
  packages/backend/discovery/playblock/nova/discovered.json
  packages/backend/discovery/xlayer/ethereum/config.jsonc
  packages/backend/discovery/xlayer/ethereum/diffHistory.md
  packages/backend/discovery/xlayer/ethereum/discovered.json
  packages/backend/discovery/zircuit/ethereum/diffHistory.md
  packages/backend/discovery/zircuit/ethereum/discovered.json
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/nova.ts
  packages/config/src/projects/layer2s/thanos.ts
  packages/config/src/projects/other/zk-catalog/index.ts
  packages/discovery/src/discovery/handlers/decodeHandlerResults.ts
Labels: trivial-discovery

#5246 Trivial discovery updates 09/27
  packages/backend/discovery/_templates/transporter/OnRampV3/template.jsonc
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/deri/arbitrum/diffHistory.md
  packages/backend/discovery/deri/arbitrum/discovered.json
  packages/backend/discovery/edgeless/ethereum/diffHistory.md
  packages/backend/discovery/edgeless/ethereum/discovered.json
  packages/backend/discovery/galxegravity/ethereum/diffHistory.md
  packages/backend/discovery/galxegravity/ethereum/discovered.json
  packages/backend/discovery/hychain/ethereum/diffHistory.md
  packages/backend/discovery/hychain/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/molten/arbitrum/diffHistory.md
  packages/backend/discovery/molten/arbitrum/discovered.json
  packages/backend/discovery/parallel/ethereum/diffHistory.md
  packages/backend/discovery/parallel/ethereum/discovered.json
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/popboss/arbitrum/diffHistory.md
  packages/backend/discovery/popboss/arbitrum/discovered.json
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
  packages/backend/discovery/reya/ethereum/diffHistory.md
  packages/backend/discovery/reya/ethereum/discovered.json
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/shared-sharp-verifier/ethereum/diffHistory.md
  packages/backend/discovery/shared-sharp-verifier/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/sxnetwork/ethereum/diffHistory.md
  packages/backend/discovery/sxnetwork/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5262 Trivial discovery updates 09/30
  packages/backend/discovery/cronoszkevm/ethereum/config.jsonc
  packages/backend/discovery/cronoszkevm/ethereum/diffHistory.md
  packages/backend/discovery/cronoszkevm/ethereum/discovered.json
  packages/backend/discovery/l3x/arbitrum/diffHistory.md
  packages/backend/discovery/l3x/arbitrum/discovered.json
  packages/backend/discovery/polygon-pos/ethereum/diffHistory.md
  packages/backend/discovery/polygon-pos/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery
