Repository l2beat/l2beat, pull requests merged in 2024-04, with the labels that each got.

#3226 Treat discovery updates related to threshold config
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/linea/ethereum/meta.json
  packages/backend/discovery/lzomnichain/arbitrum/diffHistory.md
  packages/backend/discovery/lzomnichain/arbitrum/discovered.json
  packages/backend/discovery/lzomnichain/ethereum/diffHistory.md
  packages/backend/discovery/lzomnichain/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/polygonpos/diffHistory.md
  packages/backend/discovery/lzomnichain/polygonpos/discovered.json
  packages/backend/discovery/rss3/ethereum/diffHistory.md
  packages/backend/discovery/rss3/ethereum/discovered.json
Labels: trivial

#3239 Base disc update: Raise L2 gas limit 33%
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
Labels: trivial-discovery

#3240 Kroma disc updates: Root Challenged
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/backend/discovery/kroma/ethereum/meta.json
Labels: trivial-discovery

#3253 Fraxtal update: One signer changed
  packages/backend/discovery/fraxtal/ethereum/diffHistory.md
  packages/backend/discovery/fraxtal/ethereum/discovered.json
  packages/backend/discovery/fraxtal/ethereum/meta.json
Labels: trivial-discovery

#3229 Add Coti L2 to upcoming projects
  packages/config/src/layer2s/coti.ts
  packages/config/src/layer2s/index.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/cli/tinifyLogos.ts
  packages/frontend/src/static/icons/coti.png
Labels: trivial

#3241 Add Degen L3 in review
  packages/config/src/layer3s/degen.ts
  packages/config/src/layer3s/index.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/degen.png
Labels: trivial, research

#3235 Add more tokens (in order of their tvl on arbitrum)
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#3254 Treat discovery updates related to threshold config
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/arbitrum/diffHistory.md
  packages/backend/discovery/lzomnichain/arbitrum/discovered.json
  packages/backend/discovery/lzomnichain/ethereum/diffHistory.md
  packages/backend/discovery/lzomnichain/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/optimism/diffHistory.md
  packages/backend/discovery/lzomnichain/optimism/discovered.json
  packages/backend/discovery/rss3/ethereum/diffHistory.md
  packages/backend/discovery/rss3/ethereum/discovered.json
Labels: trivial-discovery

#3233 Expose data for the l2costs chart
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/repositories/L2CostsRepository.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/repositories/L2CostsRepository.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/types/DetailedTransaction.ts
  packages/backend/src/modules/tracked-txs/modules/utils/addToMap.ts
  packages/shared-pure/src/types/api/L2CostsApi.ts
Labels: code

#3250 Add kinto (full)
  packages/backend/discovery/kinto/ethereum/config.jsonc
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/meta.json
  packages/config/src/layer2s/kinto.ts
  packages/config/src/layer2s/templates/orbitStack.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#3267 Add warning to Arbitrum forks
  packages/config/src/layer2s/nova.ts
  packages/config/src/layer2s/templates/orbitStack.ts
Labels: trivial

#3280 Base blobstream discovery update: config related
  packages/backend/discovery/blobstream/base/diffHistory.md
  packages/backend/discovery/blobstream/base/discovered.json
Labels: trivial-discovery

#3257 Add ezETH as EBV to Linea and Blast
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#2983 Add frax ferry bridge
  packages/backend/discovery/fraxferry/ethereum/config.jsonc
  packages/backend/discovery/fraxferry/ethereum/diffHistory.md
  packages/backend/discovery/fraxferry/ethereum/discovered.json
  packages/backend/discovery/fraxferry/ethereum/meta.json
  packages/config/src/bridges/fraxferry.ts
  packages/config/src/bridges/index.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/fraxferry.png
  packages/frontend/src/static/images/architecture/fraxferry.png
Labels: research

#3283 Socket discovery: New plug
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/meta.json
  packages/config/src/bridges/socket-vaults.json
Labels: trivial-discovery

#3274 Polynetwork update: new lockProxy added
  packages/backend/discovery/polynetwork/ethereum/config.jsonc
  packages/backend/discovery/polynetwork/ethereum/diffHistory.md
  packages/backend/discovery/polynetwork/ethereum/discovered.json
  packages/backend/discovery/polynetwork/ethereum/meta.json
  packages/config/src/bridges/polynetwork.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#3285 Add edgeless underreview
  packages/config/src/layer2s/edgeless.ts
  packages/config/src/layer2s/index.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/edgeless.png
Labels: research

#3290 Fraxferry discovery: FPI bridge owner Multisig signer changed
  packages/backend/discovery/fraxferry/ethereum/config.jsonc
  packages/backend/discovery/fraxferry/ethereum/diffHistory.md
  packages/backend/discovery/fraxferry/ethereum/discovered.json
  packages/backend/discovery/fraxferry/ethereum/meta.json
  packages/config/src/bridges/fraxferry.ts
Labels: trivial-discovery

#3302 Fraxferry discovery: no change.
  packages/backend/discovery/fraxferry/ethereum/diffHistory.md
  packages/backend/discovery/fraxferry/ethereum/discovered.json
Labels: trivial-discovery

#3291 Blobstream discovery: no change
  packages/backend/discovery/blobstream/arbitrum/diffHistory.md
  packages/backend/discovery/blobstream/arbitrum/discovered.json
Labels: trivial-discovery

#3309 Socket discovery: New unverified plug
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/meta.json
  packages/config/src/bridges/socket-vaults.json
Labels: trivial-discovery

#3319 Change type from EBV to NMV for 3 LayerZero bridged tokens on L2s
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3264 Add arbitrum canonically bridged tokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3170 Add Starknet Upgrades/Gov section
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/config/src/layer2s/starknet.ts
  packages/frontend/src/static/images/upgrades-and-governance/starknet.png
Labels: research

#3211 Across implementation updates - V3
  packages/backend/discovery/across-v2/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/config.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/across-v3/ethereum/meta.json
  packages/config/src/bridges/acrossV2.ts
  packages/config/src/bridges/acrossV3.ts
  packages/config/src/bridges/index.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/acrossv3.png
  packages/frontend/src/static/images/architecture/acrossV3.png
Labels: research

#3341 Add costs multiplier to L2Costs controller
  packages/backend/src/model/Project.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/types/DetailedTransaction.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxsConfig.ts
  packages/config/src/layer2s/index.test.ts
  packages/config/src/layer2s/starknet.ts
  packages/config/src/layer2s/types/Layer2TrackedTxsConfig.ts
  packages/config/src/layer2s/zksynclite.ts
Labels: code

#3351 Add Base native tokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3361 Update starknet costs warning
  packages/config/src/layer2s/starknet.ts
Labels: trivial

#3345 Amarok update: Lower the bond of the optimistic governor
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
Labels: trivial-discovery

#3360 Bring back risk summary section
  packages/frontend/src/components/project/sectionId.ts
  packages/frontend/src/pages/bridges/projects/props/getProjectDetails.ts
  packages/frontend/src/pages/layer3s/props/getProjectDetails.ts
  packages/frontend/src/pages/layer3s/view/ProjectDetails.tsx
  packages/frontend/src/pages/scaling/projects/props/getProjectDetails.ts
  packages/frontend/src/pages/scaling/projects/view/ProjectDetails.tsx
  packages/frontend/src/utils/project/getRiskSection.ts
Labels: code

#3350 Parallel updates: Upgrade to ArbOS 20, new SequencerInbox
  packages/backend/discovery/parallel/ethereum/diffHistory.md
  packages/backend/discovery/parallel/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: research

#3370 Update Polygon CDK discovery to discard update-monitor notification
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/meta.json
Labels: trivial-discovery

#3369 AcrossV3 updates: Config related
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
Labels: trivial-discovery

#3373 Add Proof of Play Apex (full)
  packages/backend/discovery/popapex/arbitrum/config.jsonc
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/popapex/arbitrum/meta.json
  packages/config/src/layer3s/popapex.ts
  packages/config/src/verification/arbitrum/verified.json
Labels: research

#3387 Allow to configure activity for underReview projects
  packages/config/src/layer2s/templates/underReview.ts
Labels: trivial

#3395 feat: update RSS3 logo
  packages/config/src/layer2s/rss3.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/rss3.png
Labels: trivial

#3394 OP Mainnet: upgrade 6 review
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/config/src/layer2s/optimism.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend/src/static/images/upgrades-and-governance/optimism.png
Labels: research

#3399 Tidy up acrossv3 discovery config
  packages/backend/discovery/across-v3/ethereum/config.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/across-v3/ethereum/meta.json
  packages/config/src/bridges/acrossV3.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#3374 Rhinofi update: Blocklist implemented
  packages/backend/discovery/deversifi/ethereum/config.jsonc
  packages/backend/discovery/deversifi/ethereum/diffHistory.md
  packages/backend/discovery/deversifi/ethereum/discovered.json
  packages/backend/discovery/deversifi/ethereum/meta.json
  packages/config/src/common/exits.ts
  packages/config/src/common/riskView.ts
  packages/config/src/layer2s/rhinofi.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#3402 Fraxferry update: Fee change
  packages/backend/discovery/fraxferry/ethereum/config.jsonc
  packages/backend/discovery/fraxferry/ethereum/diffHistory.md
  packages/backend/discovery/fraxferry/ethereum/discovered.json
  packages/backend/discovery/fraxferry/ethereum/meta.json
  packages/config/src/bridges/fraxferry.ts
Labels: trivial-discovery

#3410 Release L2Costs
  packages/frontend/src/build/config/config.production.ts
Labels: code

#3409 Update gitcoin banner
  packages/frontend/src/build/config/common.ts
  packages/frontend/src/components/PageWrapper.tsx
  packages/frontend/src/components/gitcoin/FloatingBanner.tsx
  packages/frontend/src/components/gitcoin/TopBar.tsx
  packages/frontend/src/components/l2warsaw/TopBar.tsx
  packages/frontend/src/components/navbar/Banner.tsx
  packages/frontend/src/components/table/ValueWithPercentageCell.tsx
  packages/frontend/src/pages/scaling/costs/props/getScalingCostsColumnsConfig.tsx
  packages/frontend/src/pages/scaling/costs/view/CostsBreakdownValueCell.tsx
  packages/frontend/src/pages/scaling/costs/view/CostsTotalCell.tsx
  packages/frontend/src/pages/scaling/costs/view/CostsTxCountCell.tsx
  packages/frontend/src/scripts/configureFloatingBanner.ts
  packages/frontend/src/scripts/configureTopBars.ts
  packages/frontend/src/scripts/index.ts
  packages/frontend/src/scripts/local-storage/LocalStorage.ts
  packages/frontend/src/static/images/announcements/gitcoin-19-floating.png
  packages/frontend/src/static/images/announcements/gitcoin-20-floating.png
  packages/frontend/src/utils/constants.ts
Labels: code

#3429 Show risk rosette when project under review but has risk rossete
  packages/frontend/src/components/rosette/Rosette.tsx
  packages/frontend/src/components/table/RosetteCell.tsx
  packages/frontend/src/pages/scaling/summary/props/getScalingSummaryColumnsConfig.tsx
Labels: code

#3437 Trivial discovery updates
  packages/backend/discovery/cbridge/ethereum/diffHistory.md
  packages/backend/discovery/cbridge/ethereum/discovered.json
  packages/backend/discovery/cbridge/ethereum/meta.json
  packages/backend/discovery/fraxferry/ethereum/diffHistory.md
  packages/backend/discovery/fraxferry/ethereum/discovered.json
  packages/backend/discovery/loopring/ethereum/diffHistory.md
  packages/backend/discovery/loopring/ethereum/discovered.json
  packages/backend/discovery/portal/ethereum/diffHistory.md
  packages/backend/discovery/portal/ethereum/discovered.json
  packages/backend/discovery/portal/ethereum/meta.json
Labels: trivial-discovery

#3435 Kroma update: Reimbursement of a validator
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
Labels: trivial-discovery

#3400 Cbridge update: SentinelAdmin changed to SimpleGov
  packages/backend/discovery/cbridge/ethereum/diffHistory.md
  packages/backend/discovery/cbridge/ethereum/discovered.json
  packages/config/src/bridges/cBridge.ts
Labels: trivial-discovery

#3477 Across v3 update: Dispute window decreased
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
Labels: trivial-discovery

#3457 Add rsETH (LayerZero bridged) by KelpDAO to L2s that support it
  packages/config/src/layer2s/scroll.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#3490 Add PacMoon token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3436 Review of Eigenlayer M2 upgrade
  packages/backend/discovery/eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/eigenlayer/ethereum/discovered.json
  packages/backend/discovery/eigenlayer/ethereum/meta.json
Labels: research

#3489 Move metal to in review
  packages/backend/discovery/metal/ethereum/config.jsonc
  packages/backend/discovery/metal/ethereum/diffHistory.md
  packages/backend/discovery/metal/ethereum/discovered.json
  packages/backend/discovery/metal/ethereum/meta.json
  packages/config/src/layer2s/metal.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#3491 Cbridge Update: Sentinel unrelaxed
  packages/backend/discovery/cbridge/ethereum/diffHistory.md
  packages/backend/discovery/cbridge/ethereum/discovered.json
  packages/backend/discovery/cbridge/ethereum/meta.json
Labels: trivial-discovery

#3389 Update Liveness page to show Not synced
  packages/frontend/src/build/api/fetchLivenessApi.ts
  packages/frontend/src/components/badge/NotSyncedBadge.tsx
  packages/frontend/src/components/table/FinalityDurationCell.tsx
  packages/frontend/src/components/table/GrayedOut.tsx
  packages/frontend/src/components/table/LivenessDurationCell.tsx
  packages/frontend/src/pages/scaling/finality/props/getScalingFinalityView.ts
  packages/frontend/src/pages/scaling/liveness/props/getScalingLivenessColumnsConfig.tsx
  packages/frontend/src/pages/scaling/liveness/props/getScalingLivenessView.tsx
  packages/frontend/src/pages/scaling/liveness/types.ts
  packages/frontend/src/pages/scaling/liveness/view/LivenessDurationTimeRangeCell.tsx
  packages/frontend/src/pages/scaling/liveness/view/ScalingLivenessView.stories.tsx
  packages/frontend/src/pages/types.ts
Labels: code

#3484 Starknet update: Bridges governance hardened
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/config/src/layer2s/starknet.ts
Labels: trivial-discovery

#3501 zkFair update: DAC URLs changed
  packages/backend/discovery/zkfair/ethereum/diffHistory.md
  packages/backend/discovery/zkfair/ethereum/discovered.json
  packages/backend/discovery/zkfair/ethereum/meta.json
Labels: trivial-discovery

#3498 Add zkSync Era native tokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3504 Boba update: unsafeBlockSigner replaced
  packages/backend/discovery/bobanetwork/ethereum/diffHistory.md
  packages/backend/discovery/bobanetwork/ethereum/discovered.json
  packages/backend/discovery/bobanetwork/ethereum/meta.json
Labels: trivial-discovery

#3511 Kroma update: Blobs
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/config/src/layer2s/kroma.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#3508 X Layer update: Config related
  packages/backend/discovery/xlayer/ethereum/diffHistory.md
  packages/backend/discovery/xlayer/ethereum/discovered.json
Labels: trivial-discovery

#3405 Xai update: V2 staking pools
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/backend/discovery/xai/arbitrum/meta.json
  packages/config/src/layer3s/xai.ts
  packages/config/src/verification/arbitrum/verified.json
Labels: research

#3536 Add STONE token to scroll
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3543 Metis update: Ignore sequencer stats in watch mode
  packages/backend/discovery/metis/ethereum/config.jsonc
  packages/backend/discovery/metis/ethereum/diffHistory.md
  packages/backend/discovery/metis/ethereum/discovered.json
Labels: trivial-discovery

#3546 Add Foxy
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3545 fix: rollup L3s on L2 rollups use blobs
  packages/config/src/layer2s/parallel.ts
  packages/config/src/layer2s/templates/orbitStack.ts
  packages/config/src/layer3s/deri.ts
  packages/config/src/layer3s/syndicateframe.ts
Labels: trivial

#3556 Add KOI and HOLD
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#3547 Eigenlayer update: EIGEN token
  packages/backend/discovery/eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/eigenlayer/ethereum/discovered.json
Labels: research
