Repository l2beat/l2beat, pull requests merged in 2024-07, with the labels that each got.

#4277 Add Orderly escrows, description and archi diagram
  packages/config/src/projects/layer2s/orderly.ts
  packages/frontend2/public/images/architecture/orderly.png
Labels: research

#4341 Add AlienX under review (+escrows)
  packages/config/src/projects/layer2s/alienx.ts
  packages/config/src/projects/layer2s/index.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/alienx.png
Labels: trivial-discovery

#4334 Trivial discovery updates 07/01
  packages/backend/discovery/metal/ethereum/config.jsonc
  packages/backend/discovery/metal/ethereum/diffHistory.md
  packages/backend/discovery/metal/ethereum/discovered.json
  packages/backend/discovery/metis/ethereum/diffHistory.md
  packages/backend/discovery/metis/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/config.jsonc
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/config.jsonc
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/config.jsonc
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/config/scripts/socket/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socket/outfiles/socket-crawl-result.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4342 Add USD+ to Kinto
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4346 Trivial discovery updates 07/02
  packages/backend/discovery/_templates/transporter/TokenPool/template.jsonc
  packages/backend/discovery/degen/base/config.jsonc
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/verification/base/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4348 Add Hook chain inreview (+escrows)
  packages/config/src/projects/layer3s/hook.ts
  packages/config/src/projects/layer3s/index.test.ts
  packages/config/src/projects/layer3s/index.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/hook.png
Labels: research

#4358 Fix LPT escrow
  packages/config/src/projects/layer2s/arbitrum.ts
Labels: trivial

#4366 Add SMOKE token
  packages/config/src/projects/layer3s/sanko.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4367 Trivial discovery updates 07/03
  packages/backend/discovery/polygon-plasma/ethereum/diffHistory.md
  packages/backend/discovery/polygon-plasma/ethereum/discovered.json
  packages/backend/discovery/termstructure/ethereum/config.jsonc
  packages/backend/discovery/termstructure/ethereum/diffHistory.md
  packages/backend/discovery/termstructure/ethereum/discovered.json
Labels: trivial-discovery

#4361 More added tokens
  packages/config/scripts/socket/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socket/outfiles/socket-crawl-result.json
  packages/config/src/projects/layer3s/hook.ts
  packages/config/src/projects/layer3s/mxc.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4374 Scroll: Curie upgrade, new verifier
  packages/backend/discovery/scroll/ethereum/config.jsonc
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/config/src/projects/layer2s/scroll.ts
  packages/config/src/verification/ethereum/manuallyVerified.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#4382 Trivial discovery updates 07/04
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
Labels: trivial-discovery

#4385 Socket multichain escrows (kinto, hook)
  packages/config/src/projects/bridges/index.test.ts
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/projects/layer3s/hook.ts
  packages/config/src/test/projects.test.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tokens/tokens.ts
Labels: research

#4397 Tidy polycdk upcoming projects
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/projects/layer2s/gpt.ts
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/oev.ts
  packages/config/src/projects/layer2s/wirex.ts
  packages/config/src/projects/layer2s/witness.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend/scripts/logos/tinifyLogos.ts
  packages/frontend2/public/icons/gpt.png
  packages/frontend2/public/icons/wirex.png
  packages/frontend2/public/icons/witness.png
Labels: research

#4402 LayerZero multichain: Update configs and review LayerZero executor upgrade
  packages/backend/discovery/layerzerov2oft/ethereum/config.jsonc
  packages/backend/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/backend/discovery/layerzerov2oft/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/arbitrum/config.jsonc
  packages/backend/discovery/lzomnichain/arbitrum/diffHistory.md
  packages/backend/discovery/lzomnichain/arbitrum/discovered.json
  packages/backend/discovery/lzomnichain/base/config.jsonc
  packages/backend/discovery/lzomnichain/base/diffHistory.md
  packages/backend/discovery/lzomnichain/base/discovered.json
  packages/backend/discovery/lzomnichain/ethereum/config.jsonc
  packages/backend/discovery/lzomnichain/ethereum/diffHistory.md
  packages/backend/discovery/lzomnichain/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/linea/config.jsonc
  packages/backend/discovery/lzomnichain/linea/diffHistory.md
  packages/backend/discovery/lzomnichain/linea/discovered.json
  packages/backend/discovery/lzomnichain/optimism/config.jsonc
  packages/backend/discovery/lzomnichain/optimism/diffHistory.md
  packages/backend/discovery/lzomnichain/optimism/discovered.json
  packages/backend/discovery/lzomnichain/polygonpos/config.jsonc
  packages/backend/discovery/lzomnichain/polygonpos/diffHistory.md
  packages/backend/discovery/lzomnichain/polygonpos/discovered.json
  packages/backend/discovery/stargate/ethereum/config.jsonc
  packages/backend/discovery/stargate/ethereum/diffHistory.md
  packages/backend/discovery/stargate/ethereum/discovered.json
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
Labels: trivial-discovery

#4434 Add M-BTC to Kroma
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4447 Ignore spam in zklinknova template
  packages/backend/discovery/_templates/zklinknova/secondaryZkLink/template.jsonc
  packages/backend/discovery/zklinknova/arbitrum/diffHistory.md
  packages/backend/discovery/zklinknova/arbitrum/discovered.json
  packages/backend/discovery/zklinknova/base/diffHistory.md
  packages/backend/discovery/zklinknova/base/discovered.json
  packages/backend/discovery/zklinknova/blast/diffHistory.md
  packages/backend/discovery/zklinknova/blast/discovered.json
  packages/backend/discovery/zklinknova/ethereum/diffHistory.md
  packages/backend/discovery/zklinknova/ethereum/discovered.json
  packages/backend/discovery/zklinknova/mantapacific/diffHistory.md
  packages/backend/discovery/zklinknova/mantapacific/discovered.json
  packages/backend/discovery/zklinknova/mantle/diffHistory.md
  packages/backend/discovery/zklinknova/mantle/discovered.json
  packages/backend/discovery/zklinknova/optimism/diffHistory.md
  packages/backend/discovery/zklinknova/optimism/discovered.json
  packages/backend/discovery/zklinknova/scroll/diffHistory.md
  packages/backend/discovery/zklinknova/scroll/discovered.json
Labels: trivial-discovery

#4450 Trivial discovery updates 07/11
  packages/backend/discovery/_templates/acrossv3/adapter/template.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/amarok/ethereum/config.jsonc
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/projects/bridges/amarok.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4451 Make MXC underreview due to newly verified contracts
  packages/backend/discovery/mxc/arbitrum/config.jsonc
  packages/backend/discovery/mxc/arbitrum/diffHistory.md
  packages/backend/discovery/mxc/arbitrum/discovered.json
  packages/backend/discovery/mxc/ethereum/diffHistory.md
  packages/backend/discovery/mxc/ethereum/discovered.json
  packages/config/src/projects/layer3s/mxc.ts
Labels: trivial

#4452 Move Wirex Pay Chain under review (launched on polygoncdk)
  packages/config/src/projects/layer2s/wirex.ts
Labels: trivial

#4453 Add crvUSD token on Ethereum mainnet
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4457 Review Optimism Fjord upgrade
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/optimism/optimism/config.jsonc
  packages/backend/discovery/optimism/optimism/diffHistory.md
  packages/backend/discovery/optimism/optimism/discovered.json
  packages/config/src/projects/layer2s/optimism.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#4468 Update Cairo badge name
  packages/config/src/projects/badges/index.ts
Labels: trivial

#4469 Add Curie Milestone to Scroll
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/config/src/projects/layer2s/scroll.ts
Labels: trivial

#4465 Taiko upgrade 1.8.0
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: research

#4472 rename reddioEx to RedSonic
  packages/config/src/projects/layer2s/reddioex.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/redsonic.png
Labels: trivial

#4473 Order polygon validiums under the shared escrow
  packages/frontend/src/utils/orderByTvl.ts
Labels: trivial

#4462 Trivial discovery updates 07/15
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/backend/discovery/cbridge/ethereum/diffHistory.md
  packages/backend/discovery/cbridge/ethereum/discovered.json
  packages/backend/discovery/opticsV2/celo/diffHistory.md
  packages/backend/discovery/opticsV2/celo/discovered.json
  packages/backend/discovery/opticsV2/ethereum/diffHistory.md
  packages/backend/discovery/opticsV2/ethereum/discovered.json
  packages/backend/discovery/scroll/ethereum/config.jsonc
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/backend/discovery/termstructure/ethereum/diffHistory.md
  packages/backend/discovery/termstructure/ethereum/discovered.json
  packages/backend/discovery/zklinknova/mantapacific/diffHistory.md
  packages/backend/discovery/zklinknova/mantapacific/discovered.json
  packages/backend/discovery/zklinknova/mantle/diffHistory.md
  packages/backend/discovery/zklinknova/mantle/discovered.json
  packages/backend/discovery/zkswap/ethereum/config.jsonc
  packages/backend/discovery/zkswap/ethereum/diffHistory.md
  packages/backend/discovery/zkswap/ethereum/discovered.json
  packages/config/src/projects/layer2s/scroll.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4479 Update gov badge
  packages/config/src/projects/badges/index.ts
  packages/config/src/projects/layer2s/dydx.ts
  packages/config/src/projects/layer2s/nova.ts
Labels: trivial

#4480 Add all socket tokens to Lyra via escrows, remove them from tokens.jsonc
  packages/config/src/projects/layer2s/lyra.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4494 Remove MXC (not meeting L3 requirements)
  packages/backend/discovery/mxc/arbitrum/config.jsonc
  packages/backend/discovery/mxc/arbitrum/diffHistory.md
  packages/backend/discovery/mxc/arbitrum/discovered.json
  packages/backend/discovery/mxc/ethereum/config.jsonc
  packages/backend/discovery/mxc/ethereum/diffHistory.md
  packages/backend/discovery/mxc/ethereum/discovered.json
  packages/config/src/projects/layer3s/index.ts
  packages/config/src/projects/layer3s/mxc.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/mxc.png
Labels: research

#4502 Update Linea badge visual
  packages/frontend2/public/images/badges/Linea.png
Labels: trivial

#4505 Add RWA token to re.al
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4510 Fix polygoncdk permissions
  packages/backend/discovery/astarzkevm/ethereum/config.jsonc
  packages/backend/discovery/astarzkevm/ethereum/diffHistory.md
  packages/backend/discovery/astarzkevm/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/xlayer/ethereum/config.jsonc
  packages/backend/discovery/xlayer/ethereum/diffHistory.md
  packages/backend/discovery/xlayer/ethereum/discovered.json
  packages/config/src/projects/layer2s/astarzkevm.ts
  packages/config/src/projects/layer2s/polygonzkevm.ts
  packages/config/src/projects/layer2s/templates/polygonCDKStack.ts
  packages/config/src/projects/layer2s/xlayer.ts
Labels: research

#4500 Add Witness chain
  packages/backend/discovery/witness/ethereum/config.jsonc
  packages/backend/discovery/witness/ethereum/diffHistory.md
  packages/backend/discovery/witness/ethereum/discovered.json
  packages/config/src/projects/layer2s/witness.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/witness.png
Labels: research

#4514 Taiko upgrade 1.9.0
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/backend/scripts/updateDiffHistory.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#4519 (MERGE IN THE MORNING) Add more socket tokens to lyra
  packages/config/src/projects/layer2s/lyra.ts
Labels: research

#4527 Trivial discovery updates 07/18
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/cbridge/ethereum/diffHistory.md
  packages/backend/discovery/cbridge/ethereum/discovered.json
  packages/backend/discovery/lyra/ethereum/diffHistory.md
  packages/backend/discovery/lyra/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/config/scripts/socket/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socket/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4167 Add Xterio Chain as opStackL2 with discovery
  packages/backend/discovery/xterio/ethereum/config.jsonc
  packages/backend/discovery/xterio/ethereum/diffHistory.md
  packages/backend/discovery/xterio/ethereum/discovered.json
  packages/backend/discovery/xterio/ethereum/meta.json
  packages/config/src/common/ScalingProjectDataAvailability.ts
  packages/config/src/common/dataAvailability.ts
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/xterio.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/xterio.png
  packages/frontend2/public/images/architecture/xterio.png
Labels: research

#4534 Add ezETH to Fraxtal, Optimism (via Hyperlane)
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4537 Add lisk (full)
  packages/backend/discovery/lisk/ethereum/config.jsonc
  packages/backend/discovery/lisk/ethereum/diffHistory.md
  packages/backend/discovery/lisk/ethereum/discovered.json
  packages/config/src/projects/layer2s/lisk.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
Labels: research

#4535 arbitrum.ts with orbit template
  packages/backend/discovery/arbitrum/arbitrum/diffHistory.md
  packages/backend/discovery/arbitrum/arbitrum/discovered.json
  packages/backend/discovery/arbitrum/ethereum/config.jsonc
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer2s/templates/utils.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research, code

#4549 add Lisk finality, fix some links in derivation
  packages/config/src/common/stateDerivations.ts
  packages/config/src/projects/layer2s/lisk.ts
Labels: trivial, research

#4546 Trivial discovery updates 07/19
  packages/backend/discovery/linea/ethereum/config.jsonc
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/bsc/diffHistory.md
  packages/backend/discovery/lzomnichain/bsc/discovered.json
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/stargatev2/ethereum/config.jsonc
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
  packages/backend/discovery/zklinknova/mantle/diffHistory.md
  packages/backend/discovery/zklinknova/mantle/discovered.json
  packages/config/scripts/socket/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socket/outfiles/socket-crawl-result.json
  packages/config/src/projects/layer2s/linea.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4559 Add L3x appchain (full)
  packages/backend/discovery/l3x/arbitrum/config.jsonc
  packages/backend/discovery/l3x/arbitrum/diffHistory.md
  packages/backend/discovery/l3x/arbitrum/discovered.json
  packages/config/src/projects/layer3s/index.test.ts
  packages/config/src/projects/layer3s/l3x.ts
  packages/config/src/verification/arbitrum/verified.json
Labels: research

#4569 Add tokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4571 Add TAP token to arbitrum
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4574 Trivial discovery updates 07/22
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/orbit/ethereum/diffHistory.md
  packages/backend/discovery/orbit/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/backend/discovery/worldcoin/ethereum/diffHistory.md
  packages/backend/discovery/worldcoin/ethereum/discovered.json
  packages/backend/discovery/worldcoin/optimism/config.jsonc
  packages/backend/discovery/worldcoin/optimism/diffHistory.md
  packages/backend/discovery/worldcoin/optimism/discovered.json
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
Labels: research

#4581 Update FAQ
  packages/frontend2/src/app/(legacy)/faq/faq-items.tsx
Labels: trivial

#4562 Add Playblock (full)
  packages/backend/discovery/playblock/nova/config.jsonc
  packages/backend/discovery/playblock/nova/diffHistory.md
  packages/backend/discovery/playblock/nova/discovered.json
  packages/config/src/projects/badges/index.ts
  packages/config/src/projects/layer2s/nova.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer3s/playblock.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/nova/verified.json
  packages/config/src/verification/projects.json
  packages/discovery/src/config/chains.ts
  packages/frontend2/public/images/badges/Nova.png
Labels: research

#4584 (Re-)Add mxc as upcoming
  packages/config/src/projects/layer3s/index.ts
  packages/config/src/projects/layer3s/mxc.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/mxc.png
Labels: research

#4583 Trivial discovery updates 07/23
  packages/backend/discovery/commonAddressNames.jsonc
  packages/backend/discovery/kinto/ethereum/config.jsonc
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/lisk/ethereum/diffHistory.md
  packages/backend/discovery/lisk/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/config/scripts/socket/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socket/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4587 Lisk: admin EOA removed
  packages/backend/discovery/lisk/ethereum/diffHistory.md
  packages/backend/discovery/lisk/ethereum/discovered.json
  packages/config/src/projects/layer2s/lisk.ts
Labels: trivial-discovery

#4597 new tokens (mostly scroll)
  packages/backend/discovery/scroll/ethereum/config.jsonc
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/config/src/projects/layer2s/scroll.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#4619 Add ARB (and its escrow) to Nova
  packages/backend/discovery/nova/ethereum/config.jsonc
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/config/src/projects/layer2s/nova.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
Labels: research

#4629 Add allbridge research, risks
  packages/backend/discovery/_templates/allbridge/pool/template.jsonc
  packages/backend/discovery/allbridge/ethereum/config.jsonc
  packages/backend/discovery/allbridge/ethereum/diffHistory.md
  packages/backend/discovery/allbridge/ethereum/discovered.json
  packages/config/src/projects/bridges/allbridge.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#4632 Add trackedTxs for kinto blobs
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/config/src/projects/layer2s/kinto.ts
Labels: research

#4615 Add Arbitrum L2 contracts
  packages/backend/discovery/arbitrum/arbitrum/config.jsonc
  packages/backend/discovery/arbitrum/arbitrum/diffHistory.md
  packages/backend/discovery/arbitrum/arbitrum/discovered.json
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/templates/opStack.ts
Labels: research

#4643 Trivial discovery updates 07/26
  packages/backend/discovery/_templates/acrossv3/adapter/template.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/orderly/ethereum/diffHistory.md
  packages/backend/discovery/orderly/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/backend/discovery/zklinknova/arbitrum/diffHistory.md
  packages/backend/discovery/zklinknova/arbitrum/discovered.json
  packages/backend/discovery/zklinknova/base/diffHistory.md
  packages/backend/discovery/zklinknova/base/discovered.json
  packages/backend/discovery/zklinknova/ethereum/diffHistory.md
  packages/backend/discovery/zklinknova/ethereum/discovered.json
  packages/backend/discovery/zklinknova/mantapacific/diffHistory.md
  packages/backend/discovery/zklinknova/mantapacific/discovered.json
  packages/backend/discovery/zklinknova/mantle/diffHistory.md
  packages/backend/discovery/zklinknova/mantle/discovered.json
  packages/backend/discovery/zklinknova/scroll/config.jsonc
  packages/backend/discovery/zklinknova/scroll/diffHistory.md
  packages/backend/discovery/zklinknova/scroll/discovered.json
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/projects/bridges/acrossV3.ts
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/projects/layer2s/linea.ts
  packages/config/src/projects/layer3s/zklinknova.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4649 Add Lisk TVL warning
  packages/config/src/projects/layer2s/lisk.ts
Labels: trivial

#4652 Scroll: compressed tx data since Curie upgrade
  packages/config/src/projects/layer2s/scroll.ts
Labels: trivial

#4658 Remove hypr token
  packages/config/src/projects/layer2s/hypr.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4664 Add Patex Network in review + TVL
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/patex.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/patex.png
Labels: research

#4662 Add swanchain full
  packages/backend/discovery/swan/ethereum/config.jsonc
  packages/backend/discovery/swan/ethereum/diffHistory.md
  packages/backend/discovery/swan/ethereum/discovered.json
  packages/config/scripts/checkRpc.ts
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/swan.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/swan.png
Labels: research

#4653 Add upgrades and governance section for Arbitrum and Nova
  packages/backend/discovery/arbitrum/arbitrum/config.jsonc
  packages/backend/discovery/arbitrum/arbitrum/diffHistory.md
  packages/backend/discovery/arbitrum/arbitrum/discovered.json
  packages/backend/discovery/arbitrum/ethereum/config.jsonc
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/nova/ethereum/config.jsonc
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/nova.ts
  packages/frontend2/public/images/upgrades-and-governance/arbitrum.png
  packages/frontend2/public/images/upgrades-and-governance/nova.png
Labels: research

#4667 Trivial discovery updates 07/30
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/pNetwork/ethereum/config.jsonc
  packages/backend/discovery/pNetwork/ethereum/diffHistory.md
  packages/backend/discovery/pNetwork/ethereum/discovered.json
  packages/backend/discovery/paradex/ethereum/diffHistory.md
  packages/backend/discovery/paradex/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/config.jsonc
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4670 Fix validator afk calculation for orbit stack chains
  packages/config/src/common/forceTransactions.ts
  packages/config/src/common/riskView.ts
  packages/config/src/discovery/values/index.ts
  packages/config/src/discovery/values/projects/arbitrum/ARBITRUM.ts
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/nova.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer3s/degen.ts
Labels: research

#4679 Add cvxFXS token (convex pooled FXS gov token)
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4681 Add Optopia (full)
  packages/backend/discovery/optopia/ethereum/config.jsonc
  packages/backend/discovery/optopia/ethereum/diffHistory.md
  packages/backend/discovery/optopia/ethereum/discovered.json
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/optopia.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/optopia.png
Labels: research

#4682 Add wOETH to arbitrum (via transporter)
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research
