Repository l2beat/l2beat, pull requests merged in 2024-03, with the labels that each got.

#2920 Fix mobile links
  packages/frontend/src/components/project/StageSection.tsx
  packages/frontend/src/scripts/configureDropdowns.ts
Labels: code

#2944 Update Orderly
  packages/backend/discovery/orderly/ethereum/diffHistory.md
  packages/backend/discovery/orderly/ethereum/discovered.json
  packages/backend/discovery/orderly/ethereum/meta.json
Labels: trivial-discovery

#2904 Update Linea
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/linea/ethereum/meta.json
  packages/config/src/layer2s/linea.ts
Labels: discovery

#2950 Handle overflow in daily reminder Discord message
  packages/backend/src/modules/update-monitor/UpdateNotifier.test.ts
  packages/backend/src/modules/update-monitor/UpdateNotifier.ts
Labels: code

#2954 Add warning to zkSync Era time to inclusion
  packages/config/src/layer2s/zksyncera.ts
Labels: trivial, research

#2951 Update Loopring
  packages/backend/discovery/loopring/ethereum/diffHistory.md
  packages/backend/discovery/loopring/ethereum/discovered.json
  packages/backend/discovery/loopring/ethereum/meta.json
Labels: trivial-discovery

#2952 Update Chainport
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/chainport/ethereum/meta.json
Labels: trivial-discovery

#2953 Update pNetwork
  packages/backend/discovery/pNetwork/ethereum/config.jsonc
  packages/backend/discovery/pNetwork/ethereum/diffHistory.md
  packages/backend/discovery/pNetwork/ethereum/discovered.json
  packages/backend/discovery/pNetwork/ethereum/meta.json
Labels: trivial-discovery

#2946 Add Term Structure as upcoming L2
  packages/config/src/layer2s/index.ts
  packages/config/src/layer2s/termstructure.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/termstructure.png
Labels: external

#2891 Review Scroll upgrade
  packages/backend/discovery/scroll/ethereum/config.jsonc
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/backend/discovery/scroll/ethereum/meta.json
  packages/config/src/layer2s/scroll.ts
  packages/config/src/verification/ethereum/verified.json
Labels: discovery

#2909 Add DeGate activity
  packages/backend/src/modules/activity/ActivityTransactionConfig.ts
  packages/backend/src/modules/activity/counters/DegateCounter.ts
  packages/backend/src/modules/activity/createSequenceProcessors.ts
  packages/backend/src/peripherals/degate/DegateClient.test.ts
  packages/backend/src/peripherals/degate/DegateClient.ts
  packages/backend/src/peripherals/degate/index.ts
  packages/backend/src/peripherals/degate/schemas.ts
  packages/config/src/layer2s/degate3.ts
  packages/config/src/layer2s/types/Layer2TransactionApi.ts
Labels: code, external

#2958 Update Discovery version
  packages/backend/package.json
  packages/config/package.json
  yarn.lock
Labels: trivial

#2936 Create tracked txs config table & repo
  packages/backend/src/model/Project.ts
  packages/backend/src/modules/liveness/LivenessIndexer.test.ts
  packages/backend/src/modules/tracked-txs/TrackedTxsClient.test.ts
  packages/backend/src/modules/tracked-txs/TrackedTxsClient.ts
  packages/backend/src/modules/tracked-txs/repositories/TrackedTxsConfigsRepository.test.ts
  packages/backend/src/modules/tracked-txs/repositories/TrackedTxsConfigsRepository.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxsConfig.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxsId.test.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxsId.ts
  packages/backend/src/peripherals/database/migrations/095_add_tracked_txs_configs_table.ts
  packages/backend/src/peripherals/database/types.ts
  packages/config/src/layer2s/types/Layer2TrackedTxsConfig.ts
  packages/shared-pure/src/types/TrackedTxsConfigSubtype.ts
  packages/shared-pure/src/types/TrackedTxsConfigType.ts
  packages/shared-pure/src/types/index.ts
Labels: code

#2948 Add Fraxtal full config
  packages/backend/discovery/fraxtal/ethereum/config.jsonc
  packages/backend/discovery/fraxtal/ethereum/diffHistory.md
  packages/backend/discovery/fraxtal/ethereum/discovered.json
  packages/backend/discovery/fraxtal/ethereum/meta.json
  packages/config/src/layer2s/fraxtal.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/fraxtal.png
Labels: research

#2967 Update Discovery docs
  packages/backend/discovery/README.md
Labels: trivial

#2969 Fix Polygon zkEVM derivation genesis link
  packages/config/src/layer2s/polygonzkevm.ts
Labels: trivial

#2966 Add the ability to configure a TVL warning
  packages/config/src/layer2s/polygonzkevm.ts
  packages/config/src/layer2s/types/Layer2.ts
  packages/frontend/src/components/header/DetailsHeader.tsx
  packages/frontend/src/components/header/TvlSummary.tsx
  packages/frontend/src/components/table/TotalCell.tsx
  packages/frontend/src/components/table/TotalValue.tsx
  packages/frontend/src/components/table/props/getScalingTableColumnsConfig.tsx
  packages/frontend/src/pages/scaling/projects/props/getProjectHeader.ts
  packages/frontend/src/pages/scaling/projects/view/ProjectHeader.tsx
  packages/frontend/src/pages/scaling/summary/props/getScalingSummaryView.ts
  packages/frontend/src/pages/scaling/summary/types.ts
  packages/frontend/src/pages/scaling/tvl/props/getScalingTvlView.ts
  packages/frontend/src/pages/scaling/tvl/types.ts
  packages/frontend/src/utils/sentimentFillColor.ts
Labels: website, code

#2965 Update liveness table & livenessRepo
  packages/backend/src/model/Project.ts
  packages/backend/src/modules/finality/api/FinalityController.test.ts
  packages/backend/src/modules/finality/api/calcAvgsPerProject.ts
  packages/backend/src/modules/liveness/api/LivenessController.test.ts
  packages/backend/src/modules/liveness/api/LivenessController.ts
  packages/backend/src/modules/liveness/api/calculateIntervalWithAverages.ts
  packages/backend/src/modules/liveness/api/groupByType.test.ts
  packages/backend/src/modules/liveness/api/groupByType.ts
  packages/backend/src/modules/liveness/repositories/LivenessRepository.test.ts
  packages/backend/src/modules/liveness/repositories/LivenessRepository.ts
  packages/backend/src/modules/tracked-txs/repositories/TrackedTxsConfigsRepository.test.ts
  packages/backend/src/modules/tracked-txs/repositories/TrackedTxsConfigsRepository.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxId.test.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxId.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxsConfig.ts
  packages/backend/src/modules/tracked-txs/types/TrackedTxsId.ts
  packages/backend/src/peripherals/database/migrations/095_add_tracked_txs_configs_table.ts
  packages/backend/src/peripherals/database/types.ts
Labels: code

#2976 Update Chainport
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/chainport/ethereum/meta.json
Labels: trivial-discovery

#2977 Update Socket
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/meta.json
  packages/config/src/bridges/socket-vaults.json
Labels: trivial-discovery

#2962 Added and updates some explorer links
  packages/config/src/layer2s/blast.ts
  packages/config/src/layer2s/mode.ts
  packages/config/src/layer2s/optimism.ts
  packages/config/src/layer2s/taiko.ts
Labels: trivial, external

#2979 Fetch the DA layer automatically in OP Stack template
  packages/config/src/layer2s/templates/opStack.ts
Labels: trivial, code

#2980 Make isNodeAvailable not required for Optimiums
  packages/config/src/layer2s/templates/opStack.ts
Labels: trivial, code

#2898 Add "coming soon" state to Finality
  packages/backend/src/config/features/finality.ts
  packages/backend/src/model/Project.ts
  packages/config/src/layer2s/arbitrum.ts
  packages/config/src/layer2s/bobanetwork.ts
  packages/config/src/layer2s/degate3.ts
  packages/config/src/layer2s/dydx.ts
  packages/config/src/layer2s/loopring.ts
  packages/config/src/layer2s/paradex.ts
  packages/config/src/layer2s/parallel.ts
  packages/config/src/layer2s/polygonzkevm.ts
  packages/config/src/layer2s/scroll.ts
  packages/config/src/layer2s/starknet.ts
  packages/config/src/layer2s/templates/orbitStack.ts
  packages/config/src/layer2s/types/Layer2.ts
  packages/config/src/layer2s/zkspace.ts
  packages/config/src/layer2s/zksynclite.ts
  packages/frontend/src/build/api/fetchFinalityApi.ts
  packages/frontend/src/components/header/FinalityHeader.tsx
  packages/frontend/src/components/table/FinalityDurationCell.tsx
  packages/frontend/src/components/table/ProjectNameCell.tsx
  packages/frontend/src/components/table/props/getScalingTableColumnsConfig.tsx
  packages/frontend/src/pages/scaling/activity/types.ts
  packages/frontend/src/pages/scaling/finality/props/getScalingFinalityView.ts
  packages/frontend/src/pages/scaling/finality/types.ts
  packages/frontend/src/pages/scaling/finality/view/ScalingFinalityView.stories.tsx
  packages/frontend/src/pages/types.ts
Labels: website, code

#2997 Update Discovery to fix starkware proxies in update monitor
  packages/backend/package.json
  packages/config/package.json
  yarn.lock
Labels: trivial

#2959 SHARP upgrade
  packages/backend/discovery/brine/ethereum/config.jsonc
  packages/backend/discovery/brine/ethereum/diffHistory.md
  packages/backend/discovery/brine/ethereum/discovered.json
  packages/backend/discovery/brine/ethereum/meta.json
  packages/backend/discovery/l2beat-starkware/ethereum/diffHistory.md
  packages/backend/discovery/l2beat-starkware/ethereum/discovered.json
  packages/backend/discovery/l2beat-starkware/ethereum/meta.json
  packages/backend/discovery/layer2financezk/ethereum/config.jsonc
  packages/backend/discovery/layer2financezk/ethereum/diffHistory.md
  packages/backend/discovery/layer2financezk/ethereum/discovered.json
  packages/backend/discovery/layer2financezk/ethereum/meta.json
  packages/config/src/discovery/starkware/getSHARPVerifier.ts
  packages/config/src/layer2s/apex.ts
  packages/config/src/layer2s/canvasconnect.ts
  packages/config/src/layer2s/immutablex.ts
  packages/config/src/layer2s/myria.ts
  packages/config/src/layer2s/reddioex.ts
  packages/config/src/layer2s/rhinofi.ts
  packages/config/src/layer2s/sorare.ts
  packages/config/src/layer2s/starknet.ts
  packages/config/src/layer2s/tanx.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#2986 Add ezETH and add ezETH to mode network
  packages/config/src/layer2s/mode.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research, external

#3015 Allow to override technology and add Blast exit warning
  packages/config/src/common/ScalingProjectRisk.ts
  packages/config/src/common/exits.ts
  packages/config/src/layer2s/blast.ts
  packages/config/src/layer2s/templates/opStack.ts
Labels: trivial

#3023 Update L2BEAT-starkware
  packages/backend/discovery/l2beat-starkware/ethereum/diffHistory.md
  packages/backend/discovery/l2beat-starkware/ethereum/discovered.json
  packages/backend/discovery/l2beat-starkware/ethereum/meta.json
Labels: trivial-discovery

#3044 Convert Astar to Validium
  packages/config/src/layer2s/astarzkevm.ts
Labels: trivial

#3050 Starknet upgrade to support blobs
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/meta.json
  packages/config/src/layer2s/starknet.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research, discovery

#3052 Paradex upgrade to support blobs
  packages/backend/discovery/paradex/ethereum/diffHistory.md
  packages/backend/discovery/paradex/ethereum/discovered.json
  packages/backend/discovery/paradex/ethereum/meta.json
  packages/config/src/layer2s/paradex.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research, discovery

#3053 Update LZ & Stargate discovery
  packages/backend/discovery/lzomnichain/arbitrum/diffHistory.md
  packages/backend/discovery/lzomnichain/arbitrum/discovered.json
  packages/backend/discovery/lzomnichain/arbitrum/meta.json
  packages/backend/discovery/lzomnichain/base/diffHistory.md
  packages/backend/discovery/lzomnichain/base/discovered.json
  packages/backend/discovery/lzomnichain/base/meta.json
  packages/backend/discovery/lzomnichain/bsc/diffHistory.md
  packages/backend/discovery/lzomnichain/bsc/discovered.json
  packages/backend/discovery/lzomnichain/bsc/meta.json
  packages/backend/discovery/lzomnichain/ethereum/diffHistory.md
  packages/backend/discovery/lzomnichain/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/ethereum/meta.json
  packages/backend/discovery/lzomnichain/linea/diffHistory.md
  packages/backend/discovery/lzomnichain/linea/discovered.json
  packages/backend/discovery/lzomnichain/linea/meta.json
  packages/backend/discovery/lzomnichain/optimism/diffHistory.md
  packages/backend/discovery/lzomnichain/optimism/discovered.json
  packages/backend/discovery/lzomnichain/optimism/meta.json
  packages/backend/discovery/lzomnichain/polygonpos/diffHistory.md
  packages/backend/discovery/lzomnichain/polygonpos/discovered.json
  packages/backend/discovery/lzomnichain/polygonpos/meta.json
  packages/backend/discovery/stargate/ethereum/diffHistory.md
  packages/backend/discovery/stargate/ethereum/discovered.json
  packages/backend/discovery/stargate/ethereum/meta.json
Labels: trivial-discovery

#3055 Paradex is now using blobs
  packages/config/src/layer2s/paradex.ts
Labels: trivial

#3063 Return unsynced OP Stack finality data
  packages/backend/src/modules/finality/FinalityModule.ts
  packages/backend/src/modules/finality/api/FinalityController.test.ts
  packages/backend/src/modules/finality/api/FinalityController.ts
  packages/backend/src/modules/liveness/repositories/LivenessConfigurationRepository.ts
Labels: code

#3062 Immutable zkEVM disc update: Withdrawal queue activated
  packages/backend/discovery/immutablezkevm/ethereum/diffHistory.md
  packages/backend/discovery/immutablezkevm/ethereum/discovered.json
  packages/backend/discovery/immutablezkevm/ethereum/meta.json
Labels: trivial-discovery

#3061 Discovery: Ignore L2 fee scalar in watch mode for all op stack L2s that use it
  packages/backend/discovery/base/ethereum/config.jsonc
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/meta.json
  packages/backend/discovery/blast/ethereum/config.jsonc
  packages/backend/discovery/blast/ethereum/diffHistory.md
  packages/backend/discovery/blast/ethereum/discovered.json
  packages/backend/discovery/blast/ethereum/meta.json
  packages/backend/discovery/fraxtal/ethereum/config.jsonc
  packages/backend/discovery/fraxtal/ethereum/diffHistory.md
  packages/backend/discovery/fraxtal/ethereum/discovered.json
  packages/backend/discovery/fraxtal/ethereum/meta.json
  packages/backend/discovery/kroma/ethereum/config.jsonc
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/backend/discovery/kroma/ethereum/meta.json
  packages/backend/discovery/mantapacific/ethereum/config.jsonc
  packages/backend/discovery/mantapacific/ethereum/diffHistory.md
  packages/backend/discovery/mantapacific/ethereum/discovered.json
  packages/backend/discovery/mantapacific/ethereum/meta.json
  packages/backend/discovery/mode/ethereum/config.jsonc
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/meta.json
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/meta.json
  packages/backend/discovery/zora/ethereum/config.jsonc
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/meta.json
Labels: trivial-discovery

#3069 Chainport disc update: New proposal
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/chainport/ethereum/meta.json
Labels: trivial-discovery

#3076 Blast disc updates: ignore values related to ordinary withdrawal queue and yield checkpoints.
  packages/backend/discovery/blast/ethereum/config.jsonc
  packages/backend/discovery/blast/ethereum/diffHistory.md
  packages/backend/discovery/blast/ethereum/discovered.json
  packages/backend/discovery/blast/ethereum/meta.json
Labels: trivial-discovery

#3074 Add ezETH to Connext Amarok TVL
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/backend/discovery/amarok/ethereum/meta.json
  packages/config/src/bridges/amarok.ts
Labels: trivial-discovery

#3077 Immutable zkEVM disc update: Withdrawal queue disabled, severity changed to LOW
  packages/backend/discovery/immutablezkevm/ethereum/diffHistory.md
  packages/backend/discovery/immutablezkevm/ethereum/discovered.json
  packages/backend/discovery/immutablezkevm/ethereum/meta.json
Labels: trivial-discovery

#3067 Add governance section for zkSync Era
  packages/backend/discovery/zksync2/ethereum/config.jsonc
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/backend/discovery/zksync2/ethereum/meta.json
  packages/config/src/layer2s/zksyncera.ts
  packages/frontend/src/static/images/excalidraw-sources/zkSyncEra-UpgradesGov.excalidraw
  packages/frontend/src/static/images/upgrades-and-governance/zksync-era.png
Labels: research

#3078 Starknet disc update: programHash changed
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/meta.json
Labels: trivial-discovery

#3084 Rename zkLink
  packages/config/src/layer3s/index.ts
  packages/config/src/layer3s/zklinknexus.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/zklinknexus.png
  packages/frontend/src/static/icons/zklinknova.png
Labels: trivial

#3097 Chainport disc update: Unpause unverified contracts
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
Labels: trivial-discovery

#3090 Add Proof of Play Apex L3 as inReview
  packages/config/src/layer3s/index.ts
  packages/config/src/layer3s/popapex.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/popapex.png
Labels: trivial, research

#3094 Paradex update: programHash changed
  packages/backend/discovery/paradex/ethereum/diffHistory.md
  packages/backend/discovery/paradex/ethereum/discovered.json
  packages/backend/discovery/paradex/ethereum/meta.json
  packages/config/src/layer2s/paradex.ts
Labels: trivial-discovery

#3099 Severity of program hash change is now HIGH for starknet
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/meta.json
  packages/config/src/layer2s/starknet.ts
Labels: trivial

#3100 Blast disc update: Disable insurance fee on the YieldManager contracts
  packages/backend/discovery/blast/ethereum/diffHistory.md
  packages/backend/discovery/blast/ethereum/discovered.json
  packages/backend/discovery/blast/ethereum/meta.json
Labels: trivial-discovery

#3102 Update outdated tokens info
  packages/config/src/tokens/tokens.ts
Labels: trivial

#3089 Add HYCHAIN to inReview
  packages/config/src/layer2s/hychain.ts
  packages/config/src/layer2s/index.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/hychain.png
Labels: trivial

#3106 Immutable zkEVM disc update: ignore withdrawal queue in watch mode, add withdrawalDelay to .ts file
  packages/backend/discovery/immutablezkevm/ethereum/config.jsonc
  packages/backend/discovery/immutablezkevm/ethereum/diffHistory.md
  packages/backend/discovery/immutablezkevm/ethereum/discovered.json
  packages/config/src/bridges/immutablezkevm.ts
Labels: trivial-discovery

#3104 Refactor to otherConsiderations as an array
  packages/config/scripts/getTechnologyReport.ts
  packages/config/src/common/ScalingProjectTechnology.ts
  packages/config/src/layer2s/arbitrum.ts
  packages/config/src/layer2s/aztecV1.ts
  packages/config/src/layer2s/aztecconnect.ts
  packages/config/src/layer2s/bobanetwork.ts
  packages/config/src/layer2s/index.test.ts
  packages/config/src/layer2s/kroma.ts
  packages/config/src/layer2s/mantle.ts
  packages/config/src/layer2s/metis.ts
  packages/config/src/layer2s/nova.ts
  packages/config/src/layer2s/templates/opStack.ts
  packages/config/src/layer2s/templates/orbitStack.ts
  packages/config/src/test/stubs/layer2aWithDups.ts
  packages/frontend/src/pages/layer3s/props/getTechnologyOverview.ts
  packages/frontend/src/pages/scaling/projects/props/getTechnologyOverview.ts
Labels: trivial, code

#3087 Add MXC to inReview
  packages/config/src/common/ScalingProjectProvider.ts
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/layer3s/index.ts
  packages/config/src/layer3s/mxc.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/mxc.png
Labels: trivial

#3092 Add stack to L3s in review
  packages/config/src/common/ScalingProjectProvider.ts
  packages/config/src/layer3s/index.ts
  packages/config/src/layer3s/stack.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/cli/tinifyLogos.ts
  packages/frontend/src/static/icons/stack.png
Labels: trivial, research

#3096 Synapse bridge update: New GOVERNANCE_ROLE EOA
  packages/backend/discovery/synapse/ethereum/diffHistory.md
  packages/backend/discovery/synapse/ethereum/discovered.json
  packages/backend/discovery/synapse/ethereum/meta.json
  packages/config/src/bridges/synapse.ts
Labels: trivial-discovery

#3082 Add Ankr and Davos bridge to inReview
  packages/config/src/bridges/ankr.ts
  packages/config/src/bridges/davos.ts
  packages/config/src/bridges/index.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/ankr.png
  packages/frontend/src/static/icons/davos.png
Labels: trivial

#3121 Associate ANKR token with the bridge
  packages/config/src/bridges/ankr.ts
Labels: trivial, research

#3122 Add addSequencerL2BatchFromBlobs to arbitrum config
  packages/config/src/layer2s/arbitrum.ts
Labels: research

#3123 Orbit disc and .ts updates
  packages/backend/discovery/orbit/ethereum/diffHistory.md
  packages/backend/discovery/orbit/ethereum/discovered.json
  packages/backend/discovery/orbit/ethereum/meta.json
  packages/config/src/bridges/orbit.ts
Labels: trivial-discovery, research

#3085 Add Mantle v2 Tectonic update
  packages/backend/discovery/mantle/ethereum/config.jsonc
  packages/backend/discovery/mantle/ethereum/diffHistory.md
  packages/backend/discovery/mantle/ethereum/discovered.json
  packages/backend/discovery/mantle/ethereum/meta.json
  packages/config/src/layer2s/mantle.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/src/static/images/architecture/mantle.png
Labels: research

#2903 Move stuff from technology to state validation
  packages/config/src/common/ScalingProjectStateValidation.ts
  packages/config/src/common/ScalingProjectTechnology.ts
  packages/config/src/layer2s/zksyncera.ts
  packages/frontend/src/components/project/StateValidationSection.tsx
  packages/frontend/src/pages/layer3s/props/getTechnologyOverview.ts
  packages/frontend/src/pages/scaling/projects/props/getTechnologyOverview.ts
Labels: website, research, code

#3132 Fraxtal disc update: Ignore numValidators in watch mode
  packages/backend/discovery/fraxtal/ethereum/config.jsonc
  packages/backend/discovery/fraxtal/ethereum/diffHistory.md
  packages/backend/discovery/fraxtal/ethereum/discovered.json
Labels: trivial-discovery

#3117 Adding Bugless DApp into L3 section
  packages/config/src/common/ScalingProjectProvider.ts
  packages/config/src/layer3s/bugless.ts
  packages/config/src/layer3s/index.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/bugless.png
Labels: research, external

#3146 Warn about storage handler shortcomings in mappings
  packages/backend/discovery/README.md
Labels: trivial

#3126 Refactor the compareOpStackChains script
  packages/backend/scripts/compareOpStackChains.ts
Labels: trivial, code

#3143 Expand the similarity scripts to compare entire technology stacks
  packages/backend/scripts/compareFlatSources.ts
Labels: code

#3140 Rhino.fi disc update: 6 new signers added to gov Multisig
  packages/backend/discovery/deversifi/ethereum/diffHistory.md
  packages/backend/discovery/deversifi/ethereum/discovered.json
  packages/backend/discovery/deversifi/ethereum/meta.json
  packages/config/src/layer2s/rhinofi.ts
Labels: trivial-discovery

#3037 esXAI implementation updates
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/backend/discovery/xai/arbitrum/meta.json
  packages/config/src/layer3s/xai.ts
  packages/config/src/verification/arbitrum/verified.json
Labels: research

#3156 Socket disc update: switchboard fees raised
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/meta.json
Labels: trivial-discovery

#3158 Rhinofi disc update: Make gov multisig more grown-up
  packages/backend/discovery/deversifi/ethereum/diffHistory.md
  packages/backend/discovery/deversifi/ethereum/discovered.json
Labels: trivial-discovery

#3079 add optimism milestones
  packages/config/src/layer2s/optimism.ts
Labels: trivial

#3159 Socket disc updates: bridging fees
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
Labels: trivial-discovery

#3160 Lyra disc update: ignore scalar in watch mode
  packages/backend/discovery/lyra/ethereum/config.jsonc
  packages/backend/discovery/lyra/ethereum/diffHistory.md
  packages/backend/discovery/lyra/ethereum/discovered.json
  packages/backend/discovery/lyra/ethereum/meta.json
Labels: trivial-discovery

#3007 Add L2 costs updater
  packages/backend/package.json
  packages/backend/src/config/Config.ts
  packages/backend/src/config/makeConfig.ts
  packages/backend/src/modules/tracked-txs/TrackedTxsClient.test.ts
  packages/backend/src/modules/tracked-txs/TrackedTxsIndexer.test.ts
  packages/backend/src/modules/tracked-txs/TrackedTxsIndexer.ts
  packages/backend/src/modules/tracked-txs/TrackedTxsModule.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/L2CostsModule.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/L2CostsUpdater.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/L2CostsUpdater.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/repositories/L2CostsRepository.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/repositories/L2CostsRepository.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/types/TransactionData.ts
  packages/backend/src/modules/tracked-txs/modules/liveness/LivenessUpdater.test.ts
  packages/backend/src/modules/tracked-txs/modules/liveness/LivenessUpdater.ts
  packages/backend/src/modules/tracked-txs/modules/liveness/repositories/LivenessRepository.test.ts
  packages/backend/src/modules/tracked-txs/modules/liveness/repositories/LivenessRepository.ts
  packages/backend/src/modules/tracked-txs/types/TxUpdaterInterface.ts
  packages/backend/src/modules/tracked-txs/types/model.ts
  packages/backend/src/modules/tracked-txs/utils/sql/getFunctionCallQuery.test.ts
  packages/backend/src/modules/tracked-txs/utils/sql/getFunctionCallQuery.ts
  packages/backend/src/modules/tracked-txs/utils/sql/getTransferQuery.test.ts
  packages/backend/src/modules/tracked-txs/utils/sql/getTransferQuery.ts
  packages/backend/src/modules/tracked-txs/utils/transformFunctionCallsQueryResult.test.ts
  packages/backend/src/modules/tracked-txs/utils/transformFunctionCallsQueryResult.ts
  packages/backend/src/modules/tracked-txs/utils/transformTransfersQueryResult.test.ts
  packages/backend/src/modules/tracked-txs/utils/transformTransfersQueryResult.ts
  packages/backend/src/peripherals/database/migrations/098_add_l2_costs_table.ts
  packages/backend/src/peripherals/database/types.ts
  packages/backend/src/peripherals/viem-rpc-client/RateLimitedViemProvider.ts
  packages/backend/src/peripherals/viem-rpc-client/ViemRpcClient.ts
  packages/config/src/layer2s/arbitrum.ts
  packages/config/src/layer2s/bobanetwork.ts
  packages/config/src/layer2s/degate3.ts
  packages/config/src/layer2s/dydx.ts
  packages/config/src/layer2s/kroma.ts
  packages/config/src/layer2s/linea.ts
  packages/config/src/layer2s/loopring.ts
  packages/config/src/layer2s/polygonzkevm.ts
  packages/config/src/layer2s/scroll.ts
  packages/config/src/layer2s/templates/opStack.ts
  packages/config/src/layer2s/zksyncera.ts
  packages/config/src/layer2s/zksynclite.ts
  packages/shared-pure/src/types/TrackedTxsConfigType.ts
  yarn.lock
Labels: code

#3161 Xai disc updates: ignore 'challenges'(state submissions) in watch mode
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/backend/discovery/xai/arbitrum/meta.json
Labels: trivial-discovery

#3163 Add the zk-newcrypto risk to the zkRollups that were missing it
  packages/config/src/layer2s/linea.ts
  packages/config/src/layer2s/polygonzkevm.ts
  packages/config/src/layer2s/scroll.ts
  packages/config/src/layer2s/zksyncera.ts
Labels: trivial

#3139 Arbitrum implementation updates - ArbOS v20
  packages/backend/discovery/arbitrum/ethereum/config.jsonc
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/arbitrum/ethereum/meta.json
  packages/backend/discovery/nova/ethereum/config.jsonc
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/backend/discovery/nova/ethereum/meta.json
  packages/config/src/layer2s/arbitrum.ts
  packages/config/src/layer2s/nova.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#3147 Add ezETH lockbox and disc updates to Amarok
  packages/backend/discovery/amarok/ethereum/config.jsonc
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/backend/discovery/amarok/ethereum/meta.json
  packages/config/src/bridges/amarok.ts
Labels: trivial-discovery

#3175 Socket disc updates: ignore bridging fees in watch mode
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
Labels: trivial-discovery

#3176 Update Polygon zkEVM discovery: chain halt
  packages/backend/discovery/astarzkevm/ethereum/diffHistory.md
  packages/backend/discovery/astarzkevm/ethereum/discovered.json
  packages/backend/discovery/polygonzkevm/ethereum/config.jsonc
  packages/backend/discovery/polygonzkevm/ethereum/diffHistory.md
  packages/backend/discovery/polygonzkevm/ethereum/discovered.json
  packages/backend/discovery/polygonzkevm/ethereum/meta.json
  packages/config/src/layer2s/astarzkevm.ts
  packages/config/src/layer2s/polygonzkevm.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research, discovery

#3179 Aztec disc update: Gas reimbursement tip set to 0
  packages/backend/discovery/aztec/ethereum/diffHistory.md
  packages/backend/discovery/aztec/ethereum/discovered.json
  packages/backend/discovery/aztec/ethereum/meta.json
Labels: trivial-discovery

#3185 Rhinofi disc update: implementation upgrade delay reduced
  packages/backend/discovery/deversifi/ethereum/diffHistory.md
  packages/backend/discovery/deversifi/ethereum/discovered.json
Labels: trivial-discovery

#3081 Add l2costs controller
  packages/backend/src/modules/tracked-txs/modules/l2-costs/L2CostsModule.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsRouter.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/repositories/L2CostsRepository.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/repositories/L2CostsRepository.ts
  packages/backend/src/modules/tracked-txs/modules/liveness/api/LivenessController.test.ts
  packages/backend/src/modules/tracked-txs/modules/liveness/api/LivenessController.ts
  packages/backend/src/modules/tracked-txs/modules/utils/getSyncedUntil.test.ts
  packages/backend/src/modules/tracked-txs/modules/utils/getSyncedUntil.ts
  packages/backend/src/modules/tracked-txs/repositories/TrackedTxsConfigsRepository.test.ts
  packages/backend/src/modules/tracked-txs/repositories/TrackedTxsConfigsRepository.ts
  packages/backend/src/modules/tvl/repositories/PriceRepository.test.ts
  packages/backend/src/modules/tvl/repositories/PriceRepository.ts
  packages/shared-pure/src/types/api/L2CostsApi.ts
  packages/shared-pure/src/types/api/index.ts
Labels: code

#3190 Connext disc updates: new router
  packages/backend/discovery/amarok/ethereum/config.jsonc
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/backend/discovery/amarok/ethereum/meta.json
  packages/config/src/bridges/amarok.ts
Labels: trivial-discovery

#3192 Linea is using blobs
  packages/config/src/layer2s/linea.ts
Labels: trivial

#3196 Add Syndicate Frame L3 in review
  packages/config/src/layer3s/index.ts
  packages/config/src/layer3s/syndicateframe.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/syndicateframe.png
Labels: trivial

#3199 Update zkSync Era tracked txs configs
  packages/config/src/layer2s/zksyncera.ts
Labels: trivial, research

#3197 Blast disc update: Censoring three addresses in the bridge
  packages/backend/discovery/blast/ethereum/diffHistory.md
  packages/backend/discovery/blast/ethereum/discovered.json
  packages/config/src/layer2s/blast.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#3198 Add zklighter as upcoming project
  packages/config/src/layer2s/index.ts
  packages/config/src/layer2s/zklighter.ts
  packages/config/src/verification/projects.json
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/zklighter.png
Labels: trivial, research

#3174 Add Upgrades and Gov section to Polygon zkEvm
  packages/backend/discovery/polygonzkevm/ethereum/diffHistory.md
  packages/backend/discovery/polygonzkevm/ethereum/discovered.json
  packages/config/src/layer2s/polygonzkevm.ts
  packages/frontend/src/static/images/excalidraw-sources/polygonzkevm-upgradesAndGovernance.excalidraw
  packages/frontend/src/static/images/excalidraw-sources/polygonzkevm.excalidraw
  packages/frontend/src/static/images/upgrades-and-governance/polygonzkevm.png
Labels: research

#3209 Base disc update: raise gas limit
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
Labels: trivial-discovery

#3204 Implement AmountRepository
  packages/backend/src/modules/tvl2/repositories/AmountRepository.test.ts
  packages/backend/src/modules/tvl2/repositories/AmountRepository.ts
  packages/backend/src/modules/tvl2/repositories/BlockTimestampRepository.ts
  packages/backend/src/modules/tvl2/repositories/PriceRepository.ts
  packages/backend/src/peripherals/database/migrations/100_amounts.ts
  packages/backend/src/peripherals/database/types.ts
Labels: code

#3210 Add description for the gasLimit in op stack meta.json's.
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/meta.json
  packages/backend/discovery/blast/ethereum/meta.json
  packages/backend/discovery/kroma/ethereum/meta.json
  packages/backend/discovery/mode/ethereum/meta.json
  packages/backend/discovery/optimism/ethereum/meta.json
  packages/backend/discovery/zora/ethereum/meta.json
Labels: trivial-discovery

#3213 Update L2costs controller timeranges
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.test.ts
  packages/backend/src/modules/tracked-txs/modules/l2-costs/api/L2CostsController.ts
Labels: code

#3189 feat: add RSS3 Value Sublayer Mainnet
  packages/backend/discovery/rss3/ethereum/config.jsonc
  packages/backend/discovery/rss3/ethereum/diffHistory.md
  packages/backend/discovery/rss3/ethereum/discovered.json
  packages/backend/discovery/rss3/ethereum/meta.json
  packages/config/README.md
  packages/config/src/layer2s/rss3.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research, discovery

#3195 Linea disc update: blobs Implementation upgrade
  packages/backend/discovery/linea/ethereum/config.jsonc
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/linea/ethereum/meta.json
  packages/config/src/layer2s/linea.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research, discovery

#3227 Fix outdated info banner margin
  packages/frontend/src/components/project/ContractsUpdated.tsx
Labels: code

#3219 Add warning next to TVL for associated tokens >80%
  packages/frontend/src/components/table/TotalCell.tsx
  packages/frontend/src/pages/scaling/summary/props/getScalingSummaryView.ts
  packages/frontend/src/pages/scaling/summary/types.ts
  packages/frontend/src/utils/tvl/getTVLBreakdown.tsx
  packages/frontend/src/utils/tvl/getTVLWarnings.ts
Labels: code
