Repository l2beat/l2beat, pull requests merged in 2024-02, with the labels that each got.

#2738 Update Lisk logo
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/lisk.png
Labels: trivial

#2733 Reduce DB size
  packages/backend/src/api/controllers/BlocksController.test.ts
  packages/backend/src/api/controllers/BlocksController.ts
  packages/backend/src/config/Config.ts
  packages/backend/src/config/makeConfig.ts
  packages/backend/src/core/BlockNumberUpdater.test.ts
  packages/backend/src/core/BlockNumberUpdater.ts
  packages/backend/src/core/Clock.test.ts
  packages/backend/src/core/Clock.ts
  packages/backend/src/core/activity/DailyTransactionCountViewRefresher.ts
  packages/backend/src/core/assets/CBVUpdater.test.ts
  packages/backend/src/core/assets/CBVUpdater.ts
  packages/backend/src/core/assets/CirculatingSupplyFormulaUpdater.test.ts
  packages/backend/src/core/assets/CirculatingSupplyFormulaUpdater.ts
  packages/backend/src/core/assets/TotalSupplyFormulaUpdater.test.ts
  packages/backend/src/core/assets/TotalSupplyFormulaUpdater.ts
  packages/backend/src/core/balances/BalanceUpdater.test.ts
  packages/backend/src/core/balances/BalanceUpdater.ts
  packages/backend/src/core/reports/AggregatedReportUpdater.test.ts
  packages/backend/src/core/reports/AggregatedReportUpdater.ts
  packages/backend/src/core/totalSupply/TotalSupplyUpdater.test.ts
  packages/backend/src/core/totalSupply/TotalSupplyUpdater.ts
  packages/backend/src/modules/tvl/TvlCleaner.test.ts
  packages/backend/src/modules/tvl/TvlCleaner.ts
  packages/backend/src/modules/tvl/TvlModule.ts
  packages/backend/src/modules/tvl/types.ts
  packages/backend/src/peripherals/database/AggregatedReportRepository.test.ts
  packages/backend/src/peripherals/database/AggregatedReportRepository.ts
  packages/backend/src/peripherals/database/BalanceRepository.test.ts
  packages/backend/src/peripherals/database/BalanceRepository.ts
  packages/backend/src/peripherals/database/BlockNumberRepository.test.ts
  packages/backend/src/peripherals/database/BlockNumberRepository.ts
  packages/backend/src/peripherals/database/CirculatingSupplyRepository.test.ts
  packages/backend/src/peripherals/database/CirculatingSupplyRepository.ts
  packages/backend/src/peripherals/database/PriceRepository.test.ts
  packages/backend/src/peripherals/database/PriceRepository.ts
  packages/backend/src/peripherals/database/ReportRepository.test.ts
  packages/backend/src/peripherals/database/ReportRepository.ts
  packages/backend/src/peripherals/database/TotalSupplyRepository.test.ts
  packages/backend/src/peripherals/database/TotalSupplyRepository.ts
  packages/backend/src/peripherals/database/shared/deleteArchivedRecords.test.ts
  packages/backend/src/peripherals/database/shared/deleteArchivedRecords.ts
  packages/shared-pure/src/types/UnixTime.ts
Labels: code

#2740 Update Arbitrum
  packages/backend/discovery/arbitrum/ethereum/config.jsonc
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
Labels: trivial-discovery

#2747 Update Aevo logo
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/aevo.png
Labels: trivial

#2720 Add RARI (full) and improve DAC chains
  packages/backend/discovery/arbitrum/ethereum/config.jsonc
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/deri/arbitrum/config.jsonc
  packages/backend/discovery/deri/arbitrum/diffHistory.md
  packages/backend/discovery/deri/arbitrum/discovered.json
  packages/backend/discovery/nova/ethereum/config.jsonc
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/backend/discovery/parallel/ethereum/config.jsonc
  packages/backend/discovery/parallel/ethereum/diffHistory.md
  packages/backend/discovery/parallel/ethereum/discovered.json
  packages/backend/discovery/rari/arbitrum/config.jsonc
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/backend/package.json
  packages/config/package.json
  packages/config/src/common/dataAvailability.ts
  packages/config/src/common/riskView.ts
  packages/config/src/layer2s/apex.ts
  packages/config/src/layer2s/arbitrum.ts
  packages/config/src/layer2s/canvasconnect.ts
  packages/config/src/layer2s/immutablex.ts
  packages/config/src/layer2s/layer2financezk.ts
  packages/config/src/layer2s/myria.ts
  packages/config/src/layer2s/nova.ts
  packages/config/src/layer2s/parallel.ts
  packages/config/src/layer2s/reddioex.ts
  packages/config/src/layer2s/rhinofi.ts
  packages/config/src/layer2s/sorare.ts
  packages/config/src/layer2s/tanx.ts
  packages/config/src/layer2s/templates/orbitStack.ts
  packages/config/src/layer2s/zkfair.ts
  packages/config/src/layer3s/rari.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/projects.json
  yarn.lock
Labels: research

#2756 fix: update outdated links
  packages/config/src/bridges/hyphen.ts
  packages/config/src/layer2s/myria.ts
  packages/config/src/layer2s/rhinofi.ts
  packages/config/src/layer2s/sorare.ts
Labels: trivial

#2758 Fix token selector
  packages/frontend/src/components/RichSelect.tsx
  packages/frontend/src/components/chart/TokenControls.tsx
Labels: code

#2762 Fix socket tests
  packages/config/scripts/socket/index.test.ts
  packages/config/src/bridges/socket-vaults.json
Labels: trivial, code

#2761 Fix dydx discovery configuration
  packages/backend/discovery/dydx/ethereum/config.jsonc
  packages/backend/discovery/dydx/ethereum/diffHistory.md
  packages/backend/discovery/dydx/ethereum/discovered.json
  packages/backend/src/modules/diff-history/createDiffHistoryModule.ts
Labels: trivial, code, discovery

#2748 Add endpoint to expose liveness data
  packages/backend/src/api/controllers/liveness/LivenessController.ts
  packages/backend/src/api/controllers/liveness/groupByType.ts
  packages/backend/src/api/routers/FinalityRouter.ts
  packages/backend/src/api/routers/LivenessRouter.ts
  packages/backend/src/peripherals/database/LivenessRepository.ts
Labels: code

#2767 Update Aptos
  packages/backend/discovery/aptos/ethereum/diffHistory.md
  packages/backend/discovery/aptos/ethereum/discovered.json
Labels: trivial-discovery

#2769 Update Discovery Version
  packages/backend/package.json
  packages/config/package.json
  yarn.lock
Labels: trivial, code

#2771 Add Mode activity source
  packages/config/src/layer2s/mode.ts
Labels: trivial

#2772 Update Loopring links
  packages/config/src/layer2s/loopring.ts
Labels: trivial

#2775 Update MetaImageHeader styling
  packages/frontend/src/pages/meta-images/MetaImage.stories.tsx
  packages/frontend/src/pages/meta-images/MetaImageHeader.tsx
Labels: trivial, code

#2777 Update Optimistic chains discovery
  packages/backend/discovery/aevo/ethereum/diffHistory.md
  packages/backend/discovery/aevo/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/hypr/ethereum/diffHistory.md
  packages/backend/discovery/hypr/ethereum/discovered.json
  packages/backend/discovery/lyra/ethereum/diffHistory.md
  packages/backend/discovery/lyra/ethereum/discovered.json
  packages/backend/discovery/mantapacific/ethereum/diffHistory.md
  packages/backend/discovery/mantapacific/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/publicgoodsnetwork/ethereum/diffHistory.md
  packages/backend/discovery/publicgoodsnetwork/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
Labels: trivial-discovery

#2684 Add LineaFinalityAnalyzer
  packages/backend/src/core/finality/LineaFinalityAnalyzer.test.ts
  packages/backend/src/core/finality/LineaFinalityAnalyzer.ts
  packages/backend/src/peripherals/database/LivenessRepository.test.ts
  packages/backend/src/peripherals/database/LivenessRepository.ts
Labels: code

#2725 Add missing EBV Aevo tokens
  packages/config/src/layer2s/aevo.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#2766 Add Orderly (full)
  packages/backend/discovery/orderly/ethereum/config.jsonc
  packages/backend/discovery/orderly/ethereum/diffHistory.md
  packages/backend/discovery/orderly/ethereum/discovered.json
  packages/config/src/layer2s/index.ts
  packages/config/src/layer2s/orderly.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/orderly.png
Labels: research

#2783 Add OEV (upcoming)
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/layer2s/index.ts
  packages/config/src/layer2s/oev.ts
  packages/frontend/cli/tinifiedLogos.json
  packages/frontend/src/static/icons/oev.png
Labels: trivial

#2784 Update AcrossV2
  packages/backend/discovery/across-v2/ethereum/config.jsonc
  packages/backend/discovery/across-v2/ethereum/diffHistory.md
  packages/backend/discovery/across-v2/ethereum/discovered.json
Labels: trivial-discovery

#2781 Updated Amarok
  packages/backend/discovery/amarok/ethereum/config.jsonc
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/config/src/bridges/amarok.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#2765 Add Immutable zkEVM bridge
  packages/backend/discovery/immutablezkevm/ethereum/config.jsonc
  packages/backend/discovery/immutablezkevm/ethereum/diffHistory.md
  packages/backend/discovery/immutablezkevm/ethereum/discovered.json
  packages/backend/discovery/zkfair/ethereum/diffHistory.md
  packages/backend/discovery/zkfair/ethereum/discovered.json
  packages/config/src/bridges/immutablezkevm.ts
  packages/config/src/bridges/index.ts
  packages/config/src/layer2s/immutablezkevm.ts
  packages/config/src/layer2s/index.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#2779 Update font size and styling in StateDerivationSection component
  packages/frontend/src/components/project/StateDerivationSection.tsx
Labels: trivial, code

#2778 Remove knowledge nuggets background on mobile
  packages/frontend/src/components/project/KnowledgeNuggetsSection.tsx
Labels: trivial, code

#2792 Update OP Stack derivation reference
  packages/config/src/layer2s/templates/opStack.ts
Labels: trivial

#2793 Fix DAC risk wording
  packages/config/src/common/dataAvailability.ts
Labels: trivial, research

#2791 Update Manta Pacific to use OP Stack template
  packages/config/src/layer2s/mantapacific.ts
Labels: trivial

#2780 Run tokens script for all tokens
  packages/config/scripts/tokens/tokens.test.ts
  packages/config/scripts/tokens/tokens.ts
  packages/config/scripts/tokens/utils/fsIntegration.ts
  packages/config/scripts/tokens/utils/getTokenInfo.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tokens/tokens.ts
  packages/config/src/tokens/types.ts
  packages/shared-pure/src/types/Token.ts
Labels: code

#2787 Discover sequencerInbox for all opStack chains
  packages/backend/discovery/aevo/ethereum/config.jsonc
  packages/backend/discovery/aevo/ethereum/diffHistory.md
  packages/backend/discovery/aevo/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/config.jsonc
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/hypr/ethereum/config.jsonc
  packages/backend/discovery/hypr/ethereum/diffHistory.md
  packages/backend/discovery/hypr/ethereum/discovered.json
  packages/backend/discovery/kroma/ethereum/config.jsonc
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/backend/discovery/lyra/ethereum/config.jsonc
  packages/backend/discovery/lyra/ethereum/diffHistory.md
  packages/backend/discovery/lyra/ethereum/discovered.json
  packages/backend/discovery/mantapacific/ethereum/config.jsonc
  packages/backend/discovery/mantapacific/ethereum/diffHistory.md
  packages/backend/discovery/mantapacific/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/config.jsonc
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/orderly/ethereum/config.jsonc
  packages/backend/discovery/orderly/ethereum/diffHistory.md
  packages/backend/discovery/orderly/ethereum/discovered.json
  packages/backend/discovery/publicgoodsnetwork/ethereum/config.jsonc
  packages/backend/discovery/publicgoodsnetwork/ethereum/diffHistory.md
  packages/backend/discovery/publicgoodsnetwork/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/config.jsonc
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/backend/package.json
  packages/config/package.json
  packages/config/src/layer2s/aevo.ts
  packages/config/src/layer2s/base.ts
  packages/config/src/layer2s/hypr.ts
  packages/config/src/layer2s/kroma.ts
  packages/config/src/layer2s/lyra.ts
  packages/config/src/layer2s/mantapacific.ts
  packages/config/src/layer2s/mode.ts
  packages/config/src/layer2s/optimism.ts
  packages/config/src/layer2s/orderly.ts
  packages/config/src/layer2s/publicgoodsnetwork.ts
  packages/config/src/layer2s/templates/opStack.ts
  packages/config/src/layer2s/zora.ts
  yarn.lock
Labels: code

#2794 Update ZkSync Era
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/layer2s/zksyncera.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: discovery

#2798 Update Starknet
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
Labels: trivial-discovery

#2795 Add Base native tokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#2755 Add XAI (full)
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/config/src/discovery/OrbitStackTypes.ts
  packages/config/src/layer2s/templates/orbitStack.ts
  packages/config/src/layer3s/xai.ts
  packages/config/src/verification/arbitrum/verified.json
Labels: research

#2811 Add Hypr token
  packages/config/src/layer2s/hypr.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#2782 Add finality indexer
  packages/backend/README.md
  packages/backend/src/Application.ts
  packages/backend/src/config/Config.ts
  packages/backend/src/config/makeConfig.ts
  packages/backend/src/modules/ApplicationModule.ts
  packages/backend/src/modules/finality/FinalityIndexer.test.ts
  packages/backend/src/modules/finality/FinalityIndexer.ts
  packages/backend/src/modules/finality/FinalityModule.ts
  packages/backend/src/modules/finality/analyzers/LineaFinalityAnalyzer.test.ts
  packages/backend/src/modules/finality/analyzers/LineaFinalityAnalyzer.ts
  packages/backend/src/modules/finality/analyzers/types/BaseAnalyzer.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.test.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.ts
  packages/backend/src/modules/finality/types/FinalityConfig.ts
  packages/backend/src/modules/finality/utils/findConfigurationsToSync.ts
  packages/backend/src/modules/liveness/LivenessIndexer.ts
  packages/backend/src/modules/liveness/LivenessModule.ts
  packages/backend/src/modules/liveness/repositories/LivenessRepository.test.ts
  packages/backend/src/modules/liveness/repositories/LivenessRepository.ts
  packages/backend/src/peripherals/database/migrations/093_add_finality_table.ts
  packages/backend/src/peripherals/database/types.ts
  packages/config/src/layer2s/linea.ts
  packages/config/src/layer2s/types/Layer2FinalityConfig.ts
Labels: code

#2808 Add OP Mainnet Security Council
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/config/src/layer2s/optimism.ts
  packages/config/src/layer2s/templates/opStack.ts
  packages/frontend/src/static/images/upgrades-and-governance/optimism.png
Labels: research

#2820 Modify finality endpoint
  packages/backend/src/modules/finality/FinalityModule.ts
  packages/backend/src/modules/finality/api/FinalityController.test.ts
  packages/backend/src/modules/finality/api/FinalityController.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.test.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.ts
  packages/frontend/src/build/api/fetchFinalityApi.ts
  packages/frontend/src/components/table/FinalityDurationCell.tsx
  packages/frontend/src/components/table/props/getScalingTableColumnsConfig.tsx
  packages/frontend/src/pages/scaling/finality/props/getScalingFinalityView.ts
  packages/frontend/src/pages/scaling/finality/types.ts
  packages/frontend/src/pages/scaling/finality/view/ScalingFinalityView.stories.tsx
  packages/shared-pure/src/types/api/FinalityApi.ts
  packages/shared-pure/src/utils/formatSeconds.ts
Labels: code

#2830 Update Orbit
  packages/backend/discovery/orbit/ethereum/diffHistory.md
  packages/backend/discovery/orbit/ethereum/discovered.json
Labels: trivial-discovery

#2823 Refactor LineaFinalityAnalyzer
  packages/backend/src/modules/finality/FinalityIndexer.test.ts
  packages/backend/src/modules/finality/FinalityIndexer.ts
  packages/backend/src/modules/finality/FinalityModule.ts
  packages/backend/src/modules/finality/analyzers/LineaFinalityAnalyzer.test.ts
  packages/backend/src/modules/finality/analyzers/LineaFinalityAnalyzer.ts
  packages/backend/src/modules/finality/analyzers/types/BaseAnalyzer.ts
Labels: code

#2835 Update TVL status pages
  packages/backend/src/modules/tvl/PriceUpdater.ts
  packages/backend/src/modules/tvl/api/status/TvlStatusPageDetailed.tsx
  packages/backend/src/modules/tvl/reports/getStatus.ts
  packages/backend/src/tools/Clock.ts
  packages/shared-pure/src/types/UnixTime.test.ts
  packages/shared-pure/src/types/UnixTime.ts
  packages/shared-pure/src/utils/getHourlyTimestamps.ts
  packages/shared/src/services/coingecko/CoingeckoQueryService.ts
Labels: code

#2833 Update Stargate
  packages/backend/discovery/stargate/ethereum/config.jsonc
  packages/backend/discovery/stargate/ethereum/diffHistory.md
  packages/backend/discovery/stargate/ethereum/discovered.json
Labels: trivial-discovery

#2838 Add mETH token and Stargate pool
  packages/config/src/bridges/stargate.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
Labels: trivial

#2750 Refactor stack template discovery to support backlinks
  packages/backend/package.json
  packages/config/package.json
  packages/config/src/discovery/PermissionedContract.ts
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/discovery/StackTemplateTypes.ts
  packages/config/src/discovery/values/templateUtils.ts
  yarn.lock
Labels: code

#2812 Improve TVL cleaner performance
  packages/backend/src/modules/tvl/modules/TvlCleaner.test.ts
  packages/backend/src/modules/tvl/modules/TvlCleaner.ts
  packages/backend/src/modules/tvl/modules/TvlModule.ts
  packages/backend/src/modules/tvl/modules/types.ts
  packages/backend/src/modules/tvl/repositories/AggregatedReportRepository.ts
  packages/backend/src/modules/tvl/repositories/BalanceRepository.ts
  packages/backend/src/modules/tvl/repositories/BlockNumberRepository.ts
  packages/backend/src/modules/tvl/repositories/ReportRepository.ts
  packages/backend/src/modules/tvl/repositories/TotalSupplyRepository.ts
  packages/backend/src/modules/tvl/repositories/deleteArchivedRecords.test.ts
  packages/backend/src/modules/tvl/repositories/deleteArchivedRecords.ts
  packages/backend/src/peripherals/database/BaseRepository.ts
  packages/backend/src/peripherals/database/TvlCleanerRepository.test.ts
  packages/backend/src/peripherals/database/TvlCleanerRepository.ts
  packages/backend/src/peripherals/database/migrations/094_add_tvl_cleaner.ts
  packages/backend/src/peripherals/database/types.ts
Labels: code

#2841 Add warning to Linea
  packages/config/src/layer2s/linea.ts
Labels: trivial

#2845 Update Xai
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
Labels: trivial-discovery

#2840 Add "coming soon" state to liveness projects
  packages/backend/src/modules/liveness/api/LivenessController.ts
  packages/backend/src/modules/liveness/api/calculateAnomalies.test.ts
  packages/backend/src/modules/liveness/api/calculateAnomalies.ts
  packages/frontend/src/build/api/fetchLivenessApi.ts
  packages/frontend/src/components/table/ComingSoonCell.tsx
  packages/frontend/src/components/table/LivenessDurationCell.tsx
  packages/frontend/src/components/table/TableView.tsx
  packages/frontend/src/components/table/props/getScalingTableColumnsConfig.tsx
  packages/frontend/src/pages/scaling/liveness/props/getScalingLivenessView.tsx
  packages/frontend/src/pages/scaling/liveness/types.ts
  packages/frontend/src/pages/scaling/liveness/view/ScalingLivenessView.stories.tsx
  packages/shared-pure/src/types/api/LivenessApi.ts
Labels: code

#2848 Update Blast
  packages/backend/discovery/README.md
  packages/backend/discovery/blast/ethereum/config.jsonc
  packages/backend/discovery/blast/ethereum/diffHistory.md
  packages/backend/discovery/blast/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#2859 Update cBridge
  packages/backend/discovery/cbridge/ethereum/diffHistory.md
  packages/backend/discovery/cbridge/ethereum/discovered.json
Labels: trivial-discovery

#2807 Starknet escrows upgrade
  packages/backend/discovery/starknet/ethereum/config.jsonc
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/config/src/layer2s/starknet.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#2860 Update Polygon zkEVM
  packages/backend/discovery/polygonzkevm/ethereum/config.jsonc
  packages/backend/discovery/polygonzkevm/ethereum/diffHistory.md
  packages/backend/discovery/polygonzkevm/ethereum/discovered.json
Labels: trivial-discovery

#2862 Update Connext (Amarok) discovery
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
Labels: trivial-discovery

#2821 Fix oxlint warnings
  packages/backend/src/modules/status/StatusPagesLinksPage.tsx
  packages/backend/src/modules/tvl/reports/aggregateReports.ts
  packages/backend/src/modules/update-monitor/api/view/DashboardPage.tsx
Labels: code

#2872 Update pNetwork
  packages/backend/discovery/pNetwork/ethereum/diffHistory.md
  packages/backend/discovery/pNetwork/ethereum/discovered.json
Labels: trivial-discovery

#2870 zkSync Era bridge upgrade
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#2861 Update Connext chains & tokens
  packages/config/src/bridges/amarok.ts
Labels: trivial

#2871 Refactor FinalityIndexer
  packages/backend/README.md
  packages/backend/src/config/Config.ts
  packages/backend/src/config/features/finality.ts
  packages/backend/src/config/makeConfig.ts
  packages/backend/src/modules/finality/FinalityIndexer.test.ts
  packages/backend/src/modules/finality/FinalityIndexer.ts
  packages/backend/src/modules/finality/FinalityModule.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.test.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.ts
  packages/backend/src/modules/finality/types/FinalityConfig.ts
  packages/backend/src/modules/liveness/LivenessIndexer.test.ts
  packages/backend/src/modules/liveness/api/status/LivenessConfigurationCard.tsx
  packages/backend/src/modules/liveness/utils/getSafeHeight.test.ts
  packages/backend/src/modules/liveness/utils/getSafeHeight.ts
  packages/config/src/layer2s/linea.ts
  packages/config/src/layer2s/types/Layer2FinalityConfig.ts
Labels: code

#2882 Add LQTY token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#2876 Add rollups discovery on Polygon RollupManager
  packages/backend/discovery/polygonzkevm/ethereum/config.jsonc
  packages/backend/discovery/polygonzkevm/ethereum/diffHistory.md
  packages/backend/discovery/polygonzkevm/ethereum/discovered.json
Labels: trivial-discovery

#2878 Show not synced on Finality tab
  packages/backend/src/modules/finality/api/FinalityController.test.ts
  packages/backend/src/modules/finality/api/FinalityController.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.test.ts
  packages/backend/src/modules/finality/repositories/FinalityRepository.ts
  packages/frontend/src/build/api/fetchFinalityApi.ts
  packages/frontend/src/components/badge/Badge.tsx
  packages/frontend/src/components/badge/NoDataBadge.tsx
  packages/frontend/src/components/badge/NotSyncedBadge.tsx
  packages/frontend/src/components/badge/UpcomingBadge.tsx
  packages/frontend/src/components/table/FinalityDurationCell.tsx
  packages/frontend/src/components/table/ProjectNameCell.tsx
  packages/frontend/src/components/table/props/getProjectWithIndexColumns.tsx
  packages/frontend/src/components/table/props/getScalingTableColumnsConfig.tsx
  packages/frontend/src/pages/scaling/finality/props/getScalingFinalityView.ts
  packages/frontend/src/pages/scaling/finality/types.ts
  packages/frontend/src/pages/scaling/finality/view/ScalingFinalityView.stories.tsx
  packages/frontend/tailwind.config.js
  packages/shared-pure/src/types/api/FinalityApi.ts
Labels: website, code

#2839 Add discovery to near rainbow bridge
  packages/backend/discovery/near/ethereum/config.jsonc
  packages/backend/discovery/near/ethereum/diffHistory.md
  packages/backend/discovery/near/ethereum/discovered.json
  packages/config/src/bridges/near.ts
  packages/frontend/src/static/images/architecture/near.png
Labels: research

#2901 Update Kroma
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/backend/discovery/kroma/ethereum/meta.json
Labels: trivial-discovery

#2900 Update Connext (Amarok)
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/backend/discovery/amarok/ethereum/meta.json
Labels: trivial-discovery

#2890 Add Aevo activity
  packages/config/src/layer2s/aevo.ts
Labels: trivial

#2915 Fix typos
  CONTRIBUTING.md
  packages/frontend/src/content/publications/governance-review-2.md
  packages/frontend/src/content/publications/governance-review-3.md
Labels: trivial

#2911 Show meta information in discovery dashboard
  packages/backend/src/modules/update-monitor/UpdateMonitor.ts
  packages/backend/src/modules/update-monitor/api/UpdateMonitorController.ts
  packages/backend/src/modules/update-monitor/api/view/DashboardProjectPage.tsx
  packages/backend/src/modules/update-monitor/api/view/components/Diff.tsx
  packages/backend/src/modules/update-monitor/utils/diffToMessages.ts
  packages/backend/src/modules/update-monitor/utils/metaGetters.ts
  packages/backend/src/modules/update-monitor/utils/normalizeDiffPath.test.ts
  packages/backend/src/modules/update-monitor/utils/normalizeDiffPath.ts
  packages/backend/src/modules/update-monitor/utils/removeArraySuffix.test.ts
  packages/backend/src/modules/update-monitor/utils/sortDiffs.test.ts
  packages/backend/src/modules/update-monitor/utils/sortDiffs.ts
Labels: code

#2905 Update Linea finality logic
  packages/backend/src/config/features/finality.ts
  packages/backend/src/config/makeConfig.ts
  packages/backend/src/modules/finality/FinalityModule.ts
  packages/backend/src/modules/finality/analyzers/LineaFinalityAnalyzer.test.ts
  packages/backend/src/modules/finality/analyzers/LineaFinalityAnalyzer.ts
  packages/backend/src/modules/finality/analyzers/types/BaseAnalyzer.ts
  packages/config/src/layer2s/linea.ts
Labels: code

#2893 Add Ancient8 (full)
  packages/backend/discovery/ancient/ethereum/config.jsonc
  packages/backend/discovery/ancient/ethereum/diffHistory.md
  packages/backend/discovery/ancient/ethereum/discovered.json
  packages/backend/discovery/ancient/ethereum/meta.json
  packages/config/src/layer2s/ancient.ts
  packages/config/src/verification/ethereum/verified.json
Labels: discovery
