Repository l2beat/l2beat, pull requests merged in 2024-10, with the labels that each got.

#5283 Trivial discovery updates 10/01
  packages/backend/discovery/_templates/succinct/SP1SuccinctGateway/template.jsonc
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/blobstream/arbitrum/diffHistory.md
  packages/backend/discovery/blobstream/arbitrum/discovered.json
  packages/backend/discovery/blobstream/base/diffHistory.md
  packages/backend/discovery/blobstream/base/discovered.json
  packages/backend/discovery/blobstream/ethereum/diffHistory.md
  packages/backend/discovery/blobstream/ethereum/discovered.json
  packages/backend/discovery/omni/ethereum/config.jsonc
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/polygonzkevm/ethereum/config.jsonc
  packages/backend/discovery/polygonzkevm/ethereum/diffHistory.md
  packages/backend/discovery/polygonzkevm/ethereum/discovered.json
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/config.jsonc
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/vector/ethereum/diffHistory.md
  packages/backend/discovery/vector/ethereum/discovered.json
  packages/config/src/projects/layer2s/base.ts
  packages/config/src/projects/layer2s/hemi.ts
  packages/config/src/projects/layer2s/polygonzkevm.ts
  packages/config/src/projects/layer2s/starknet.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#5297 Trivial discovery updates 10/02
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/blobstream/arbitrum/diffHistory.md
  packages/backend/discovery/blobstream/arbitrum/discovered.json
  packages/backend/discovery/blobstream/base/diffHistory.md
  packages/backend/discovery/blobstream/base/discovered.json
  packages/backend/discovery/blobstream/ethereum/diffHistory.md
  packages/backend/discovery/blobstream/ethereum/discovered.json
  packages/backend/discovery/cronoszkevm/ethereum/diffHistory.md
  packages/backend/discovery/cronoszkevm/ethereum/discovered.json
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/opticsV2/ethereum/config.jsonc
  packages/backend/discovery/opticsV2/ethereum/diffHistory.md
  packages/backend/discovery/opticsV2/ethereum/discovered.json
  packages/backend/discovery/polygonzkevm/ethereum/diffHistory.md
  packages/backend/discovery/polygonzkevm/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/vector/ethereum/diffHistory.md
  packages/backend/discovery/vector/ethereum/discovered.json
Labels: trivial-discovery

#5317 Trivial discovery updates 10/04
  packages/backend/discovery/base/ethereum/config.jsonc
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/scroll/ethereum/config.jsonc
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/config/src/projects/layer2s/scroll.ts
Labels: trivial-discovery

#5333 Trivial discovery updates 10/07
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/backend/discovery/nova/nova/config.jsonc
  packages/backend/discovery/nova/nova/diffHistory.md
  packages/backend/discovery/nova/nova/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/projects/layer2s/real.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5337 Archive redsonic
  packages/config/src/projects/layer2s/reddioex.ts
Labels: trivial

#5335 Test templatization: PGN (`discoveryDrivenData: true`)
  packages/backend/discovery/_templates/opstack/OptimismPortal/shape/OptimismPortal_v1_6_0.sol
  packages/backend/discovery/publicgoodsnetwork/ethereum/config.jsonc
  packages/backend/discovery/publicgoodsnetwork/ethereum/diffHistory.md
  packages/backend/discovery/publicgoodsnetwork/ethereum/discovered.json
  packages/config/src/projects/layer2s/publicgoodsnetwork.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial

#5347 Refresh contribution guidelines (->tokens)
  CONTRIBUTING.md
Labels: research

#5353 Trivial discovery updates 10/08
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/worldcoin/ethereum/config.jsonc
  packages/backend/discovery/worldcoin/ethereum/diffHistory.md
  packages/backend/discovery/worldcoin/ethereum/discovered.json
Labels: trivial-discovery

#5372 Fix SHARP trackedTxs (Starknet, Paradex)
  packages/config/src/projects/layer2s/paradex.ts
  packages/config/src/projects/layer2s/starknet.ts
Labels: research

#5375 Add EGP, ATH to Arbi TVL
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5370 Fix TVL warn for polygonCDK and ZK stack
  packages/frontend/src/server/features/scaling/tvl/breakdown/get-tvl-breakdown.ts
Labels: research

#5379 Trivial discovery updates 10/10
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/molten/arbitrum/diffHistory.md
  packages/backend/discovery/molten/arbitrum/discovered.json
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/backend/discovery/sanko/arbitrum/config.jsonc
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/projects/bridges/acrossV3.ts
  packages/config/src/projects/layer3s/sanko.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5391 Trivial discovery updates 10/11
  packages/backend/discovery/base/ethereum/config.jsonc
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/lisk/ethereum/diffHistory.md
  packages/backend/discovery/lisk/ethereum/discovered.json
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
  packages/backend/discovery/reya/ethereum/diffHistory.md
  packages/backend/discovery/reya/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
Labels: trivial-discovery

#5401 Add WINR L3 (full)
  packages/backend/discovery/winr/arbitrum/config.jsonc
  packages/backend/discovery/winr/arbitrum/diffHistory.md
  packages/backend/discovery/winr/arbitrum/discovered.json
  packages/config/src/projects/layer3s/winr.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5398 Add Aleph Zero (full)
  packages/backend/discovery/alephzero/ethereum/config.jsonc
  packages/backend/discovery/alephzero/ethereum/diffHistory.md
  packages/backend/discovery/alephzero/ethereum/discovered.json
  packages/config/src/projects/layer2s/alephzero.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5396 Add Everclear (full)
  packages/backend/discovery/everclear/ethereum/config.jsonc
  packages/backend/discovery/everclear/ethereum/diffHistory.md
  packages/backend/discovery/everclear/ethereum/discovered.json
  packages/config/src/projects/layer2s/everclear.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5373 Add L3 stages
  packages/config/src/projects/layer2s/common/stages/getStage.test.ts
  packages/config/src/projects/layer2s/common/stages/getStage.ts
  packages/config/src/projects/layer2s/ebi.ts
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/templates/opStack.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer2s/templates/underReview.ts
  packages/config/src/projects/layer3s/bugbuster.ts
  packages/config/src/projects/layer3s/types/Layer3.ts
  packages/frontend/src/server/api/routers/asset-risks.ts
  packages/frontend/src/server/features/scaling/get-common-scaling-entry.ts
  packages/frontend/src/server/features/scaling/project/utils/get-l3-project-details.tsx
Labels: research, code

#5404 Trivial discovery updates 10/12
  packages/backend/discovery/_templates/lido/L1LidoTokensBridge/shape/L1LidoTokensBridge.sol
  packages/backend/discovery/_templates/lido/L1LidoTokensBridge/template.jsonc
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#5405 [External] Add 2 tokens to re.al
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5422 Trivial discovery updates 10/14
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/swell/ethereum/diffHistory.md
  packages/backend/discovery/swell/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5421 Add external tokens to Polynomial
  packages/config/scripts/socketconvert/convertedVaults.txt
  packages/config/scripts/socketconvert/input.json
  packages/config/src/projects/layer2s/polynomial.ts
Labels: research

#5428 Add BNRY gas token
  packages/config/src/projects/layer2s/thebinaryholdings.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5442 Add EURC to Base TVL
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5443 Add Linea BTC tokens (via Free.tech bridge)
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5451 Trivial discovery updates 10/16
  packages/backend/discovery/_templates/transporter/TokenPool/shape/LockReleaseTokenPoolAndProxy.sol
  packages/backend/discovery/commonAddressNames.jsonc
  packages/backend/discovery/immutablezkevm/ethereum/diffHistory.md
  packages/backend/discovery/immutablezkevm/ethereum/discovered.json
  packages/backend/discovery/popapex/arbitrum/config.jsonc
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/popboss/arbitrum/config.jsonc
  packages/backend/discovery/popboss/arbitrum/diffHistory.md
  packages/backend/discovery/popboss/arbitrum/discovered.json
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/backend/discovery/winr/arbitrum/config.jsonc
  packages/backend/discovery/winr/arbitrum/diffHistory.md
  packages/backend/discovery/winr/arbitrum/discovered.json
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/layer2s/taiko.ts
  packages/config/src/projects/layer3s/popapex.ts
  packages/config/src/projects/layer3s/popboss.ts
  packages/config/src/projects/layer3s/winr.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5453 Add XCHAIN (full)
  packages/backend/discovery/xchain/ethereum/config.jsonc
  packages/backend/discovery/xchain/ethereum/diffHistory.md
  packages/backend/discovery/xchain/ethereum/discovered.json
  packages/config/src/projects/layer2s/xchain.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5457 Add Fuel (in review)
  packages/backend/discovery/fuel/ethereum/config.jsonc
  packages/backend/discovery/fuel/ethereum/diffHistory.md
  packages/backend/discovery/fuel/ethereum/discovered.json
  packages/config/src/projects/layer2s/fuel.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5454 Add AlienX (full)
  packages/backend/discovery/alienx/ethereum/config.jsonc
  packages/backend/discovery/alienx/ethereum/diffHistory.md
  packages/backend/discovery/alienx/ethereum/discovered.json
  packages/config/src/projects/layer2s/alienx.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#5477 Trivial discovery updates 10/17
  packages/backend/discovery/arbitrum/arbitrum/diffHistory.md
  packages/backend/discovery/arbitrum/arbitrum/discovered.json
  packages/backend/discovery/eclipse/ethereum/diffHistory.md
  packages/backend/discovery/eclipse/ethereum/discovered.json
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/swell/ethereum/diffHistory.md
  packages/backend/discovery/swell/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
Labels: trivial-discovery

#5435 Add worldchain (full)
  packages/backend/discovery/_templates/opstack/OptimismPortal/shape/OptimismPortal_v2_6_0.sol
  packages/backend/discovery/worldchain/ethereum/config.jsonc
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/projects/layer2s/templates/opStack.ts
  packages/config/src/projects/layer2s/world.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#5483 Add moar tokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5487 Change stateCorrectness text for OP stacks
  packages/config/src/projects/layer2s/templates/opStack.ts
Labels: research

#5490 Fix blocknumber format in checkrpc script
  packages/l2b/src/implementations/checkrpc.ts
Labels: code

#5500 Trivial discovery updates 10/19
  packages/backend/discovery/_templates/acrossv3/adapter/template.jsonc
  packages/backend/discovery/_templates/shared-zk-stack/ChainAdmin/shape/ChainAdmin_v1.sol
  packages/backend/discovery/_templates/shared-zk-stack/ChainAdmin/shape/ChainAdmin_v2.sol
  packages/backend/discovery/_templates/shared-zk-stack/ChainAdmin/template.jsonc
  packages/backend/discovery/across-v3/ethereum/config.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/eclipse/ethereum/diffHistory.md
  packages/backend/discovery/eclipse/ethereum/discovered.json
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
  packages/backend/discovery/polygon-pos/ethereum/diffHistory.md
  packages/backend/discovery/polygon-pos/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/output.sol
  packages/config/src/common/riskView.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#5507 Add ApeChain (full)
  packages/backend/discovery/apechain/arbitrum/config.jsonc
  packages/backend/discovery/apechain/arbitrum/diffHistory.md
  packages/backend/discovery/apechain/arbitrum/discovered.json
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer3s/apechain.ts
  packages/config/src/projects/layer3s/winr.ts
  packages/config/src/test/snapshots/apechain.riskView.snapshot
  packages/config/src/verification/arbitrum/verified.json
Labels: research

#5509 Update worldchain links
  packages/config/src/projects/layer2s/world.ts
Labels: trivial

#5510 Add monitoring for ZK stack launches
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
Labels: research

#5531 Remove min timestamp for TVL (rss3)
  packages/config/src/projects/layer2s/rss3.ts
Labels: trivial

#5539 Superchain springclean (add badges, describe contracts)
  packages/backend/discovery/bobanetwork/ethereum/config.jsonc
  packages/backend/discovery/bobanetwork/ethereum/diffHistory.md
  packages/backend/discovery/bobanetwork/ethereum/discovered.json
  packages/backend/discovery/cyber/ethereum/config.jsonc
  packages/backend/discovery/cyber/ethereum/diffHistory.md
  packages/backend/discovery/cyber/ethereum/discovered.json
  packages/backend/discovery/dbk/ethereum/config.jsonc
  packages/backend/discovery/dbk/ethereum/diffHistory.md
  packages/backend/discovery/dbk/ethereum/discovered.json
  packages/backend/discovery/ham/base/config.jsonc
  packages/backend/discovery/ham/base/diffHistory.md
  packages/backend/discovery/ham/base/discovered.json
  packages/backend/discovery/lambda/ethereum/config.jsonc
  packages/backend/discovery/lambda/ethereum/diffHistory.md
  packages/backend/discovery/lambda/ethereum/discovered.json
  packages/backend/discovery/lisk/ethereum/config.jsonc
  packages/backend/discovery/lisk/ethereum/diffHistory.md
  packages/backend/discovery/lisk/ethereum/discovered.json
  packages/backend/discovery/optopia/ethereum/config.jsonc
  packages/backend/discovery/optopia/ethereum/diffHistory.md
  packages/backend/discovery/optopia/ethereum/discovered.json
  packages/backend/discovery/redstone/ethereum/config.jsonc
  packages/backend/discovery/redstone/ethereum/diffHistory.md
  packages/backend/discovery/redstone/ethereum/discovered.json
  packages/backend/discovery/rss3/ethereum/config.jsonc
  packages/backend/discovery/rss3/ethereum/diffHistory.md
  packages/backend/discovery/rss3/ethereum/discovered.json
  packages/backend/discovery/swan/ethereum/config.jsonc
  packages/backend/discovery/swan/ethereum/diffHistory.md
  packages/backend/discovery/swan/ethereum/discovered.json
  packages/backend/discovery/thebinaryholdings/ethereum/config.jsonc
  packages/backend/discovery/thebinaryholdings/ethereum/diffHistory.md
  packages/backend/discovery/thebinaryholdings/ethereum/discovered.json
  packages/backend/discovery/xterio/ethereum/config.jsonc
  packages/backend/discovery/xterio/ethereum/diffHistory.md
  packages/backend/discovery/xterio/ethereum/discovered.json
  packages/config/src/projects/layer2s/bob.ts
  packages/config/src/projects/layer2s/fraxtal.ts
  packages/config/src/projects/layer2s/mint.ts
  packages/config/src/projects/layer2s/polynomial.ts
  packages/config/src/projects/layer2s/race.ts
  packages/config/src/projects/layer2s/redstone.ts
  packages/config/src/projects/layer2s/swan.ts
  packages/config/src/projects/layer2s/world.ts
  packages/config/src/projects/layer3s/donatuz.ts
  packages/config/src/projects/layer3s/ham.ts
Labels: research

#5540 RSS 3 TVL fix?
  packages/config/src/projects/layer2s/rss3.ts
Labels: research

#5542 Add SCR token on Scroll
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5551 Trivial discovery updates 10/23
  packages/backend/discovery/_templates/GnosisSafe/shape/Safe.sol
  packages/backend/discovery/aptos/ethereum/diffHistory.md
  packages/backend/discovery/aptos/ethereum/discovered.json
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/eigenda/ethereum/diffHistory.md
  packages/backend/discovery/eigenda/ethereum/discovered.json
  packages/backend/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/backend/discovery/layerzerov2oft/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/arbitrum/diffHistory.md
  packages/backend/discovery/lzomnichain/arbitrum/discovered.json
  packages/backend/discovery/lzomnichain/base/diffHistory.md
  packages/backend/discovery/lzomnichain/base/discovered.json
  packages/backend/discovery/lzomnichain/linea/diffHistory.md
  packages/backend/discovery/lzomnichain/linea/discovered.json
  packages/backend/discovery/lzomnichain/polygonpos/diffHistory.md
  packages/backend/discovery/lzomnichain/polygonpos/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/rss3/ethereum/config.jsonc
  packages/backend/discovery/rss3/ethereum/diffHistory.md
  packages/backend/discovery/rss3/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/stargate/ethereum/diffHistory.md
  packages/backend/discovery/stargate/ethereum/discovered.json
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
  packages/backend/discovery/taiko/ethereum/config.jsonc
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#5562 YCVC to fix gravity verification status
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial

#5563 Remove critical tags across all bridges
  packages/config/src/projects/bridges/acrossV3.ts
  packages/config/src/projects/bridges/allbridge.ts
  packages/config/src/projects/bridges/amarok.ts
  packages/config/src/projects/bridges/aptos.ts
  packages/config/src/projects/bridges/avalanche.ts
  packages/config/src/projects/bridges/cBridge.ts
  packages/config/src/projects/bridges/chainport.ts
  packages/config/src/projects/bridges/debridge.ts
  packages/config/src/projects/bridges/eclipse.ts
  packages/config/src/projects/bridges/fraxferry.ts
  packages/config/src/projects/bridges/hop.ts
  packages/config/src/projects/bridges/hyphen.ts
  packages/config/src/projects/bridges/immutablezkevm.ts
  packages/config/src/projects/bridges/layerzerov2oft.ts
  packages/config/src/projects/bridges/lightlink.ts
  packages/config/src/projects/bridges/lzOmnichain.ts
  packages/config/src/projects/bridges/multichain.ts
  packages/config/src/projects/bridges/near.ts
  packages/config/src/projects/bridges/nomad.ts
  packages/config/src/projects/bridges/omni.ts
  packages/config/src/projects/bridges/opticsV1.ts
  packages/config/src/projects/bridges/opticsV2.ts
  packages/config/src/projects/bridges/orbit.ts
  packages/config/src/projects/bridges/orbiter.ts
  packages/config/src/projects/bridges/pNetwork.ts
  packages/config/src/projects/bridges/polygonpos.ts
  packages/config/src/projects/bridges/polynetwork.ts
  packages/config/src/projects/bridges/portal.ts
  packages/config/src/projects/bridges/pulseChain.ts
  packages/config/src/projects/bridges/ronin.ts
  packages/config/src/projects/bridges/satellite.ts
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/projects/bridges/sollet.ts
  packages/config/src/projects/bridges/stargate.ts
  packages/config/src/projects/bridges/stargatev2.ts
  packages/config/src/projects/bridges/sygma.ts
  packages/config/src/projects/bridges/symbiosis.ts
  packages/config/src/projects/bridges/synapse.ts
  packages/config/src/projects/bridges/transporter.ts
  packages/config/src/projects/bridges/xdai.ts
Labels: trivial

#5567 Arbi and Zircuit tokens
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/base.ts
  packages/config/src/projects/layer2s/linea.ts
  packages/config/src/projects/layer2s/mantle.ts
  packages/config/src/projects/layer2s/mode.ts
  packages/config/src/projects/layer2s/optimism.ts
  packages/config/src/projects/layer2s/scroll.ts
  packages/config/src/projects/layer2s/zircuit.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5597 Add Caldera badge to Ham
  packages/config/src/projects/layer3s/ham.ts
Labels: trivial

#5598 Include all tokens + typo, grammar, links, wording fixes for Portal.
  packages/config/src/projects/bridges/portal.ts
Labels: research

#5617 Trivial discovery updates 10/28
  packages/backend/discovery/fuel/ethereum/diffHistory.md
  packages/backend/discovery/fuel/ethereum/discovered.json
  packages/backend/discovery/kroma/ethereum/config.jsonc
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/test/snapshots/sanko.riskView.snapshot
  packages/config/src/verification/arbitrum/verified.json
Labels: trivial-discovery

#5631 Add act permission to Orbit stack template
  packages/backend/discovery/_templates/orbitstack/UpgradeExecutor/template.jsonc
  packages/backend/discovery/alephzero/ethereum/diffHistory.md
  packages/backend/discovery/alephzero/ethereum/discovered.json
  packages/backend/discovery/alienx/ethereum/diffHistory.md
  packages/backend/discovery/alienx/ethereum/discovered.json
  packages/backend/discovery/apechain/arbitrum/diffHistory.md
  packages/backend/discovery/apechain/arbitrum/discovered.json
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/deri/arbitrum/diffHistory.md
  packages/backend/discovery/deri/arbitrum/discovered.json
  packages/backend/discovery/edgeless/ethereum/diffHistory.md
  packages/backend/discovery/edgeless/ethereum/discovered.json
  packages/backend/discovery/everclear/ethereum/diffHistory.md
  packages/backend/discovery/everclear/ethereum/discovered.json
  packages/backend/discovery/galxegravity/ethereum/diffHistory.md
  packages/backend/discovery/galxegravity/ethereum/discovered.json
  packages/backend/discovery/hychain/ethereum/diffHistory.md
  packages/backend/discovery/hychain/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/l3x/arbitrum/diffHistory.md
  packages/backend/discovery/l3x/arbitrum/discovered.json
  packages/backend/discovery/molten/arbitrum/diffHistory.md
  packages/backend/discovery/molten/arbitrum/discovered.json
  packages/backend/discovery/parallel/ethereum/diffHistory.md
  packages/backend/discovery/parallel/ethereum/discovered.json
  packages/backend/discovery/playblock/nova/diffHistory.md
  packages/backend/discovery/playblock/nova/discovered.json
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/popboss/arbitrum/diffHistory.md
  packages/backend/discovery/popboss/arbitrum/discovered.json
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
  packages/backend/discovery/reya/ethereum/diffHistory.md
  packages/backend/discovery/reya/ethereum/discovered.json
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/sxnetwork/ethereum/diffHistory.md
  packages/backend/discovery/sxnetwork/ethereum/discovered.json
  packages/backend/discovery/winr/arbitrum/diffHistory.md
  packages/backend/discovery/winr/arbitrum/discovered.json
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/backend/discovery/xchain/ethereum/diffHistory.md
  packages/backend/discovery/xchain/ethereum/discovered.json
Labels: trivial, research

#5665 Shape L2: Switch to Multisig gov
  packages/backend/discovery/shape/ethereum/config.jsonc
  packages/backend/discovery/shape/ethereum/diffHistory.md
  packages/backend/discovery/shape/ethereum/discovered.json
  packages/config/src/projects/layer2s/shape.ts
Labels: trivial

#5625 Enforce strict rules for canonically bridged assets
  packages/backend/discovery/_templates/global/ProxyAdmin/shape/ProxyAdmin_Blast.sol
  packages/backend/discovery/blast/ethereum/diffHistory.md
  packages/backend/discovery/blast/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/config/src/projects/layer2s/alienx.ts
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/base.ts
  packages/config/src/projects/layer2s/blast.ts
  packages/config/src/projects/layer2s/bob.ts
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/projects/layer2s/kroma.ts
  packages/config/src/projects/layer2s/linea.ts
  packages/config/src/projects/layer2s/nova.ts
  packages/config/src/projects/layer2s/optimism.ts
  packages/config/src/projects/layer2s/paradex.ts
  packages/config/src/projects/layer2s/real.ts
  packages/config/src/projects/layer2s/scroll.ts
  packages/config/src/projects/layer2s/starknet.ts
  packages/config/src/projects/layer2s/world.ts
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#5676 Dydx: Link to explorer
  packages/backend/discovery/dydx/ethereum/diffHistory.md
  packages/backend/discovery/dydx/ethereum/discovered.json
  packages/config/src/projects/layer2s/dydx.ts
Labels: trivial, research

#5669 Add oevnet (full)
  packages/backend/discovery/_templates/orbitstack/Bridge/shape/Bridge.sol
  packages/backend/discovery/_templates/orbitstack/Outbox/shape/Outbox.sol
  packages/backend/discovery/oevnetwork/ethereum/config.jsonc
  packages/backend/discovery/oevnetwork/ethereum/diffHistory.md
  packages/backend/discovery/oevnetwork/ethereum/discovered.json
  packages/config/src/projects/layer2s/oev.ts
  packages/config/src/test/snapshots/oevnetwork.riskView.snapshot
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research
