Repository l2beat/l2beat, pull requests merged in 2024-01, with the labels that each got.

#2395 Add BOB network
  packages/config/src/layer2s/bob.ts
  packages/config/src/layer2s/index.ts
  packages/frontend/src/static/icons/bob.png
Labels: non-ETH-L2

#2543 Update amarok
  packages/backend/discovery/amarok/ethereum/config.jsonc
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
Labels: small-discovery-update

#2529 Adding Ola
  packages/config/src/layer2s/index.ts
  packages/config/src/layer2s/ola.ts
  packages/frontend/src/static/icons/ola.png
Labels: upcoming

#2549 Update Polygon zkEVM
  packages/backend/discovery/polygonzkevm/ethereum/config.jsonc
  packages/backend/discovery/polygonzkevm/ethereum/diffHistory.md
  packages/backend/discovery/polygonzkevm/ethereum/discovered.json
Labels: small-discovery-update

#2551 Update EigenLayer
  packages/backend/discovery/eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/eigenlayer/ethereum/discovered.json
Labels: small-discovery-update

#2588 Update Starknet
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
Labels: small-discovery-update

#2610 Update Eigenlayer
  packages/backend/discovery/eigenlayer/ethereum/config.jsonc
  packages/backend/discovery/eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/eigenlayer/ethereum/discovered.json
Labels: small-discovery-update

#2611 Update Across-V2
  packages/backend/discovery/across-v2/ethereum/diffHistory.md
  packages/backend/discovery/across-v2/ethereum/discovered.json
Labels: small-discovery-update

#2632 Update Manta Pacific
  packages/backend/discovery/mantapacific/ethereum/diffHistory.md
  packages/backend/discovery/mantapacific/ethereum/discovered.json
Labels: small-discovery-update

#2630 Update pNetwork
  packages/backend/discovery/pNetwork/ethereum/config.jsonc
  packages/backend/discovery/pNetwork/ethereum/diffHistory.md
  packages/backend/discovery/pNetwork/ethereum/discovered.json
  packages/config/src/bridges/pNetwork.ts
Labels: small-discovery-update

#2636 Update Manta Pacific
  packages/backend/discovery/mantapacific/ethereum/diffHistory.md
  packages/backend/discovery/mantapacific/ethereum/discovered.json
Labels: small-discovery-update

#2637 Update Polygon Plasma
  packages/backend/discovery/polygon-plasma/ethereum/diffHistory.md
  packages/backend/discovery/polygon-plasma/ethereum/discovered.json
Labels: small-discovery-update

#2651 Update orbit discovery
  packages/backend/discovery/orbit/ethereum/diffHistory.md
  packages/backend/discovery/orbit/ethereum/discovered.json
Labels: small-discovery-update

#2648 Update layer2financezk discovery
  packages/backend/discovery/layer2financezk/ethereum/config.jsonc
  packages/backend/discovery/layer2financezk/ethereum/discovered.json
Labels: small-discovery-update

#2649 Update l2beat-starkware discovery
  packages/backend/discovery/l2beat-starkware/ethereum/config.jsonc
  packages/backend/discovery/l2beat-starkware/ethereum/discovered.json
Labels: small-discovery-update

#2650 Update symbiosis discovery
  packages/backend/discovery/symbiosis/ethereum/diffHistory.md
  packages/backend/discovery/symbiosis/ethereum/discovered.json
Labels: small-discovery-update

#2641 Update Chainport
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
  turbo.json
Labels: small-discovery-update

#2668 Verify Parallel contracts
  packages/backend/discovery/parallel/ethereum/diffHistory.md
  packages/backend/discovery/parallel/ethereum/discovered.json
  packages/config/src/layer2s/parallel.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: small-discovery-update

#2674 Update pNetwork
  packages/backend/discovery/pNetwork/ethereum/config.jsonc
  packages/backend/discovery/pNetwork/ethereum/discovered.json
Labels: small-discovery-update

#2694 Update Linea minTimestamp
  packages/config/src/layer2s/linea.ts
Labels: trivial

#2581 Add axelar description and discovery
  packages/backend/discovery/satellite/ethereum/config.jsonc
  packages/backend/discovery/satellite/ethereum/diffHistory.md
  packages/backend/discovery/satellite/ethereum/discovered.json
  packages/backend/src/tools/updateDiffHistory.ts
  packages/config/src/bridges/satellite.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend/src/static/images/satellite-architecture.png
  packages/frontend/src/utils/project/getContractSection.ts
Labels: research

#2693 Add slug to socket token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#2690 Add seq/val handler for Arbitrum
  packages/config/src/discovery/values/projects/arbitrum/ARBITRUM.ts
  packages/config/src/layer2s/arbitrum.ts
Labels: trivial

#2695 Add opStackDa handler to all op stack projects
  packages/backend/discovery/aevo/ethereum/config.jsonc
  packages/backend/discovery/aevo/ethereum/diffHistory.md
  packages/backend/discovery/aevo/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/config.jsonc
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/lyra/ethereum/config.jsonc
  packages/backend/discovery/lyra/ethereum/diffHistory.md
  packages/backend/discovery/lyra/ethereum/discovered.json
  packages/backend/discovery/mantapacific/ethereum/config.jsonc
  packages/backend/discovery/mantapacific/ethereum/diffHistory.md
  packages/backend/discovery/mantapacific/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/publicgoodsnetwork/ethereum/config.jsonc
  packages/backend/discovery/publicgoodsnetwork/ethereum/diffHistory.md
  packages/backend/discovery/publicgoodsnetwork/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/config.jsonc
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/backend/package.json
  packages/config/package.json
  yarn.lock
Labels: research, code

#2696 Convert PGN into an Optimium
  packages/config/src/layer2s/publicgoodsnetwork.ts
Labels: trivial, research

#2697 Add Zentachain (upcoming)
  packages/config/src/layer2s/index.ts
  packages/config/src/layer2s/zentachain.ts
  packages/frontend/src/static/icons/zentachain.png
Labels: trivial

#2692 Show skipped database tests in the output
  packages/backend/src/core/SequenceProcessor.test.ts
  packages/backend/src/peripherals/database/AggregatedReportRepository.test.ts
  packages/backend/src/peripherals/database/AggregatedReportStatusRepository.test.ts
  packages/backend/src/peripherals/database/BalanceRepository.test.ts
  packages/backend/src/peripherals/database/BalanceStatusRepository.test.ts
  packages/backend/src/peripherals/database/BlockNumberRepository.test.ts
  packages/backend/src/peripherals/database/CirculatingSupplyRepository.test.ts
  packages/backend/src/peripherals/database/DiscoveryCacheRepository.test.ts
  packages/backend/src/peripherals/database/IndexerStateRepository.test.ts
  packages/backend/src/peripherals/database/LivenessConfigurationRepository.test.ts
  packages/backend/src/peripherals/database/LivenessRepository.test.ts
  packages/backend/src/peripherals/database/PriceRepository.test.ts
  packages/backend/src/peripherals/database/ReportRepository.test.ts
  packages/backend/src/peripherals/database/ReportStatusRepository.test.ts
  packages/backend/src/peripherals/database/TotalSupplyRepository.test.ts
  packages/backend/src/peripherals/database/TotalSupplyStatusRepository.test.ts
  packages/backend/src/peripherals/database/activity/BlockTransactionCountRepository.test.ts
  packages/backend/src/peripherals/database/activity/DailyTransactionCountViewRepository.test.ts
  packages/backend/src/peripherals/database/activity/StarkexCountRepository.test.ts
  packages/backend/src/peripherals/database/activity/ZksyncTransactionRepository.test.ts
  packages/backend/src/peripherals/database/discovery/DiscoveryHistoryRepository.test.ts
  packages/backend/src/peripherals/database/discovery/UpdateMonitorRepository.test.ts
  packages/backend/src/peripherals/database/discovery/UpdateNotifierRepository.test.ts
  packages/backend/src/peripherals/database/shared/BaseRepository.test.ts
  packages/backend/src/peripherals/database/shared/Database.test.ts
  packages/backend/src/test/database.ts
Labels: code

#2699 Add RARI L3 (under review)
  packages/config/src/layer3s/index.ts
  packages/config/src/layer3s/rari.ts
  packages/frontend/src/static/icons/rari.png
Labels: trivial, research

#2678 Add POL token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#2698 Add Hypr (active)
  packages/backend/discovery/hypr/ethereum/config.jsonc
  packages/backend/discovery/hypr/ethereum/diffHistory.md
  packages/backend/discovery/hypr/ethereum/discovered.json
  packages/config/package.json
  packages/config/scripts/checkRpc.ts
  packages/config/src/layer2s/base.ts
  packages/config/src/layer2s/hypr.ts
  packages/config/src/layer2s/lyra.ts
  packages/config/src/layer2s/publicgoodsnetwork.ts
  packages/config/src/layer2s/templates/opStack.ts
  packages/config/src/layer2s/zora.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#2665 Configure backend through feature flags
  packages/backend/README.md
  packages/backend/src/Application.ts
  packages/backend/src/config/Config.ts
  packages/backend/src/config/FeatureFlags.test.ts
  packages/backend/src/config/FeatureFlags.ts
  packages/backend/src/config/config.local.ts
  packages/backend/src/config/config.production.ts
  packages/backend/src/config/config.staging.ts
  packages/backend/src/config/getChainTvlConfig.ts
  packages/backend/src/config/index.ts
  packages/backend/src/config/makeConfig.ts
Labels: code

#2702 Sanitize the Update Monitor diffs
  packages/backend/src/core/discovery/UpdateMonitor.test.ts
  packages/backend/src/core/discovery/UpdateMonitor.ts
  packages/backend/src/core/discovery/sanitizeDiscoveryOutput.ts
  packages/backend/src/peripherals/database/discovery/DiscoveryHistoryRepository.ts
Labels: code

#2706 Add initial XAI config
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
Labels: trivial, research

#2704 Add initial RARI chain config
  packages/backend/discovery/rari/arbitrum/config.jsonc
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
Labels: trivial, research

#2701 Fix broken links and add milestone update in `metis` docs
  packages/config/src/common/riskView.ts
  packages/config/src/layer2s/metis.ts
Labels: trivial, external

#2708 Add Orbit Stack template
  packages/config/src/common/riskView.ts
  packages/config/src/discovery/OpStackTypes.ts
  packages/config/src/discovery/OrbitStackTypes.ts
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/discovery/StackTemplateTypes.ts
  packages/config/src/layer2s/parallel.ts
  packages/config/src/layer2s/templates/orbitStack.ts
  packages/config/src/layer3s/deri.ts
Labels: code

#2715 Update Chainport
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
Labels: trivial-discovery

#2716 Update pNetwork
  packages/backend/discovery/pNetwork/ethereum/config.jsonc
  packages/backend/discovery/pNetwork/ethereum/diffHistory.md
  packages/backend/discovery/pNetwork/ethereum/discovered.json
Labels: trivial-discovery

#2717 Update Satellite
  packages/backend/discovery/satellite/ethereum/config.jsonc
  packages/backend/discovery/satellite/ethereum/diffHistory.md
  packages/backend/discovery/satellite/ethereum/discovered.json
Labels: trivial-discovery

#2675 Remove Sass
  .github/workflows/chromatic.yml
  packages/frontend/.storybook/preview.tsx
  packages/frontend/gulpfile.js
  packages/frontend/package.json
  packages/frontend/src/components/Logo.tsx
  packages/frontend/src/components/PageWrapper.tsx
  packages/frontend/src/components/chart/Chart.tsx
  packages/frontend/src/components/chart/ChartComingSoonState.tsx
  packages/frontend/src/components/chart/ChartLoader.tsx
  packages/frontend/src/components/chart/RangeControls.tsx
  packages/frontend/src/components/chart/TimeRange.tsx
  packages/frontend/src/components/header/Header.tsx
  packages/frontend/src/components/icons/Icon.tsx
  packages/frontend/src/components/icons/Icons.stories.tsx
  packages/frontend/src/components/icons/symbols/CheckIcon.tsx
  packages/frontend/src/components/icons/symbols/CodeIcon.tsx
  packages/frontend/src/components/icons/symbols/GlobeIcon.tsx
  packages/frontend/src/components/icons/symbols/SearchIcon.tsx
  packages/frontend/src/components/index.ts
  packages/frontend/src/pages/bridges/projects/props/getProps.ts
  packages/frontend/src/pages/bridges/projects/view/ProjectPage.tsx
  packages/frontend/src/pages/definitions/DefinitionsPage.tsx
  packages/frontend/src/pages/definitions/getProps.tsx
  packages/frontend/src/pages/definitions/index.tsx
  packages/frontend/src/pages/definitions/maturity.md
  packages/frontend/src/pages/definitions/style.css
  packages/frontend/src/pages/donate/DonateDetails.tsx
  packages/frontend/src/pages/donate/DonateLetter.tsx
  packages/frontend/src/pages/donate/DonatePage.tsx
  packages/frontend/src/pages/donate/GitcoinButton.tsx
  packages/frontend/src/pages/layer3s/props/getProps.ts
  packages/frontend/src/pages/layer3s/view/ProjectPage.tsx
  packages/frontend/src/pages/markdown/getHtml.ts
  packages/frontend/src/pages/markdown/renderHeading.tsx
  packages/frontend/src/pages/meta-images/ActivityMetaImage.tsx
  packages/frontend/src/pages/meta-images/DetailedTvlMetaImage.tsx
  packages/frontend/src/pages/meta-images/MetaImage.stories.tsx
  packages/frontend/src/pages/meta-images/MetaImageHeader.tsx
  packages/frontend/src/pages/meta-images/TvlMetaImage.tsx
  packages/frontend/src/pages/meta-images/getProps.ts
  packages/frontend/src/pages/scaling/projects/props/getProps.ts
  packages/frontend/src/pages/scaling/projects/view/ProjectPage.tsx
  packages/frontend/src/scripts/charts/view-controller/header/getChangeHtml.ts
  packages/frontend/src/scripts/charts/view-controller/hovers.ts
  packages/frontend/src/styles/_global.scss
  packages/frontend/src/styles/_meta.scss
  packages/frontend/src/styles/_properties.scss
  packages/frontend/src/styles/components/_DonateDetails.scss
  packages/frontend/src/styles/components/_DonateLetter.scss
  packages/frontend/src/styles/components/_GitcoinButton.scss
  packages/frontend/src/styles/components/_Header.scss
  packages/frontend/src/styles/components/_Heading.scss
  packages/frontend/src/styles/components/_Logo.scss
  packages/frontend/src/styles/main.scss
  packages/frontend/src/styles/style.css
  packages/frontend/src/utils/project/getHeader.ts
  packages/frontend/tailwind.config.js
  yarn.lock
Labels: code

#2719 Update description text size in DetailsHeader component
  packages/frontend/src/components/header/DetailsHeader.tsx
Labels: trivial

#2710 Configure activity and updateMonitor automatically
  packages/backend/src/config/Config.ts
  packages/backend/src/config/features/activity.ts
  packages/backend/src/config/features/tvl.ts
  packages/backend/src/config/features/updateMonitor.ts
  packages/backend/src/config/getChainsWithTokens.ts
  packages/backend/src/config/makeConfig.ts
  packages/backend/src/core/activity/ActivityTransactionConfig.ts
  packages/backend/src/core/activity/counters/AztecConnectCounter.ts
  packages/backend/src/core/activity/counters/AztecCounter.ts
  packages/backend/src/core/activity/counters/LoopringCounter.ts
  packages/backend/src/core/activity/counters/RpcCounter.ts
  packages/backend/src/core/activity/counters/StarkexCounter.test.ts
  packages/backend/src/core/activity/counters/StarkexCounter.ts
  packages/backend/src/core/activity/counters/StarknetCounter.ts
  packages/backend/src/core/activity/counters/ZksyncCounter.ts
  packages/backend/src/modules/activity/ActivityModule.test.ts
  packages/backend/src/modules/activity/ActivityModule.ts
  packages/backend/src/modules/activity/createTransactionCounters.ts
  packages/backend/src/peripherals/aztec/AztecConnectClient.test.ts
  packages/backend/src/peripherals/aztec/AztecConnectClient.ts
  packages/backend/src/peripherals/aztec/index.ts
  packages/backend/src/peripherals/loopring/LoopringClient.test.ts
  packages/backend/src/peripherals/loopring/LoopringClient.ts
  packages/backend/src/peripherals/starkex/StarkexClient.test.ts
  packages/backend/src/peripherals/starkex/StarkexClient.ts
  packages/backend/src/peripherals/zksync/ZksyncClient.test.ts
  packages/backend/src/peripherals/zksync/ZksyncClient.ts
  packages/config/src/layer2s/arbitrum.ts
  packages/config/src/layer2s/aztecV1.ts
  packages/config/src/layer2s/bobanetwork.ts
  packages/config/src/layer2s/index.test.ts
  packages/config/src/layer2s/kroma.ts
  packages/config/src/layer2s/linea.ts
  packages/config/src/layer2s/loopring.ts
  packages/config/src/layer2s/mantapacific.ts
  packages/config/src/layer2s/mantle.ts
  packages/config/src/layer2s/metis.ts
  packages/config/src/layer2s/nova.ts
  packages/config/src/layer2s/optimism.ts
  packages/config/src/layer2s/polygonzkevm.ts
  packages/config/src/layer2s/scroll.ts
  packages/config/src/layer2s/starknet.ts
  packages/config/src/layer2s/templates/opStack.ts
  packages/config/src/layer2s/types/Layer2TransactionApi.ts
  packages/config/src/layer2s/zksyncera.ts
  packages/config/src/layer2s/zksynclite.ts
Labels: code

#2711 Add WEMIX & improve tokens script
  packages/backend/src/config/features/tvl.ts
  packages/config/scripts/tokens/tokens.test.ts
  packages/config/scripts/tokens/tokens.ts
  packages/config/scripts/tokens/utils/ScriptLogger.ts
  packages/config/scripts/tokens/utils/fsIntegration.ts
  packages/config/src/layer2s/kroma.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: code

#2724 Add support for Optimiums to Orbit template
  packages/config/src/layer2s/templates/orbitStack.ts
Labels: trivial, code

#2721 Add upgrades and governance section
  packages/config/src/layer2s/types/Layer2.ts
  packages/frontend/src/components/project/UpgradesAndGovernanceSection.stories.tsx
  packages/frontend/src/components/project/UpgradesAndGovernanceSection.tsx
  packages/frontend/src/components/project/sectionId.ts
  packages/frontend/src/pages/scaling/projects/props/getProjectDetails.ts
  packages/frontend/src/pages/scaling/projects/view/ProjectDetails.tsx
  packages/frontend/src/pages/types.ts
Labels: trivial, code

#2712 Add Tradable to upcoming projects
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/layer2s/index.ts
  packages/config/src/layer2s/tradable.ts
  packages/frontend/src/static/icons/tradable.png
Labels: trivial, external

#2479 Add difftastic based diff script
  packages/backend/package.json
  packages/backend/src/tools/powerdiff.ts
  yarn.lock
Labels: code

#2184 Add funding sources to donate page
  packages/frontend/src/components/PageContent.tsx
  packages/frontend/src/pages/donate/DonateLetter.stories.tsx
  packages/frontend/src/pages/donate/DonateLetter.tsx
  packages/frontend/src/pages/donate/DonatePage.tsx
  packages/frontend/src/pages/donate/GitcoinButton.tsx
  packages/frontend/src/pages/donate/getProps.ts
  packages/frontend/src/pages/donate/index.tsx
  packages/frontend/src/pages/donate/props/getProps.tsx
  packages/frontend/src/pages/donate/view/DonateDetails.tsx
  packages/frontend/src/pages/donate/view/DonateFundingSources.stories.tsx
  packages/frontend/src/pages/donate/view/DonateFundingSources.tsx
  packages/frontend/src/pages/donate/view/DonatePage.tsx
  packages/frontend/src/static/fonts/Lora/OFL.txt
  packages/frontend/src/static/fonts/Lora/lora-v17-latin-italic.woff2
  packages/frontend/src/styles/style.css
  packages/frontend/tailwind.config.js
Labels: code

#2730 Remove unused status endpoints
  packages/backend/README.md
  packages/backend/src/api/controllers/status/StatusController.ts
  packages/backend/src/api/controllers/status/view/AggregatedReportsPage.tsx
  packages/backend/src/api/controllers/status/view/PricesPage.tsx
  packages/backend/src/api/routers/StatusRouter.ts
  packages/backend/src/modules/status/StatusModule.ts
Labels: code

#2729 Update Paradex
  packages/backend/discovery/paradex/ethereum/diffHistory.md
  packages/backend/discovery/paradex/ethereum/discovered.json
  packages/config/src/layer2s/paradex.ts
Labels: trivial-discovery

#2732 Update Socket
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
Labels: trivial-discovery
