Repository l2beat/l2beat, pull requests merged in 2024-06, with the labels that each got.

#3987 Exclude USDC from canonical bridge
  packages/config/src/projects/layer2s/taiko.ts
Labels: trivial

#3995 Make USDC canonical on Taiko
  packages/config/src/projects/layer2s/taiko.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4000 Bob update: L2 fee scalar and Multisig nonce ignored
  packages/backend/discovery/bob/ethereum/config.jsonc
  packages/backend/discovery/bob/ethereum/diffHistory.md
  packages/backend/discovery/bob/ethereum/discovered.json
Labels: trivial-discovery

#4001 Swell update: new token supported
  packages/backend/discovery/swell/ethereum/diffHistory.md
  packages/backend/discovery/swell/ethereum/discovered.json
Labels: trivial-discovery

#3998 Update Molten L3 logo
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend/src/static/icons/molten.png
Labels: trivial

#3999 Chainport update: New proposal
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
Labels: trivial-discovery

#4016 Move Term Structure L2 to underreview
  packages/backend/discovery/termstructure/ethereum/config.jsonc
  packages/backend/discovery/termstructure/ethereum/diffHistory.md
  packages/backend/discovery/termstructure/ethereum/discovered.json
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/projects/layer2s/termstructure.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial

#4017 Add Everclear L2 as upcoming
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/projects/layer2s/everclear.ts
  packages/config/src/projects/layer2s/index.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend/src/static/icons/everclear.png
  packages/frontend/src/static/icons/worldcoin-semaphore.png
  packages/frontend/src/static/icons/worldcoin-smtb.png
Labels: trivial

#4019 Make Termstructure discovery more silent
  packages/backend/discovery/termstructure/ethereum/config.jsonc
  packages/backend/discovery/termstructure/ethereum/diffHistory.md
  packages/backend/discovery/termstructure/ethereum/discovered.json
Labels: trivial-discovery

#4018 Make stablecoins stable
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4030 Add Re.al L2 full
  packages/backend/discovery/real/ethereum/config.jsonc
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
  packages/backend/discovery/reya/ethereum/config.jsonc
  packages/backend/discovery/reya/ethereum/diffHistory.md
  packages/backend/discovery/reya/ethereum/discovered.json
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/real.ts
  packages/config/src/projects/layer2s/reya.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend/src/static/icons/real.png
Labels: research

#4039 Configure Re.al discovery (more silence)
  packages/backend/discovery/real/ethereum/config.jsonc
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
Labels: trivial-discovery

#4056 Re.al L2 ignore
  packages/backend/discovery/real/ethereum/config.jsonc
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
Labels: trivial-discovery

#4043 Add MXC full unverified
  packages/backend/discovery/mxc/arbitrum/config.jsonc
  packages/backend/discovery/mxc/arbitrum/diffHistory.md
  packages/backend/discovery/mxc/arbitrum/discovered.json
  packages/backend/discovery/mxc/ethereum/config.jsonc
  packages/backend/discovery/mxc/ethereum/diffHistory.md
  packages/backend/discovery/mxc/ethereum/discovered.json
  packages/config/src/common/ScalingProjectTechnology.ts
  packages/config/src/projects/layer3s/index.test.ts
  packages/config/src/projects/layer3s/mxc.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend/scripts/logos/tinifyLogos.ts
  packages/frontend/src/pages/project/layer2/props/getTechnologyOverview.ts
  packages/frontend/src/pages/project/layer3/props/getProjectDetails.ts
  packages/frontend/src/pages/project/layer3/props/getTechnologyOverview.ts
  packages/frontend/src/static/icons/mxc.png
  packages/frontend2/src/app/asset-risks/[address]/page.tsx
Labels: research

#4078 zkSync Era upgrade v24 (wip)
  packages/backend/discovery/zksync2/ethereum/config.jsonc
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend/src/static/images/architecture/zksync-era.png
  packages/frontend/src/static/images/upgrades-and-governance/zksync-era.png
Labels: research

#4083 Socket update: New vaults, new EOA gov
  packages/backend/discovery/socket/ethereum/config.jsonc
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/config/scripts/socket/index.ts
  packages/config/scripts/socket/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socket/outfiles/socket-crawl-result.json
  packages/config/src/projects/bridges/socket-vaults.json
  packages/config/src/projects/bridges/socket.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4084 Connext update: Router added
  packages/backend/discovery/amarok/ethereum/config.jsonc
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
Labels: trivial-discovery

#4085 Linea update: Ignore currentFinalizedState
  packages/backend/discovery/linea/ethereum/config.jsonc
  packages/backend/discovery/linea/ethereum/diffHistory.md
  packages/backend/discovery/linea/ethereum/discovered.json
Labels: trivial-discovery

#4086 Loopring update: New AMM pool
  packages/backend/discovery/loopring/ethereum/diffHistory.md
  packages/backend/discovery/loopring/ethereum/discovered.json
Labels: trivial-discovery

#4091 Base updates: Gas limit, signer
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
Labels: trivial-discovery

#4088 Optimism update: Ignored
  packages/backend/discovery/optimism/optimism/config.jsonc
  packages/backend/discovery/optimism/optimism/diffHistory.md
  packages/backend/discovery/optimism/optimism/discovered.json
Labels: trivial-discovery

#4092 Switch fraxferry type to Liquidity Network
  packages/config/src/projects/bridges/fraxferry.ts
  packages/config/src/projects/layer2s/fraxtal.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4082 zkSync Era: Add governance section and revise project.ts
  packages/backend/discovery/zksync2/ethereum/config.jsonc
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/backend/scripts/compare-flat/cli.ts
  packages/config/src/common/ScalingProjectProvider.ts
  packages/config/src/common/milestones.ts
  packages/config/src/discovery/values/index.ts
  packages/config/src/discovery/values/projects/zksync2/ZKSYNC_2.ts
  packages/config/src/projects/bridges/fraxferry.ts
  packages/config/src/projects/bridges/orbiter.ts
  packages/config/src/projects/layer2s/cronos.ts
  packages/config/src/projects/layer2s/lens.ts
  packages/config/src/projects/layer2s/sophon.ts
  packages/config/src/projects/layer2s/termstructure.ts
  packages/config/src/projects/layer2s/tradable.ts
  packages/config/src/projects/layer2s/xpla.ts
  packages/config/src/projects/layer2s/zkcandy.ts
  packages/config/src/projects/layer2s/zkspace.ts
  packages/config/src/projects/layer2s/zkswap.ts
  packages/config/src/projects/layer2s/zkswap2.ts
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/config/src/projects/layer2s/zksynclite.ts
  packages/config/src/projects/layer3s/teva.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend/src/components/ScalingLegend.tsx
  packages/frontend/src/components/chart/Chart.stories.tsx
  packages/frontend/src/components/icons/providers/ZkSyncLiteIcon.tsx
  packages/frontend/src/components/table/TypeCell.tsx
  packages/frontend/src/pages/bridges/risk/view/BridgesRiskView.stories.tsx
  packages/frontend/src/pages/donate/props/getProps.tsx
  packages/frontend/src/pages/project/components/DesktopProjectNavigation.stories.tsx
  packages/frontend/src/pages/project/components/MobileProjectNavigation.stories.tsx
  packages/frontend/src/pages/project/components/sections/StateValidationSection.stories.tsx
  packages/frontend/src/pages/scaling/activity/view/ScalingActivityView.stories.tsx
  packages/frontend/src/pages/scaling/risk/view/ScalingRiskView.stories.tsx
  packages/frontend/src/pages/scaling/summary/view/ScalingSummaryView.stories.tsx
  packages/frontend/src/static/icons/zksync-era.png
  packages/frontend/src/static/images/architecture/zksync-era.png
  packages/frontend/src/static/images/upgrades-and-governance/zksync-era.png
  packages/frontend2/src/app/(legacy)/donate/page.tsx
Labels: research

#4098 Fix the connext twitter link
  packages/config/src/projects/bridges/amarok.ts
Labels: trivial

#4103 Add lightlink LL token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4011 Add AxelarGasService contract to satellite.ts
  packages/backend/discovery/satellite/ethereum/config.jsonc
  packages/backend/discovery/satellite/ethereum/diffHistory.md
  packages/backend/discovery/satellite/ethereum/discovered.json
  packages/config/src/projects/bridges/satellite.ts
  packages/config/src/verification/ethereum/verified.json
Labels: research

#4105 Add weETH to all chains where it is OFT by LayerZero
  packages/config/src/projects/layer2s/blast.ts
  packages/config/src/projects/layer2s/lightlink.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4126 Nod to config changes
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/deri/arbitrum/diffHistory.md
  packages/backend/discovery/deri/arbitrum/discovered.json
  packages/backend/discovery/molten/arbitrum/config.jsonc
  packages/backend/discovery/molten/arbitrum/diffHistory.md
  packages/backend/discovery/molten/arbitrum/discovered.json
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/rari/arbitrum/diffHistory.md
  packages/backend/discovery/rari/arbitrum/discovered.json
  packages/backend/discovery/sanko/arbitrum/diffHistory.md
  packages/backend/discovery/sanko/arbitrum/discovered.json
  packages/backend/discovery/stack/base/diffHistory.md
  packages/backend/discovery/stack/base/discovered.json
  packages/backend/discovery/syndicateframe/base/diffHistory.md
  packages/backend/discovery/syndicateframe/base/discovered.json
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
Labels: trivial

#4132 Fix opti trackedtxs, add sequencer address, add provider
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/config/src/projects/layer2s/optimism.ts
Labels: trivial

#4139 Update Linea links
  packages/config/src/projects/layer2s/linea.ts
Labels: trivial

#4143 Try no 2
  packages/config/src/projects/layer2s/optimism.ts
Labels: trivial

#4136 Re.al update: contract verified, governance changed
  packages/backend/discovery/real/ethereum/config.jsonc
  packages/backend/discovery/real/ethereum/diffHistory.md
  packages/backend/discovery/real/ethereum/discovered.json
  packages/config/src/projects/layer2s/real.ts
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4145 Add OLE token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4146 Add JUICE token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4147 Add RBX token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4138 Superchain update: New SC threshold, Guardian MS, Deputy, Liveness
  packages/backend/discovery/metal/ethereum/config.jsonc
  packages/backend/discovery/metal/ethereum/diffHistory.md
  packages/backend/discovery/metal/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/config.jsonc
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/config.jsonc
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/config/src/projects/layer2s/metal.ts
  packages/config/src/projects/layer2s/mode.ts
  packages/config/src/projects/layer2s/zora.ts
Labels: trivial-discovery

#4151 Polygon plasma update: Ignore nonce
  packages/backend/discovery/polygon-plasma/ethereum/config.jsonc
  packages/backend/discovery/polygon-plasma/ethereum/diffHistory.md
  packages/backend/discovery/polygon-plasma/ethereum/discovered.json
Labels: trivial-discovery

#4150 Add WOOL to Blast and (s)USDe to all supported chains
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4125 Update display shortName for popapex and syndicateframe
  packages/config/src/projects/layer3s/popapex.ts
  packages/config/src/projects/layer3s/syndicateframe.ts
Labels: website, trivial

#4170 Add acrossv3 archi diagram
  packages/config/src/projects/bridges/acrossV3.ts
  packages/frontend2/public/images/architecture/acrossV3.png
  packages/frontend2/public/images/architecture/acrossv3.png
Labels: research

#4173 Trivial discovery updates
  packages/backend/discovery/amarok/ethereum/config.jsonc
  packages/backend/discovery/amarok/ethereum/diffHistory.md
  packages/backend/discovery/amarok/ethereum/discovered.json
  packages/backend/discovery/orderly/ethereum/diffHistory.md
  packages/backend/discovery/orderly/ethereum/discovered.json
Labels: trivial-discovery

#4182 Add taiko associated token to taiko
  packages/config/src/projects/layer2s/taiko.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4178 Add mTokens to mantapacific
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4184 Portal (Wormhole) revision, add diagram
  packages/backend/discovery/portal/ethereum/config.jsonc
  packages/backend/discovery/portal/ethereum/diffHistory.md
  packages/backend/discovery/portal/ethereum/discovered.json
  packages/config/src/projects/bridges/portal.ts
  packages/config/src/verification/ethereum/verified.json
  packages/frontend2/public/images/architecture/portal.png
Labels: research

#4194 Add MXC token as associated
  packages/config/src/projects/layer3s/mxc.ts
Labels: trivial

#4193 Trivial discovery updates 06/17
  packages/backend/discovery/orderly/ethereum/diffHistory.md
  packages/backend/discovery/orderly/ethereum/discovered.json
  packages/backend/discovery/paradex/ethereum/diffHistory.md
  packages/backend/discovery/paradex/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
Labels: trivial-discovery

#3979 Add stargatev2 full
  packages/backend/discovery/stargatev2/arbitrum/config.jsonc
  packages/backend/discovery/stargatev2/arbitrum/diffHistory.md
  packages/backend/discovery/stargatev2/arbitrum/discovered.json
  packages/backend/discovery/stargatev2/base/config.jsonc
  packages/backend/discovery/stargatev2/base/diffHistory.md
  packages/backend/discovery/stargatev2/base/discovered.json
  packages/backend/discovery/stargatev2/ethereum/config.jsonc
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
  packages/backend/discovery/stargatev2/linea/config.jsonc
  packages/backend/discovery/stargatev2/linea/diffHistory.md
  packages/backend/discovery/stargatev2/linea/discovered.json
  packages/backend/discovery/stargatev2/mantle/config.jsonc
  packages/backend/discovery/stargatev2/mantle/diffHistory.md
  packages/backend/discovery/stargatev2/mantle/discovered.json
  packages/backend/discovery/stargatev2/metis/config.jsonc
  packages/backend/discovery/stargatev2/metis/diffHistory.md
  packages/backend/discovery/stargatev2/metis/discovered.json
  packages/backend/discovery/stargatev2/optimism/config.jsonc
  packages/backend/discovery/stargatev2/optimism/diffHistory.md
  packages/backend/discovery/stargatev2/optimism/discovered.json
  packages/backend/discovery/stargatev2/scroll/config.jsonc
  packages/backend/discovery/stargatev2/scroll/diffHistory.md
  packages/backend/discovery/stargatev2/scroll/discovered.json
  packages/config/package.json
  packages/config/scripts/checkVerifiedContracts/chains.ts
  packages/config/scripts/stargatev2-pools/index.ts
  packages/config/src/projects/bridges/index.ts
  packages/config/src/projects/bridges/stargatev2.ts
  packages/config/src/projects/layer2s/mantle.ts
  packages/config/src/projects/layer2s/metis.ts
  packages/config/src/utils/chains.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/base/verified.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/linea/verified.json
  packages/config/src/verification/mantle/verified.json
  packages/config/src/verification/metis/verified.json
  packages/config/src/verification/optimism/verified.json
  packages/config/src/verification/projects.json
  packages/config/src/verification/scroll/verified.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/stargatev2.png
  packages/frontend2/public/images/architecture/stargatev2.png
Labels: research

#3921 Add hychain as orbitstackL2 with discovery
  packages/backend/discovery/hychain/ethereum/config.jsonc
  packages/backend/discovery/hychain/ethereum/diffHistory.md
  packages/backend/discovery/hychain/ethereum/discovered.json
  packages/config/src/projects/layer2s/hychain.ts
  packages/config/src/verification/arbitrum/verified.json
  packages/config/src/verification/base/verified.json
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#4200 Rename Stargate v2 (LayerZero v2)
  packages/config/src/projects/bridges/stargatev2.ts
Labels: trivial

#4204 Add ZK token
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4196 Add Lambda L2 (full)
  packages/backend/discovery/lambda/ethereum/config.jsonc
  packages/backend/discovery/lambda/ethereum/diffHistory.md
  packages/backend/discovery/lambda/ethereum/discovered.json
  packages/config/src/common/ScalingProjectPurpose.ts
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/lambda.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/lambda.png
  packages/frontend2/public/images/architecture/lambda.png
Labels: research

#3710 Add Transporter Bridge
  packages/backend/discovery/_templates/transporter/CommitStore/template.jsonc
  packages/backend/discovery/_templates/transporter/OffRamp/template.jsonc
  packages/backend/discovery/_templates/transporter/OnRamp/template.jsonc
  packages/backend/discovery/_templates/transporter/OnRampV2/template.jsonc
  packages/backend/discovery/_templates/transporter/PriceRegistry/template.jsonc
  packages/backend/discovery/_templates/transporter/Router/template.jsonc
  packages/backend/discovery/_templates/transporter/RouterV2/template.jsonc
  packages/backend/discovery/_templates/transporter/TokenPool/template.jsonc
  packages/backend/discovery/transporter/ethereum/config.jsonc
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/projects/bridges/index.ts
  packages/config/src/projects/bridges/transporter.ts
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/database/src/kysely/generated/types.ts
  packages/discovery/src/discovery/analysis/TemplateService.ts
  packages/discovery/src/discovery/source/processSources.ts
  packages/discovery/src/discovery/source/sourceToEntries.ts
  packages/discovery/src/flatten/utils.ts
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/transporter.png
  packages/frontend2/public/images/architecture/transporter.png
Labels: research

#4216 Trivial discovery updates 06/19
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/hychain/ethereum/diffHistory.md
  packages/backend/discovery/hychain/ethereum/discovered.json
  packages/backend/discovery/optimism/optimism/config.jsonc
  packages/backend/discovery/optimism/optimism/diffHistory.md
  packages/backend/discovery/optimism/optimism/discovered.json
  packages/backend/discovery/stargatev2/arbitrum/diffHistory.md
  packages/backend/discovery/stargatev2/arbitrum/discovered.json
  packages/backend/discovery/stargatev2/base/diffHistory.md
  packages/backend/discovery/stargatev2/base/discovered.json
  packages/backend/discovery/stargatev2/mantle/diffHistory.md
  packages/backend/discovery/stargatev2/mantle/discovered.json
  packages/backend/discovery/stargatev2/metis/diffHistory.md
  packages/backend/discovery/stargatev2/metis/discovered.json
  packages/backend/discovery/stargatev2/optimism/diffHistory.md
  packages/backend/discovery/stargatev2/optimism/discovered.json
  packages/backend/discovery/stargatev2/scroll/diffHistory.md
  packages/backend/discovery/stargatev2/scroll/discovered.json
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
Labels: trivial-discovery

#4224 Disable Lambda finality
  packages/config/src/projects/layer2s/lambda.ts
Labels: trivial

#4227 Fix zklinknova WETH
  packages/config/src/projects/layer3s/zklinknova.ts
Labels: trivial

#4231 Orbit update: new unverified PolicyAdmin
  packages/backend/discovery/orbit/ethereum/diffHistory.md
  packages/backend/discovery/orbit/ethereum/discovered.json
  packages/config/src/projects/bridges/orbit.ts
  packages/config/src/verification/projects.json
Labels: trivial-discovery

#4211 Add LayerZero v2 OFTs (Bridge, full)
  packages/backend/discovery/layerzerov2oft/ethereum/config.jsonc
  packages/backend/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/backend/discovery/layerzerov2oft/ethereum/discovered.json
  packages/config/scripts/omnichain/data.csv
  packages/config/scripts/omnichain/libraries.csv
  packages/config/scripts/omnichain/lzv1newsource.json
  packages/config/scripts/omnichain/lzv2newsource.json
  packages/config/src/projects/bridges/index.ts
  packages/config/src/projects/bridges/layerzerov2oft.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/frontend2/public/icons/layerzerov2oft.png
  packages/frontend2/public/images/architecture/layerzerov2oft.png
Labels: research

#4238 Hack l2beat
  packages/config/src/projects/layer2s/templates/orbitStack.ts
Labels: code

#4245 Add ZRO to optimism, arbi, base
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4258 Add BTCT warning
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4265 Remove weETH external token from Arbitrum
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4269 Give popapex a shortname
  packages/config/src/projects/layer3s/popapex.ts
Labels: website

#4270 Trivial discovery updates0624
  packages/backend/discovery/arbitrum/arbitrum/diffHistory.md
  packages/backend/discovery/arbitrum/arbitrum/discovered.json
  packages/backend/discovery/kinto/ethereum/config.jsonc
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/transporter/ethereum/diffHistory.md
  packages/backend/discovery/transporter/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4253 Kroma update: ZK verifier upgraded
  packages/backend/discovery/kroma/ethereum/diffHistory.md
  packages/backend/discovery/kroma/ethereum/discovered.json
  packages/config/src/verification/ethereum/verified.json
Labels: trivial-discovery

#4267 zklink nova: Reclassify tokens as externally bridged (apart from linea)
  packages/config/src/projects/layer3s/zklinknova.ts
Labels: research

#4275 Degen: Stacked risks hardcoded
  packages/config/src/projects/layer3s/degen.ts
Labels: research

#4278 zkLink Nova: Reclassify ethereum escrows and add two restaking tokens
  packages/config/src/projects/layer3s/zklinknova.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4288 Add ZK Catalog README
  packages/config/src/projects/other/zk-catalog/README.md
Labels: trivial

#4297 Add new Tokens
  packages/backend/discovery/arbitrum/ethereum/config.jsonc
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/config/src/projects/bridges/amarok.ts
  packages/config/src/projects/bridges/stargatev2.ts
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer3s/zklinknova.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/ethereum/verified.json
  packages/config/src/verification/projects.json
Labels: research

#4304 Remove cdplike tokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#4306 Add Blast token
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: trivial

#4311 Add BLAST as associated token
  packages/config/src/projects/layer2s/blast.ts
Labels: trivial

#4315 Delist Transporter
  packages/backend/src/modules/update-monitor/tests/config.test.ts
  packages/config/src/projects/bridges/index.ts
Labels: trivial

#4327 Update Taiko provider
  packages/config/src/common/ScalingProjectProvider.ts
  packages/config/src/projects/layer2s/taiko.ts
  packages/frontend/src/components/icons/index.ts
  packages/frontend/src/components/icons/providers/TaikoIcon.tsx
  packages/frontend/src/components/table/TypeCell.tsx
Labels: trivial
