Repository l2beat/l2beat, pull requests merged in 2025-01, with the labels that each got.

#6263 Trivial discovery updates 01/03
  packages/backend/discovery/_templates/fraxtal/EtherRouter/shape/EtherRouter.sol
  packages/backend/discovery/_templates/fraxtal/EtherRouter/template.jsonc
  packages/backend/discovery/_templates/fraxtal/FraxEtherMinter/shape/FraxEtherMinter.sol
  packages/backend/discovery/_templates/fraxtal/FraxEtherMinter/template.jsonc
  packages/backend/discovery/across-v3/ethereum/config.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/fraxtal/ethereum/diffHistory.md
  packages/backend/discovery/fraxtal/ethereum/discovered.json
  packages/backend/discovery/loopring/ethereum/diffHistory.md
  packages/backend/discovery/loopring/ethereum/discovered.json
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/taiko/ethereum/diffHistory.md
  packages/backend/discovery/taiko/ethereum/discovered.json
  packages/config/src/projects/bridges/acrossV3.ts
  packages/config/src/projects/bridges/chainport.ts
Labels: trivial-discovery

#6271 Update description
  packages/frontend/src/components/countdowns/other-migration/other-migration-tab-notice.tsx
Labels: trivial

#6275 add PUFFER, ONDO, COW, DODO, wormhole tokens for degate and OPN for sophon
  packages/config/src/projects/layer2s/sophon.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6277 Add swell (full)
  packages/backend/discovery/swell/ethereum/config.jsonc
  packages/backend/discovery/swell/ethereum/diffHistory.md
  packages/backend/discovery/swell/ethereum/discovered.json
  packages/config/src/projects/layer2s/swell.ts
  packages/config/src/test/constants.ts
  packages/config/src/test/snapshots/swell.riskView.snapshot
  packages/frontend/public/icons/swell.png
  packages/frontend/public/images/architecture/swell.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6298 Trivial discovery updates 01/08
  packages/backend/discovery/_templates/succinct/SP1Blobstream/template.jsonc
  packages/backend/discovery/arbitrum/arbitrum/diffHistory.md
  packages/backend/discovery/arbitrum/arbitrum/discovered.json
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/blobstream/arbitrum/diffHistory.md
  packages/backend/discovery/blobstream/arbitrum/discovered.json
  packages/backend/discovery/blobstream/base/diffHistory.md
  packages/backend/discovery/blobstream/base/discovered.json
  packages/backend/discovery/blobstream/ethereum/diffHistory.md
  packages/backend/discovery/blobstream/ethereum/discovered.json
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/kinto/kinto/config.jsonc
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/socket/ethereum/diffHistory.md
  packages/backend/discovery/socket/ethereum/discovered.json
  packages/backend/discovery/xlayer/ethereum/config.jsonc
  packages/backend/discovery/xlayer/ethereum/diffHistory.md
  packages/backend/discovery/xlayer/ethereum/discovered.json
  packages/backend/output.sol
  packages/config/scripts/socketcrawl/index.ts
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/layer2s/xlayer.ts
Labels: trivial-discovery

#6304 Trivial discovery updates 01/09
  packages/backend/discovery/_templates/opstack/FaultDisputeGame/shape/FaultDisputeGame_v1_3_1.sol
  packages/backend/discovery/_templates/opstack/FaultDisputeGame/shape/FaultDisputeGame_v1_3_1_base.sol
  packages/backend/discovery/_templates/opstack/MIPS/shape/MIPS_v1_2_1.sol
  packages/backend/discovery/_templates/opstack/PermissionedDisputeGame/shape/PermissionedDisputeGame_v1_3_1.sol
  packages/backend/discovery/_templates/opstack/PermissionedDisputeGame/shape/PermissionedDisputeGame_v1_3_1_base.sol
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/nova/nova/diffHistory.md
  packages/backend/discovery/nova/nova/discovered.json
  packages/backend/discovery/optimism/ethereum/config.jsonc
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/treasure/ethereum/diffHistory.md
  packages/backend/discovery/treasure/ethereum/discovered.json
  packages/backend/discovery/vector/ethereum/diffHistory.md
  packages/backend/discovery/vector/ethereum/discovered.json
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/projects/layer2s/base.ts
  packages/config/src/projects/layer2s/optimism.ts
Labels: trivial-discovery

#6332 move soon to inreview, add ETH escrow
  packages/config/src/projects/layer2s/soon.ts
  packages/config/src/test/snapshots/soon.riskView.snapshot
Labels: research

#6331 add missing zkstack diagrams
  packages/frontend/public/images/architecture/grvt.png
  packages/frontend/public/images/architecture/treasure.png
  packages/frontend/public/images/architecture/zeronetwork.png
Labels: research

#6242 Add GRVT (full)
  packages/backend/discovery/grvt/ethereum/config.jsonc
  packages/backend/discovery/grvt/ethereum/diffHistory.md
  packages/backend/discovery/grvt/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/config.jsonc
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/layer2s/grvt.ts
  packages/config/src/projects/layer2s/templates/zkStack.ts
  packages/config/src/test/constants.ts
  packages/config/src/test/snapshots/grvt.riskView.snapshot
  packages/frontend/src/app/(top-nav)/scaling/projects/[slug]/_components/scaling-project-stats.tsx
  packages/frontend/src/app/(top-nav)/scaling/projects/[slug]/_components/scaling-project-summary.tsx
  packages/frontend/src/app/(top-nav)/scaling/projects/[slug]/_components/token-breakdown-stat.tsx
  packages/frontend/src/app/(top-nav)/scaling/projects/[slug]/_components/value-locked-summary.tsx
  packages/frontend/src/server/features/scaling/project/get-scaling-project-entry.ts
Labels: research

#6380 add swell token as associated
  packages/config/src/projects/layer2s/swell.ts
Labels: trivial

#6387 add absolute prestate hash decoding where known
  packages/backend/discovery/_templates/opstack/FaultDisputeGame/template.jsonc
  packages/backend/discovery/_templates/opstack/PermissionedDisputeGame/template.jsonc
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/globalTypes.jsonc
  packages/backend/discovery/ink/ethereum/diffHistory.md
  packages/backend/discovery/ink/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/soneium/ethereum/diffHistory.md
  packages/backend/discovery/soneium/ethereum/discovered.json
  packages/backend/discovery/swell/ethereum/diffHistory.md
  packages/backend/discovery/swell/ethereum/discovered.json
Labels: research

#6399 Move superpos under review
  packages/config/src/projects/layer3s/superposition.ts
  packages/config/src/test/snapshots/superposition.riskView.snapshot
Labels: trivial, research

#6401 Dedup descriptions for optimism
  packages/config/src/projects/layer2s/optimism.ts
Labels: research

#6389 Add educhain (full)
  packages/backend/discovery/educhain/arbitrum/config.jsonc
  packages/backend/discovery/educhain/arbitrum/diffHistory.md
  packages/backend/discovery/educhain/arbitrum/discovered.json
  packages/config/src/projects/layer2s/corn.ts
  packages/config/src/projects/layer3s/educhain.ts
  packages/config/src/projects/other/da-beat/dac/educhain.ts
  packages/config/src/projects/other/da-beat/index.ts
  packages/config/src/test/snapshots/educhain.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/verification/projects.json
Labels: research

#6402 add new logo and reason for others to EDU
  packages/config/src/projects/layer3s/educhain.ts
  packages/frontend/public/icons/edu-chain.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: trivial, research

#6406 Discovery updates 01/17
  packages/backend/discovery/educhain/arbitrum/diffHistory.md
  packages/backend/discovery/educhain/arbitrum/discovered.json
  packages/backend/discovery/zeronetwork/ethereum/diffHistory.md
  packages/backend/discovery/zeronetwork/ethereum/discovered.json
Labels: trivial-discovery

#6400 tokens: SOULS, XBG, USDT0, and plenty canonical tokens sourced from the script
  packages/config/src/projects/layer2s/ink.ts
  packages/config/src/projects/layer2s/polygonpos.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/l2b/src/implementations/rpcDeploymentFetch.ts
Labels: research

#6413 archive hypr
  packages/config/src/projects/layer2s/hypr.ts
Labels: trivial

#6403 Add corn (full)
  packages/backend/discovery/_templates/orbitstack/Bridge/shape/ERC20Bridge_gastoken_corn.sol
  packages/backend/discovery/corn/ethereum/config.jsonc
  packages/backend/discovery/corn/ethereum/diffHistory.md
  packages/backend/discovery/corn/ethereum/discovered.json
  packages/config/src/projects/layer2s/corn.ts
  packages/config/src/projects/other/da-beat/dac/corn.ts
  packages/config/src/projects/other/da-beat/index.ts
  packages/config/src/test/snapshots/corn.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6434 Discovery updates 01/20
  packages/backend/discovery/_templates/opstack/L1StandardBridge_soon/shape/L1StandardBridge2.sol
  packages/backend/discovery/educhain/arbitrum/diffHistory.md
  packages/backend/discovery/educhain/arbitrum/discovered.json
  packages/backend/discovery/polygon-pos/ethereum/diffHistory.md
  packages/backend/discovery/polygon-pos/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/zksync2/diffHistory.md
  packages/backend/discovery/shared-zk-stack/zksync2/discovered.json
  packages/backend/discovery/soon/ethereum/diffHistory.md
  packages/backend/discovery/soon/ethereum/discovered.json
  packages/backend/discovery/xlayer/ethereum/diffHistory.md
  packages/backend/discovery/xlayer/ethereum/discovered.json
  packages/config/src/common/riskView.ts
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/projects/layer2s/kinto.ts
  packages/config/src/projects/layer2s/nova.ts
  packages/config/src/projects/layer2s/polygonzkevm.ts
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/test/snapshots/arbitrum.riskView.snapshot
  packages/config/src/test/snapshots/educhain.riskView.snapshot
  packages/config/src/test/snapshots/kinto.riskView.snapshot
  packages/config/src/test/snapshots/nova.riskView.snapshot
  packages/config/src/test/snapshots/polygon-pos.riskView.snapshot
Labels: trivial-discovery

#6440 update morph metadata, add activity
  packages/config/src/projects/layer2s/morph.ts
Labels: research

#6439 add ASTR token to soneium
  packages/config/src/projects/layer2s/soneium.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6379 Morph forcetxs (queue)
  packages/backend/discovery/morph/ethereum/diffHistory.md
  packages/backend/discovery/morph/ethereum/discovered.json
  packages/config/src/projects/layer2s/morph.ts
  packages/config/src/test/snapshots/morph.riskView.snapshot
Labels: research

#6457 Huddle01 under review
  packages/config/src/projects/layer3s/huddle01.ts
  packages/config/src/projects/layer3s/index.ts
  packages/config/src/test/snapshots/huddle01.riskView.snapshot
  packages/frontend/public/icons/huddle01.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6458 Henez under review
  packages/config/src/projects/layer3s/henez.ts
  packages/config/src/projects/layer3s/index.ts
  packages/config/src/test/snapshots/henez.riskView.snapshot
  packages/frontend/public/icons/henez.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6459 Xrone under review
  packages/config/src/projects/layer3s/index.ts
  packages/config/src/projects/layer3s/xrone.ts
  packages/config/src/test/snapshots/xrone.riskView.snapshot
  packages/frontend/public/icons/xrone.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6461 Onchain under review
  packages/config/src/projects/layer3s/index.ts
  packages/config/src/projects/layer3s/onchain.ts
  packages/config/src/test/snapshots/onchain.riskView.snapshot
  packages/frontend/public/icons/onchain.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6470 Discovery updates 01/22
  packages/backend/discovery/_templates/opstack/OptimismPortal2/template.jsonc
  packages/backend/discovery/_templates/shared-zk-stack/L1USDCBridge/shape/L1USDCBridge_reinitialize.sol
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/cronoszkevm/ethereum/diffHistory.md
  packages/backend/discovery/cronoszkevm/ethereum/discovered.json
  packages/backend/discovery/educhain/arbitrum/diffHistory.md
  packages/backend/discovery/educhain/arbitrum/discovered.json
  packages/backend/discovery/facet/ethereum/diffHistory.md
  packages/backend/discovery/facet/ethereum/discovered.json
  packages/backend/discovery/hashkey/ethereum/config.jsonc
  packages/backend/discovery/hashkey/ethereum/diffHistory.md
  packages/backend/discovery/hashkey/ethereum/discovered.json
  packages/backend/discovery/ink/ethereum/diffHistory.md
  packages/backend/discovery/ink/ethereum/discovered.json
  packages/backend/discovery/mantle/ethereum/diffHistory.md
  packages/backend/discovery/mantle/ethereum/discovered.json
  packages/backend/discovery/morph/ethereum/config.jsonc
  packages/backend/discovery/morph/ethereum/diffHistory.md
  packages/backend/discovery/morph/ethereum/discovered.json
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/scroll/ethereum/config.jsonc
  packages/backend/discovery/scroll/ethereum/diffHistory.md
  packages/backend/discovery/scroll/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/soneium/ethereum/diffHistory.md
  packages/backend/discovery/soneium/ethereum/discovered.json
  packages/backend/discovery/sophon/ethereum/config.jsonc
  packages/backend/discovery/sophon/ethereum/diffHistory.md
  packages/backend/discovery/sophon/ethereum/discovered.json
  packages/backend/discovery/swell/ethereum/diffHistory.md
  packages/backend/discovery/swell/ethereum/discovered.json
  packages/backend/discovery/xdai/ethereum/diffHistory.md
  packages/backend/discovery/xdai/ethereum/discovered.json
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/projects/layer2s/scroll.ts
  packages/config/src/projects/layer2s/soon.ts
  packages/config/src/projects/layer2s/sophon.ts
  packages/config/src/test/snapshots/cronoszkevm.riskView.snapshot
Labels: trivial-discovery

#6476 Fix grammar
  packages/frontend/src/components/recategorisation-preview/recategorisation-preview-banner.tsx
Labels: trivial

#6488 Discovery updates 01/23
  packages/backend/discovery/blobstream/arbitrum/diffHistory.md
  packages/backend/discovery/blobstream/arbitrum/discovered.json
  packages/backend/discovery/blobstream/base/diffHistory.md
  packages/backend/discovery/blobstream/base/discovered.json
  packages/backend/discovery/blobstream/ethereum/diffHistory.md
  packages/backend/discovery/blobstream/ethereum/discovered.json
  packages/backend/discovery/cronoszkevm/ethereum/diffHistory.md
  packages/backend/discovery/cronoszkevm/ethereum/discovered.json
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/gluon/ethereum/config.jsonc
  packages/backend/discovery/gluon/ethereum/diffHistory.md
  packages/backend/discovery/gluon/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/winr/arbitrum/diffHistory.md
  packages/backend/discovery/winr/arbitrum/discovered.json
Labels: trivial-discovery

#6495 Bitlazer under review
  packages/config/src/projects/layer3s/bitlazer.ts
  packages/config/src/projects/layer3s/index.ts
  packages/config/src/test/snapshots/bitlazer.riskView.snapshot
  packages/frontend/public/icons/bitlazer.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6490 update blobfetcher tags for `l2b find-l2`
  packages/l2b/src/implementations/find-l2/BlobsFetcher.ts
Labels: research

#6496 move superseed under review
  packages/config/src/projects/layer2s/superseed.ts
  packages/config/src/test/snapshots/superseed.riskView.snapshot
Labels: research

#6501 World Chain upgrade
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/config/src/projects/layer2s/hashkey.ts
  packages/config/src/projects/layer2s/world.ts
  packages/config/src/test/snapshots/hashkey.riskView.snapshot
  packages/config/src/test/snapshots/worldchain.riskView.snapshot
  packages/frontend/public/images/architecture/worldchain.png
Labels: research

#6494 Rufus under review
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/rufus.ts
  packages/config/src/test/snapshots/rufus.riskView.snapshot
  packages/frontend/public/icons/rufus.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6503 Discovery updates 01/24
  packages/backend/discovery/ethernity/ethereum/diffHistory.md
  packages/backend/discovery/ethernity/ethereum/discovered.json
  packages/backend/discovery/ink/ethereum/config.jsonc
  packages/backend/discovery/ink/ethereum/diffHistory.md
  packages/backend/discovery/ink/ethereum/discovered.json
  packages/backend/discovery/popapex/arbitrum/diffHistory.md
  packages/backend/discovery/popapex/arbitrum/discovered.json
  packages/backend/discovery/popboss/arbitrum/diffHistory.md
  packages/backend/discovery/popboss/arbitrum/discovered.json
  packages/backend/discovery/worldchain/ethereum/config.jsonc
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/config/src/projects/layer2s/gpt.ts
  packages/config/src/projects/layer2s/templates/polygonCDKStack.ts
Labels: trivial-discovery

#6504 add Geist L3 (full)
  packages/backend/discovery/commonAddressNames.jsonc
  packages/backend/discovery/degen/base/config.jsonc
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/geist/base/config.jsonc
  packages/backend/discovery/geist/base/diffHistory.md
  packages/backend/discovery/geist/base/discovered.json
  packages/backend/discovery/shape/ethereum/config.jsonc
  packages/backend/discovery/shape/ethereum/diffHistory.md
  packages/backend/discovery/shape/ethereum/discovered.json
  packages/backend/discovery/worldchain/ethereum/config.jsonc
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/config/src/projects/layer3s/geist.ts
  packages/config/src/test/snapshots/geist.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6519 archive TBH (operator inactive, potentially pre-launch)
  packages/config/src/projects/layer2s/thebinaryholdings.ts
Labels: research

#6533 add FIUSD to zksyncera, ANIME to arbitrum
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6542 Discovery updates 01/27
  packages/backend/discovery/_templates/opstack/SystemConfig/shape/SystemConfig_v2_3_0.sol
  packages/backend/discovery/arenaz/ethereum/config.jsonc
  packages/backend/discovery/arenaz/ethereum/diffHistory.md
  packages/backend/discovery/arenaz/ethereum/discovered.json
  packages/backend/discovery/automata/ethereum/config.jsonc
  packages/backend/discovery/automata/ethereum/diffHistory.md
  packages/backend/discovery/automata/ethereum/discovered.json
  packages/backend/discovery/hyperliquid/arbitrum/diffHistory.md
  packages/backend/discovery/hyperliquid/arbitrum/discovered.json
  packages/backend/discovery/metal/ethereum/diffHistory.md
  packages/backend/discovery/metal/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/config.jsonc
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/zksync2/diffHistory.md
  packages/backend/discovery/shared-zk-stack/zksync2/discovered.json
  packages/backend/discovery/soneium/ethereum/diffHistory.md
  packages/backend/discovery/soneium/ethereum/discovered.json
  packages/backend/discovery/sophon/ethereum/diffHistory.md
  packages/backend/discovery/sophon/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/config.jsonc
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/witness/ethereum/diffHistory.md
  packages/backend/discovery/witness/ethereum/discovered.json
  packages/backend/discovery/xai/arbitrum/config.jsonc
  packages/backend/discovery/xai/arbitrum/diffHistory.md
  packages/backend/discovery/xai/arbitrum/discovered.json
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/config/src/projects/layer2s/starknet.ts
Labels: trivial-discovery

#6020 Add new starknet trackedTxs, new hackMultipliers
  packages/config/src/projects/layer2s/starknet.ts
Labels: research

#6557 Add abstract (full)
  packages/backend/discovery/abstract/ethereum/config.jsonc
  packages/backend/discovery/abstract/ethereum/diffHistory.md
  packages/backend/discovery/abstract/ethereum/discovered.json
  packages/config/src/projects/layer2s/abstract.ts
  packages/config/src/projects/layer2s/cronoszkevm.ts
  packages/config/src/projects/layer2s/grvt.ts
  packages/config/src/projects/layer2s/sophon.ts
  packages/config/src/projects/layer2s/templates/zkStack.ts
  packages/config/src/projects/layer2s/treasure.ts
  packages/config/src/projects/layer2s/zeronetwork.ts
  packages/config/src/projects/layer2s/zksyncera.ts
  packages/config/src/test/snapshots/abstract.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6572 archive witness chain
  packages/config/src/projects/layer2s/witness.ts
Labels: research

#6574 Discovery updates 01/28
  packages/backend/discovery/allbridge/ethereum/diffHistory.md
  packages/backend/discovery/allbridge/ethereum/discovered.json
  packages/backend/discovery/aptos/ethereum/diffHistory.md
  packages/backend/discovery/aptos/ethereum/discovered.json
  packages/backend/discovery/galxegravity/ethereum/diffHistory.md
  packages/backend/discovery/galxegravity/ethereum/discovered.json
  packages/backend/discovery/hyperliquid/arbitrum/diffHistory.md
  packages/backend/discovery/hyperliquid/arbitrum/discovered.json
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/backend/discovery/layerzerov2oft/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/arbitrum/diffHistory.md
  packages/backend/discovery/lzomnichain/arbitrum/discovered.json
  packages/backend/discovery/lzomnichain/base/diffHistory.md
  packages/backend/discovery/lzomnichain/base/discovered.json
  packages/backend/discovery/lzomnichain/ethereum/diffHistory.md
  packages/backend/discovery/lzomnichain/ethereum/discovered.json
  packages/backend/discovery/lzomnichain/optimism/diffHistory.md
  packages/backend/discovery/lzomnichain/optimism/discovered.json
  packages/backend/discovery/lzomnichain/polygonpos/diffHistory.md
  packages/backend/discovery/lzomnichain/polygonpos/discovered.json
  packages/backend/discovery/lzomnichain/polygonzkevm/diffHistory.md
  packages/backend/discovery/lzomnichain/polygonzkevm/discovered.json
  packages/backend/discovery/stargate/ethereum/diffHistory.md
  packages/backend/discovery/stargate/ethereum/discovered.json
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
  packages/backend/discovery/xchain/ethereum/diffHistory.md
  packages/backend/discovery/xchain/ethereum/discovered.json
  packages/config/src/projects/layer2s/abstract.ts
  packages/config/src/projects/layer2s/arenaz.ts
Labels: research

#6576 Shibarium (under review)
  packages/config/src/projects/layer2s/index.ts
  packages/config/src/projects/layer2s/shibarium.ts
  packages/config/src/test/snapshots/shibarium.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/frontend/public/icons/shibarium.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6579 Add abstract to uops explorer
  packages/uops-dashboard/src/chains.ts
Labels: research

#6597 add USDC to Soneium
  packages/backend/discovery/soneium/ethereum/diffHistory.md
  packages/backend/discovery/soneium/ethereum/discovered.json
  packages/config/src/projects/layer2s/soneium.ts
Labels: research

#6598 save swell and world tvs
  packages/config/src/projects/layer2s/swell.ts
  packages/config/src/projects/layer2s/world.ts
Labels: research

#6608 Discovery updates 01/30
  packages/backend/discovery/_templates/eigenlayer/EigenPodManager/template.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/apex/ethereum/diffHistory.md
  packages/backend/discovery/apex/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/degen/base/config.jsonc
  packages/backend/discovery/degen/base/diffHistory.md
  packages/backend/discovery/degen/base/discovered.json
  packages/backend/discovery/eigenda/ethereum/diffHistory.md
  packages/backend/discovery/eigenda/ethereum/discovered.json
  packages/backend/discovery/grvt/ethereum/diffHistory.md
  packages/backend/discovery/grvt/ethereum/discovered.json
  packages/backend/discovery/layerzerov2oft/ethereum/config.jsonc
  packages/backend/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/backend/discovery/layerzerov2oft/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/zksync2/diffHistory.md
  packages/backend/discovery/shared-zk-stack/zksync2/discovered.json
  packages/backend/discovery/witness/ethereum/diffHistory.md
  packages/backend/discovery/witness/ethereum/discovered.json
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/config/src/test/snapshots/degen.riskView.snapshot
  packages/l2b/src/commands/StarknetProgramHashes.ts
Labels: trivial-discovery

#6619 Add ternoa (full review)
  packages/backend/discovery/ternoa/ethereum/config.jsonc
  packages/backend/discovery/ternoa/ethereum/diffHistory.md
  packages/backend/discovery/ternoa/ethereum/discovered.json
  packages/config/src/projects/layer2s/polygonzkevm.ts
  packages/config/src/projects/layer2s/templates/polygonCDKStack.ts
  packages/config/src/projects/layer2s/ternoa.ts
  packages/config/src/test/constants.ts
  packages/config/src/test/snapshots/ternoa.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/frontend/public/images/architecture/astarzkevm.png
  packages/frontend/public/images/architecture/gpt.png
  packages/frontend/public/images/architecture/polygon-zkevm-rollup.png
  packages/frontend/public/images/architecture/polygon-zkevm-validium.png
  packages/frontend/public/images/architecture/wirex.png
  packages/frontend/public/images/architecture/xlayer.png
  packages/frontend/public/images/architecture/zkfair.png
Labels: research

#6596 add Sonic Gateway (full review)
  packages/backend/discovery/sonicgateway/ethereum/config.jsonc
  packages/backend/discovery/sonicgateway/ethereum/diffHistory.md
  packages/backend/discovery/sonicgateway/ethereum/discovered.json
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/projects/bridges/index.ts
  packages/config/src/projects/bridges/sonicgateway.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/discovery-types/src/Discovery.ts
  packages/discovery/schemas/contract.v2.schema.json
  packages/discovery/src/discovery/config/RawDiscoveryConfig.ts
  packages/frontend/public/icons/sonicgateway.png
  packages/frontend/public/images/architecture/sonicgateway.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6622 Add lumia (full review)
  packages/backend/discovery/lumia/ethereum/config.jsonc
  packages/backend/discovery/lumia/ethereum/diffHistory.md
  packages/backend/discovery/lumia/ethereum/discovered.json
  packages/config/src/projects/layer2s/lumia.ts
  packages/config/src/test/constants.ts
  packages/config/src/test/snapshots/lumia.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6623 fix polygon validium archi img
  packages/frontend/public/images/architecture/polygon-zkevm-validium.png
Labels: trivial, research

#6624 associate tokens with lumia, ternoa, sonicgw
  packages/config/src/projects/bridges/sonicgateway.ts
  packages/config/src/projects/layer2s/lumia.ts
  packages/config/src/projects/layer2s/ternoa.ts
Labels: trivial, research

#6633 Discovery updates 01/31
  packages/backend/discovery/blessnet/arbitrum/diffHistory.md
  packages/backend/discovery/blessnet/arbitrum/discovered.json
  packages/backend/discovery/chainport/ethereum/diffHistory.md
  packages/backend/discovery/chainport/ethereum/discovered.json
  packages/backend/discovery/gpt/ethereum/diffHistory.md
  packages/backend/discovery/gpt/ethereum/discovered.json
  packages/backend/discovery/omni/ethereum/diffHistory.md
  packages/backend/discovery/omni/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/backend/discovery/shared-zk-stack/ethereum/discovered.json
  packages/backend/discovery/silicon/ethereum/diffHistory.md
  packages/backend/discovery/silicon/ethereum/discovered.json
  packages/backend/discovery/skale-ima/ethereum/diffHistory.md
  packages/backend/discovery/skale-ima/ethereum/discovered.json
  packages/backend/discovery/sonicgateway/ethereum/config.jsonc
  packages/backend/discovery/sonicgateway/ethereum/diffHistory.md
  packages/backend/discovery/sonicgateway/ethereum/discovered.json
  packages/backend/discovery/wirex/ethereum/diffHistory.md
  packages/backend/discovery/wirex/ethereum/discovered.json
  packages/backend/discovery/xdai/ethereum/diffHistory.md
  packages/backend/discovery/xdai/ethereum/discovered.json
  packages/config/src/projects/layer2s/lyra.ts
  packages/config/src/projects/layer2s/starknet.ts
Labels: trivial-discovery
