Repository l2beat/l2beat, pull requests merged in 2025-03, with the labels that each got.

#6994 Discovery updates 03/03
  packages/config/discovery/_templates/orbitstack/Inbox/shape/Inbox_muster.sol
  packages/config/discovery/_templates/orbitstack/SequencerInbox/shape/SequencerInbox_muster.sol
  packages/config/discovery/lightlink/ethereum/diffHistory.md
  packages/config/discovery/lightlink/ethereum/discovered.json
  packages/config/discovery/muster/arbitrum/diffHistory.md
  packages/config/discovery/muster/arbitrum/discovered.json
  packages/config/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/config/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/config/discovery/soneium/ethereum/diffHistory.md
  packages/config/discovery/soneium/ethereum/discovered.json
  packages/config/src/projects/layer2s/lightlink.ts
Labels: trivial-discovery

#7023 Tokens 03/04
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6999 Clean starknet gov (discern $admin from GOVERNANCE_ADMIN)
  packages/config/discovery/_templates/shared-sharp-verifier/SHARPVerifier/template.jsonc
  packages/config/discovery/_templates/starknet/StarkgateManager/template.jsonc
  packages/config/discovery/_templates/starknet/StarkgateRegistry/template.jsonc
  packages/config/discovery/_templates/starknet/Starknet/template.jsonc
  packages/config/discovery/_templates/starknet/StarknetERC20Bridge/template.jsonc
  packages/config/discovery/_templates/starknet/StarknetEthBridge/template.jsonc
  packages/config/discovery/_templates/starknet/StarknetMultiBridge/template.jsonc
  packages/config/discovery/paradex/ethereum/diffHistory.md
  packages/config/discovery/paradex/ethereum/discovered.json
  packages/config/discovery/shared-sharp-verifier/ethereum/config.jsonc
  packages/config/discovery/shared-sharp-verifier/ethereum/diffHistory.md
  packages/config/discovery/shared-sharp-verifier/ethereum/discovered.json
  packages/config/discovery/starknet/ethereum/diffHistory.md
  packages/config/discovery/starknet/ethereum/discovered.json
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/discovery/starkware/getSHARPVerifier.ts
  packages/discovery/src/discovery/type-casters/GreaterThan.ts
Labels: research

#7024 Discovery updates 03/04
  packages/config/discovery/kinto/kinto/config.jsonc
  packages/config/discovery/kinto/kinto/diffHistory.md
  packages/config/discovery/kinto/kinto/discovered.json
  packages/config/discovery/loopring/ethereum/diffHistory.md
  packages/config/discovery/loopring/ethereum/discovered.json
  packages/config/discovery/taiko/ethereum/diffHistory.md
  packages/config/discovery/taiko/ethereum/discovered.json
Labels: trivial-discovery

#7044 Discovery updates 03/05
  packages/config/discovery/kinto/kinto/diffHistory.md
  packages/config/discovery/kinto/kinto/discovered.json
  packages/config/discovery/lumia/ethereum/diffHistory.md
  packages/config/discovery/lumia/ethereum/discovered.json
  packages/config/discovery/omni/ethereum/diffHistory.md
  packages/config/discovery/omni/ethereum/discovered.json
  packages/config/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/config/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/config/src/projects/layer2s/lumia.ts
Labels: trivial-discovery

#7057 Add Gasp under review
  packages/config/src/projects/layer2s/gasp.ts
  packages/frontend/public/icons/gasp.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#7080 add MINT native token
  packages/config/src/projects/layer2s/mint.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7076 Discovery updates 03/07
  packages/config/discovery/_templates/opstack/SystemConfig/shape/SystemConfig_v2_3_0_beta_2_soon2.sol
  packages/config/discovery/b3/base/diffHistory.md
  packages/config/discovery/b3/base/discovered.json
  packages/config/discovery/educhain/arbitrum/diffHistory.md
  packages/config/discovery/educhain/arbitrum/discovered.json
  packages/config/discovery/immutablex/ethereum/diffHistory.md
  packages/config/discovery/immutablex/ethereum/discovered.json
  packages/config/discovery/immutablezkevm/ethereum/diffHistory.md
  packages/config/discovery/immutablezkevm/ethereum/discovered.json
  packages/config/discovery/kinto/kinto/config.jsonc
  packages/config/discovery/kinto/kinto/diffHistory.md
  packages/config/discovery/kinto/kinto/discovered.json
  packages/config/discovery/lightlink/ethereum/config.jsonc
  packages/config/discovery/lightlink/ethereum/diffHistory.md
  packages/config/discovery/lightlink/ethereum/discovered.json
  packages/config/discovery/lzomnichain/arbitrum/diffHistory.md
  packages/config/discovery/lzomnichain/arbitrum/discovered.json
  packages/config/discovery/lzomnichain/base/diffHistory.md
  packages/config/discovery/lzomnichain/base/discovered.json
  packages/config/discovery/lzomnichain/ethereum/diffHistory.md
  packages/config/discovery/lzomnichain/ethereum/discovered.json
  packages/config/discovery/lzomnichain/linea/diffHistory.md
  packages/config/discovery/lzomnichain/linea/discovered.json
  packages/config/discovery/lzomnichain/optimism/diffHistory.md
  packages/config/discovery/lzomnichain/optimism/discovered.json
  packages/config/discovery/lzomnichain/polygonpos/diffHistory.md
  packages/config/discovery/lzomnichain/polygonpos/discovered.json
  packages/config/discovery/lzomnichain/polygonzkevm/diffHistory.md
  packages/config/discovery/lzomnichain/polygonzkevm/discovered.json
  packages/config/discovery/socket/ethereum/diffHistory.md
  packages/config/discovery/socket/ethereum/discovered.json
  packages/config/discovery/soneium/ethereum/diffHistory.md
  packages/config/discovery/soneium/ethereum/discovered.json
  packages/config/discovery/soon/ethereum/config.jsonc
  packages/config/discovery/soon/ethereum/diffHistory.md
  packages/config/discovery/soon/ethereum/discovered.json
  packages/config/scripts/socketcrawl/index.ts
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/layer2s/lightlink.ts
  packages/config/src/test/snapshots/educhain.riskView.snapshot
Labels: trivial-discovery

#7097 Discovery updates 03/10
  packages/config/discovery/_templates/tokens/Lido/stETH/template.jsonc
  packages/config/discovery/b3/base/diffHistory.md
  packages/config/discovery/b3/base/discovered.json
  packages/config/discovery/deversifi/ethereum/diffHistory.md
  packages/config/discovery/educhain/arbitrum/diffHistory.md
  packages/config/discovery/educhain/arbitrum/discovered.json
  packages/config/discovery/kinto/ethereum/config.jsonc
  packages/config/discovery/kinto/ethereum/diffHistory.md
  packages/config/discovery/kinto/ethereum/discovered.json
  packages/config/discovery/polygon-pos/ethereum/diffHistory.md
  packages/config/discovery/polygon-pos/ethereum/discovered.json
  packages/config/discovery/tokens/ethereum/diffHistory.md
  packages/config/discovery/tokens/ethereum/discovered.json
  packages/config/discovery/zklinknova/arbitrum/diffHistory.md
  packages/config/discovery/zklinknova/arbitrum/discovered.json
  packages/config/discovery/zklinknova/base/diffHistory.md
  packages/config/discovery/zklinknova/base/discovered.json
  packages/config/discovery/zklinknova/blast/diffHistory.md
  packages/config/discovery/zklinknova/blast/discovered.json
  packages/config/discovery/zklinknova/ethereum/diffHistory.md
  packages/config/discovery/zklinknova/ethereum/discovered.json
  packages/config/discovery/zklinknova/linea/diffHistory.md
  packages/config/discovery/zklinknova/linea/discovered.json
  packages/config/discovery/zklinknova/mantapacific/diffHistory.md
  packages/config/discovery/zklinknova/mantapacific/discovered.json
  packages/config/discovery/zklinknova/mantle/diffHistory.md
  packages/config/discovery/zklinknova/mantle/discovered.json
  packages/config/discovery/zklinknova/optimism/diffHistory.md
  packages/config/discovery/zklinknova/optimism/discovered.json
  packages/config/discovery/zklinknova/scroll/diffHistory.md
  packages/config/discovery/zklinknova/scroll/discovered.json
  packages/config/discovery/zklinknova/zksync2/diffHistory.md
  packages/config/discovery/zklinknova/zksync2/discovered.json
  packages/config/src/projects/layer2s/rhinofi.ts
  packages/config/src/test/snapshots/educhain.riskView.snapshot
  packages/config/src/test/snapshots/polygon-pos.riskView.snapshot
Labels: trivial-discovery

#7108 Discovery updates 03/11
  packages/config/discovery/_templates/opstack/zircuit/L2OutputOracle/shape/L2OutputOracle.sol
  packages/config/discovery/_templates/opstack/zircuit/L2OutputOracle/template.jsonc
  packages/config/discovery/_templates/opstack/zircuit/OptimismPortal/shape/OptimismPortal_v1_8_0_zircuit.sol
  packages/config/discovery/_templates/opstack/zircuit/OptimismPortal/template.jsonc
  packages/config/discovery/_templates/opstack/zircuit/SuperchainConfig/shape/SuperchainConfig.sol
  packages/config/discovery/_templates/opstack/zircuit/SuperchainConfig/template.jsonc
  packages/config/discovery/_templates/opstack/zircuit/Verifier/shape/VerifierV2.sol
  packages/config/discovery/_templates/opstack/zircuit/Verifier/template.jsonc
  packages/config/discovery/educhain/arbitrum/diffHistory.md
  packages/config/discovery/educhain/arbitrum/discovered.json
  packages/config/discovery/ink/ink/diffHistory.md
  packages/config/discovery/ink/ink/discovered.json
  packages/config/discovery/kroma/ethereum/config.jsonc
  packages/config/discovery/kroma/ethereum/diffHistory.md
  packages/config/discovery/kroma/ethereum/discovered.json
  packages/config/discovery/symbiosis/ethereum/config.jsonc
  packages/config/discovery/symbiosis/ethereum/diffHistory.md
  packages/config/discovery/symbiosis/ethereum/discovered.json
  packages/config/discovery/zircuit/ethereum/config.jsonc
  packages/config/discovery/zircuit/ethereum/diffHistory.md
  packages/config/discovery/zircuit/ethereum/discovered.json
  packages/config/src/templates/zkStack.ts
Labels: research

#7119 StarkEx diagram updates
  packages/config/discovery/_templates/starkex/StarkExchange/template.jsonc
  packages/config/discovery/brine/ethereum/diffHistory.md
  packages/config/discovery/brine/ethereum/discovered.json
  packages/config/discovery/canvasconnect/ethereum/diffHistory.md
  packages/config/discovery/canvasconnect/ethereum/discovered.json
  packages/config/discovery/immutablex/ethereum/diffHistory.md
  packages/config/discovery/immutablex/ethereum/discovered.json
  packages/config/discovery/layer2financezk/ethereum/diffHistory.md
  packages/config/discovery/layer2financezk/ethereum/discovered.json
  packages/config/discovery/myria/ethereum/diffHistory.md
  packages/config/discovery/myria/ethereum/discovered.json
  packages/config/discovery/reddioex/ethereum/diffHistory.md
  packages/config/discovery/reddioex/ethereum/discovered.json
  packages/config/discovery/sorare/ethereum/diffHistory.md
  packages/config/discovery/sorare/ethereum/discovered.json
  packages/config/src/discovery/descriptions.ts
  packages/config/src/projects/apex/apex.ts
  packages/config/src/projects/brine/tanx.ts
  packages/config/src/projects/deversifi/rhinofi.ts
  packages/config/src/projects/immutablex/immutablex.ts
  packages/config/src/projects/myria/myria.ts
  packages/config/src/projects/sorare/sorare.ts
  packages/discovery/schemas/contract.v2.schema.json
  packages/discovery/src/discovery/config/RawDiscoveryConfig.ts
  packages/frontend/public/images/architecture/apex.png
  packages/frontend/public/images/architecture/immutablex.png
  packages/frontend/public/images/architecture/myria.png
  packages/frontend/public/images/architecture/rhinofi.png
  packages/frontend/public/images/architecture/sorare.png
  packages/frontend/public/images/architecture/starkex.png
  packages/frontend/public/images/architecture/tanx.png
Labels: research

#7130 Discovery updates 03/12
  packages/config/discovery/_templates/opstack/zircuit/L2OutputOracle/template.jsonc
  packages/config/discovery/_templates/shared-zk-stack/ProtocolUpgradeHandler/template.jsonc
  packages/config/discovery/educhain/arbitrum/config.jsonc
  packages/config/discovery/educhain/arbitrum/diffHistory.md
  packages/config/discovery/educhain/arbitrum/discovered.json
  packages/config/discovery/parallel/ethereum/diffHistory.md
  packages/config/discovery/parallel/ethereum/discovered.json
  packages/config/discovery/scroll/ethereum/diffHistory.md
  packages/config/discovery/scroll/ethereum/discovered.json
  packages/config/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/config/discovery/shared-zk-stack/ethereum/discovered.json
  packages/config/discovery/zircuit/ethereum/config.jsonc
  packages/config/discovery/zircuit/ethereum/diffHistory.md
  packages/config/discovery/zircuit/ethereum/discovered.json
  packages/config/discovery/zksync2/ethereum/diffHistory.md
  packages/config/discovery/zksync2/ethereum/discovered.json
  packages/config/src/projects/zircuit/zircuit.ts
  packages/frontend/public/images/upgrades-and-governance/arbitrum.png
Labels: research

#7155 do not subtract count for Zircuit activity
  packages/config/src/processing/layer2s.test.ts
  packages/config/src/projects/zircuit/zircuit.ts
Labels: research

#7153 ZKsync upgrade v26 step 1.5 (diamond upgrade)
  packages/config/src/projects/_templates/shared-zk-stack/Diamond_v26/shape/AdminFacet.1.sol
  packages/config/src/projects/_templates/shared-zk-stack/Diamond_v26/shape/DiamondProxy.p.sol
  packages/config/src/projects/_templates/shared-zk-stack/Diamond_v26/shape/ExecutorFacet.4.sol
  packages/config/src/projects/_templates/shared-zk-stack/Diamond_v26/shape/GettersFacet.2.sol
  packages/config/src/projects/_templates/shared-zk-stack/Diamond_v26/shape/MailboxFacet.3.sol
  packages/config/src/projects/_templates/shared-zk-stack/Diamond_v26/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/RollupL1DAValidator/shape/RollupL1DAValidator.sol
  packages/config/src/projects/_templates/shared-zk-stack/RollupL1DAValidator/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/ValidatorTimelock/shape/ValidatorTimelock_v26.sol
  packages/config/src/projects/_templates/shared-zk-stack/Verifier/shape/Verifier_v26.sol
  packages/config/src/projects/zksync2/ethereum/config.jsonc
  packages/config/src/projects/zksync2/ethereum/diffHistory.md
  packages/config/src/projects/zksync2/ethereum/discovered.json
  packages/config/src/projects/zksync2/zksync2.ts
  packages/discovery/src/discovery/handlers/user/ZKsyncEraValidatorsHandler.ts
Labels: research

#7177 add canonical USDC to sxnetwork
  packages/config/src/projects/sxnetwork/ethereum/config.jsonc
  packages/config/src/projects/sxnetwork/ethereum/diffHistory.md
  packages/config/src/projects/sxnetwork/ethereum/discovered.json
  packages/config/src/projects/sxnetwork/sxnetwork.ts
Labels: research

#7176 Everclear bridge in review (+tvs)
  packages/backend/src/config/features/updateMonitor.ts
  packages/config/src/common/explorerUrls.ts
  packages/config/src/processing/bridges.ts
  packages/config/src/projects/everclear/everclear.ts
  packages/config/src/projects/everclearbridge/ethereum/config.jsonc
  packages/config/src/projects/everclearbridge/ethereum/diffHistory.md
  packages/config/src/projects/everclearbridge/ethereum/discovered.json
  packages/config/src/projects/everclearbridge/everclear/config.jsonc
  packages/config/src/projects/everclearbridge/everclear/diffHistory.md
  packages/config/src/projects/everclearbridge/everclear/discovered.json
  packages/config/src/projects/everclearbridge/everclearbridge.ts
  packages/config/src/test/multicall.test.ts
  packages/discovery/schemas/config.v2.schema.json
  packages/discovery/src/config/chains.ts
  packages/frontend/public/icons/everclearbridge.png
  packages/frontend/scripts/logos/tinifiedLogos.json
  packages/protocolbeat/src/panel-values/explorers.ts
Labels: research

#7183 add new zircuit trackedTxs
  packages/config/src/processing/getProjects.test.ts
  packages/config/src/projects/zircuit/zircuit.ts
Labels: research

#7191 Arbitrum l2 sc-manager disco config
  packages/config/src/projects/_templates/orbitstack/layer2/CoreGovernor/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2ARBGateway/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2DAIGateway/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2ERC20Gateway/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2GatewayRouter/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2LPTGateway/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2Timelock/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2UpgradeExecutor/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/L2WethGateway/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilManager/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilMemberElectionGovernor/shape/SecurityCouncilMemberElectionGovernor.sol
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilMemberElectionGovernor/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilMemberRemovalGovernor/shape/SecurityCouncilMemberRemovalGovernor.sol
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilMemberRemovalGovernor/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilNomineeElectionGovernor/shape/SecurityCouncilNomineeElectionGovernor.sol
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilNomineeElectionGovernor/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/TreasuryGovernor/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/TreasuryTimelock/template.jsonc
  packages/config/src/projects/arbitrum/arbitrum/diffHistory.md
  packages/config/src/projects/arbitrum/arbitrum/discovered.json
  packages/config/src/projects/nova/nova/diffHistory.md
  packages/config/src/projects/nova/nova/discovered.json
Labels: research

#7200 Discovery updates 03/18
  packages/config/src/projects/donatuz/base/diffHistory.md
  packages/config/src/projects/donatuz/base/discovered.json
  packages/config/src/projects/ink/ethereum/diffHistory.md
  packages/config/src/projects/ink/ethereum/discovered.json
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/linea/ethereum/diffHistory.md
  packages/config/src/projects/linea/ethereum/discovered.json
  packages/config/src/projects/linea/linea.ts
  packages/config/src/projects/shape/ethereum/diffHistory.md
  packages/config/src/projects/shape/ethereum/discovered.json
  packages/config/src/projects/shared-polygon-cdk/ethereum/diffHistory.md
  packages/config/src/projects/shared-polygon-cdk/ethereum/discovered.json
  packages/config/src/projects/shared-polygon-cdk/ethereum/l2b-fetchagg_output.json
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/stack/base/diffHistory.md
  packages/config/src/projects/stack/base/discovered.json
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/l2b/src/commands/FetchAggLayer.ts
  packages/l2b/src/implementations/fetchAgglayer.ts
Labels: research

#7204 Fix function signature for zksync era tracked txs
  packages/config/src/projects/zksync2/zksync2.ts
Labels: research

#7209 add `l2b fetchzkstack` command to decode zk stack cluster of l2s
  packages/config/src/projects/shared-polygon-cdk/ethereum/l2b-fetchagg_output.json
  packages/config/src/projects/shared-zk-stack/ethereum/l2b-fetchzkstack_output.json
  packages/l2b/src/commands/FetchZkStack.ts
  packages/l2b/src/commands/index.ts
  packages/l2b/src/implementations/fetchAgglayer.ts
  packages/l2b/src/implementations/fetchZkStack.ts
Labels: research

#7218 rm celo/opticsV2 discovery
  packages/config/src/projects/opticsV2/celo/config.jsonc
  packages/config/src/projects/opticsV2/celo/diffHistory.md
  packages/config/src/projects/opticsV2/celo/discovered.json
Labels: research

#7225 Update bridge links
  packages/config/src/projects/openzk/openzk.ts
Labels: trivial

#7224 Kinto rerereview
  packages/config/src/common/explorerUrls.ts
  packages/config/src/projects/kinto/kinto.ts
  packages/config/src/projects/kinto/kinto/config.jsonc
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
Labels: research

#7241 Discovery updates 03/21
  packages/config/src/projects/bob/ethereum/diffHistory.md
  packages/config/src/projects/bob/ethereum/discovered.json
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/kroma/ethereum/diffHistory.md
  packages/config/src/projects/kroma/ethereum/discovered.json
  packages/config/src/projects/layerzerov2oft/ethereum/diffHistory.md
  packages/config/src/projects/layerzerov2oft/ethereum/discovered.json
  packages/config/src/projects/mantle/mantle.ts
  packages/config/src/projects/polygon-pos/ethereum/diffHistory.md
  packages/config/src/projects/polygon-pos/ethereum/discovered.json
  packages/config/src/projects/shared-polygon-cdk/ethereum/diffHistory.md
  packages/config/src/projects/shared-polygon-cdk/ethereum/discovered.json
  packages/config/src/projects/shared-polygon-cdk/ethereum/l2b-fetchagg_output.json
  packages/config/src/projects/shared-zk-stack/ethereum/l2b-fetchzkstack_output.json
  packages/config/src/projects/unichain/ethereum/diffHistory.md
  packages/config/src/projects/unichain/ethereum/discovered.json
  packages/config/src/projects/zklinknova/linea/config.jsonc
  packages/config/src/projects/zklinknova/linea/diffHistory.md
  packages/config/src/projects/zklinknova/linea/discovered.json
  packages/config/src/test/snapshots/polygon-pos.riskView.snapshot
  packages/frontend/public/images/architecture/opstack-optimium.png
  packages/l2b/src/implementations/fetchZkStack.ts
Labels: trivial-discovery

#7251 kinto stage under review
  packages/config/src/projects/kinto/kinto.ts
Labels: research

#7250 Kinto script update (add role section and output for diffing)
  packages/l2b/src/implementations/scan-kinto-am/ScanKintoAmImpl.ts
  packages/l2b/src/implementations/scan-kinto-am/scankintoam_out.txt
Labels: research

#7271 Discovery updates 03/25
  packages/config/src/projects/_templates/orbitstack/Bridge/shape/ERC20Bridge_decimals.sol
  packages/config/src/projects/_templates/orbitstack/Inbox/shape/ERC20Inbox_decimals-7702.sol
  packages/config/src/projects/_templates/shared-zk-stack/Diamond_v26/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/L1AssetRouter/shape/L1AssetRouter.sol
  packages/config/src/projects/_templates/shared-zk-stack/L1AssetRouter/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/L1NativeTokenVault/shape/L1NativeTokenVault.sol
  packages/config/src/projects/_templates/shared-zk-stack/L1NativeTokenVault/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/ValidiumL1DAValidator/shape/ValidiumL1DAValidator.sol
  packages/config/src/projects/_templates/shared-zk-stack/ValidiumL1DAValidator/template.jsonc
  packages/config/src/projects/_templates/starknet/Starknet/shape/Starknet_v2025-10.sol
  packages/config/src/projects/alephzero/ethereum/diffHistory.md
  packages/config/src/projects/alephzero/ethereum/discovered.json
  packages/config/src/projects/educhain/arbitrum/diffHistory.md
  packages/config/src/projects/educhain/arbitrum/discovered.json
  packages/config/src/projects/everclear/ethereum/diffHistory.md
  packages/config/src/projects/everclear/ethereum/discovered.json
  packages/config/src/projects/fluence/ethereum/diffHistory.md
  packages/config/src/projects/fluence/ethereum/discovered.json
  packages/config/src/projects/grvt/ethereum/config.jsonc
  packages/config/src/projects/grvt/ethereum/diffHistory.md
  packages/config/src/projects/grvt/ethereum/discovered.json
  packages/config/src/projects/grvt/grvt.ts
  packages/config/src/projects/hyperlane/ethereum/config.jsonc
  packages/config/src/projects/hyperlane/ethereum/diffHistory.md
  packages/config/src/projects/hyperlane/ethereum/discovered.json
  packages/config/src/projects/kinto/kinto/config.jsonc
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/omni/ethereum/diffHistory.md
  packages/config/src/projects/omni/ethereum/discovered.json
  packages/config/src/projects/playblock/nova/diffHistory.md
  packages/config/src/projects/playblock/nova/discovered.json
  packages/config/src/projects/polygon-pos/ethereum/diffHistory.md
  packages/config/src/projects/polygon-pos/ethereum/discovered.json
  packages/config/src/projects/real/ethereum/diffHistory.md
  packages/config/src/projects/real/ethereum/discovered.json
  packages/config/src/projects/reya/ethereum/diffHistory.md
  packages/config/src/projects/reya/ethereum/discovered.json
  packages/config/src/projects/scroll/ethereum/diffHistory.md
  packages/config/src/projects/scroll/ethereum/discovered.json
  packages/config/src/projects/scroll/scroll.ts
  packages/config/src/projects/shared-zk-stack/ethereum/config.jsonc
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/sxnetwork/ethereum/diffHistory.md
  packages/config/src/projects/sxnetwork/ethereum/discovered.json
  packages/config/src/projects/tokens/ethereum/diffHistory.md
  packages/config/src/projects/tokens/ethereum/discovered.json
  packages/config/src/projects/zeronetwork/ethereum/config.jsonc
  packages/config/src/projects/zeronetwork/ethereum/diffHistory.md
  packages/config/src/projects/zeronetwork/ethereum/discovered.json
  packages/config/src/projects/zksync2/ethereum/diffHistory.md
  packages/config/src/projects/zksync2/ethereum/discovered.json
  packages/config/src/test/snapshots/polygon-pos.riskView.snapshot
Labels: research

#7295 add more celo tokens, use totalsupply for cTokens
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7258 Unreview kinto and add u g section
  packages/config/src/projects/arbitrum/arbitrum.ts
  packages/config/src/projects/aztec/aztec.ts
  packages/config/src/projects/degate3/degate3.ts
  packages/config/src/projects/fuelv1/fuelv1.ts
  packages/config/src/projects/ink/ink.ts
  packages/config/src/projects/kinto/ethereum/diffHistory.md
  packages/config/src/projects/kinto/ethereum/discovered.json
  packages/config/src/projects/kinto/kinto.ts
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/optimism/optimism.ts
  packages/config/src/projects/unichain/unichain.ts
  packages/config/src/test/snapshots/kinto.riskView.snapshot
  packages/config/src/types.ts
  packages/frontend/public/images/upgrades-and-governance/kinto.png
  packages/frontend/src/components/projects/sections/scope-of-assessment.tsx
Labels: research

#7309 Discovery updates 03/28
  packages/config/src/projects/abstract/ethereum/config.jsonc
  packages/config/src/projects/abstract/ethereum/diffHistory.md
  packages/config/src/projects/abstract/ethereum/discovered.json
  packages/config/src/projects/cronoszkevm/cronoszkevm.ts
  packages/config/src/projects/cronoszkevm/ethereum/config.jsonc
  packages/config/src/projects/cronoszkevm/ethereum/diffHistory.md
  packages/config/src/projects/cronoszkevm/ethereum/discovered.json
  packages/config/src/projects/kinto/kinto/config.jsonc
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/sophon/ethereum/config.jsonc
  packages/config/src/projects/sophon/ethereum/diffHistory.md
  packages/config/src/projects/sophon/ethereum/discovered.json
  packages/config/src/projects/sophon/sophon.ts
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/treasure/ethereum/config.jsonc
  packages/config/src/projects/treasure/ethereum/diffHistory.md
  packages/config/src/projects/treasure/ethereum/discovered.json
  packages/config/src/projects/treasure/treasure.ts
Labels: trivial-discovery
