Repository l2beat/l2beat, pull requests merged in 2025-02, with the labels that each got.

#6644 Remove starknet EOA warn
  packages/config/src/projects/layer2s/starknet.ts
Labels: research

#6656 Update stark governance review to reflect EOAs removal
  packages/backend/discovery/brine/ethereum/config.jsonc
  packages/backend/discovery/brine/ethereum/diffHistory.md
  packages/backend/discovery/brine/ethereum/discovered.json
  packages/backend/discovery/shared-sharp-verifier/ethereum/config.jsonc
  packages/backend/discovery/shared-sharp-verifier/ethereum/diffHistory.md
  packages/backend/discovery/shared-sharp-verifier/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/config.jsonc
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/config/src/discovery/starkware/getSHARPVerifier.ts
  packages/config/src/projects/layer2s/starknet.ts
  packages/frontend/public/images/upgrades-and-governance/starknet.png
Labels: research

#6659 Discovery updates 02/03
  packages/backend/discovery/_templates/shared-zk-stack/Diamond/template.jsonc
  packages/backend/discovery/abstract/ethereum/diffHistory.md
  packages/backend/discovery/abstract/ethereum/discovered.json
  packages/backend/discovery/cronoszkevm/ethereum/diffHistory.md
  packages/backend/discovery/cronoszkevm/ethereum/discovered.json
  packages/backend/discovery/edgeless/ethereum/config.jsonc
  packages/backend/discovery/edgeless/ethereum/diffHistory.md
  packages/backend/discovery/edgeless/ethereum/discovered.json
  packages/backend/discovery/grvt/ethereum/diffHistory.md
  packages/backend/discovery/grvt/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/zksync2/diffHistory.md
  packages/backend/discovery/shared-zk-stack/zksync2/discovered.json
  packages/backend/discovery/silicon/ethereum/diffHistory.md
  packages/backend/discovery/silicon/ethereum/discovered.json
  packages/backend/discovery/sonicgateway/ethereum/diffHistory.md
  packages/backend/discovery/sonicgateway/ethereum/discovered.json
  packages/backend/discovery/sophon/ethereum/diffHistory.md
  packages/backend/discovery/sophon/ethereum/discovered.json
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
  packages/backend/discovery/ternoa/ethereum/config.jsonc
  packages/backend/discovery/ternoa/ethereum/diffHistory.md
  packages/backend/discovery/ternoa/ethereum/discovered.json
  packages/backend/discovery/treasure/ethereum/diffHistory.md
  packages/backend/discovery/treasure/ethereum/discovered.json
  packages/backend/discovery/wirex/ethereum/diffHistory.md
  packages/backend/discovery/wirex/ethereum/discovered.json
  packages/backend/discovery/zeronetwork/ethereum/diffHistory.md
  packages/backend/discovery/zeronetwork/ethereum/discovered.json
  packages/backend/discovery/zksync2/ethereum/diffHistory.md
  packages/backend/discovery/zksync2/ethereum/discovered.json
  packages/config/src/test/snapshots/abstract.riskView.snapshot
  packages/config/src/test/snapshots/cronoszkevm.riskView.snapshot
  packages/config/src/test/snapshots/grvt.riskView.snapshot
  packages/config/src/test/snapshots/sophon.riskView.snapshot
  packages/config/src/test/snapshots/treasure.riskView.snapshot
  packages/config/src/test/snapshots/zeronetwork.riskView.snapshot
  packages/config/src/test/snapshots/zksync2.riskView.snapshot
Labels: research

#6677 Soneium: add lido bridge
  packages/backend/discovery/soneium/ethereum/config.jsonc
  packages/backend/discovery/soneium/ethereum/diffHistory.md
  packages/backend/discovery/soneium/ethereum/discovered.json
  packages/config/src/projects/layer2s/soneium.ts
Labels: research

#6679 discodrive last opstacks
  packages/backend/discovery/_templates/global/ProxyAdmin/shape/ProxyAdmin_zircuit.sol
  packages/backend/discovery/_templates/opstack/OptimismMintableERC20Factory/shape/OptimismMintableERC20Factory_v1_9_0_zircuit.sol
  packages/backend/discovery/_templates/opstack/SuperchainConfig_zircuit/shape/SuperchainConfig.sol
  packages/backend/discovery/_templates/opstack/SuperchainConfig_zircuit/template.jsonc
  packages/backend/discovery/ancient/ethereum/config.jsonc
  packages/backend/discovery/ancient/ethereum/diffHistory.md
  packages/backend/discovery/ancient/ethereum/discovered.json
  packages/backend/discovery/zircuit/ethereum/config.jsonc
  packages/backend/discovery/zircuit/ethereum/diffHistory.md
  packages/backend/discovery/zircuit/ethereum/discovered.json
  packages/config/src/projects/layer2s/ancient.ts
  packages/config/src/projects/layer2s/zircuit.ts
Labels: research

#6682 Add Espresso sequencing badge
  packages/config/src/projects/badges/index.ts
  packages/frontend/public/images/badges/EspressoSequencing.png
Labels: trivial

#6684 Discovery updates 02/05
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/blessnet/arbitrum/diffHistory.md
  packages/backend/discovery/blessnet/arbitrum/discovered.json
  packages/backend/discovery/hermez/ethereum/config.jsonc
  packages/backend/discovery/hermez/ethereum/diffHistory.md
  packages/backend/discovery/hermez/ethereum/discovered.json
  packages/backend/discovery/shape/ethereum/diffHistory.md
  packages/backend/discovery/shape/ethereum/discovered.json
  packages/backend/discovery/sophon/ethereum/diffHistory.md
  packages/backend/discovery/sophon/ethereum/discovered.json
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/config.jsonc
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/treasure/ethereum/diffHistory.md
  packages/backend/discovery/treasure/ethereum/discovered.json
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/backend/discovery/xdai/ethereum/config.jsonc
  packages/backend/discovery/xdai/ethereum/diffHistory.md
  packages/backend/discovery/xdai/ethereum/discovered.json
  packages/config/src/common/stateDerivations.ts
  packages/config/src/projects/layer2s/hashkey.ts
  packages/config/src/projects/layer2s/shape.ts
  packages/config/src/projects/layer2s/sophon.ts
  packages/config/src/projects/layer2s/starknet.ts
  packages/config/src/projects/layer2s/treasure.ts
  packages/config/src/test/snapshots/shape.riskView.snapshot
Labels: research

#6672 polygon cdk: chains without full state proofs can join agglayer
  packages/backend/discovery/_templates/polygon-cdk/PolygonRollupManager_pessimistic/shape/PolygonRollupManager_pessimistic.sol
  packages/backend/discovery/_templates/polygon-cdk/PolygonRollupManager_pessimistic/template.jsonc
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/projects/layer2s/templates/polygonCDKStack.ts
  packages/config/src/test/snapshots/astarzkevm.riskView.snapshot
  packages/config/src/test/snapshots/gpt.riskView.snapshot
  packages/config/src/test/snapshots/lumia.riskView.snapshot
  packages/config/src/test/snapshots/polygonzkevm.riskView.snapshot
  packages/config/src/test/snapshots/silicon.riskView.snapshot
  packages/config/src/test/snapshots/ternoa.riskView.snapshot
  packages/config/src/test/snapshots/wirex.riskView.snapshot
  packages/config/src/test/snapshots/witness.riskView.snapshot
  packages/config/src/test/snapshots/xlayer.riskView.snapshot
Labels: research

#6714 define kinto and arbitrum sc member names as common
  packages/backend/discovery/arbitrum/ethereum/diffHistory.md
  packages/backend/discovery/arbitrum/ethereum/discovered.json
  packages/backend/discovery/commonAddressNames.jsonc
  packages/backend/discovery/kinto/ethereum/config.jsonc
  packages/backend/discovery/kinto/ethereum/diffHistory.md
  packages/backend/discovery/kinto/ethereum/discovered.json
  packages/backend/discovery/nova/ethereum/diffHistory.md
  packages/backend/discovery/nova/ethereum/discovered.json
Labels: research

#6709 Discovery updates 02/06
  packages/backend/discovery/_templates/polygon-cdk/PolygonRollupManager_pessimistic/template.jsonc
  packages/backend/discovery/across-v3/ethereum/diffHistory.md
  packages/backend/discovery/across-v3/ethereum/discovered.json
  packages/backend/discovery/arenaz/ethereum/diffHistory.md
  packages/backend/discovery/arenaz/ethereum/discovered.json
  packages/backend/discovery/base/ethereum/diffHistory.md
  packages/backend/discovery/base/ethereum/discovered.json
  packages/backend/discovery/eigenda/ethereum/diffHistory.md
  packages/backend/discovery/eigenda/ethereum/discovered.json
  packages/backend/discovery/ink/ethereum/diffHistory.md
  packages/backend/discovery/ink/ethereum/discovered.json
  packages/backend/discovery/kinto/kinto/config.jsonc
  packages/backend/discovery/kinto/kinto/diffHistory.md
  packages/backend/discovery/kinto/kinto/discovered.json
  packages/backend/discovery/metal/ethereum/diffHistory.md
  packages/backend/discovery/metal/ethereum/discovered.json
  packages/backend/discovery/mode/ethereum/diffHistory.md
  packages/backend/discovery/mode/ethereum/discovered.json
  packages/backend/discovery/optimism/ethereum/diffHistory.md
  packages/backend/discovery/optimism/ethereum/discovered.json
  packages/backend/discovery/shape/ethereum/config.jsonc
  packages/backend/discovery/shape/ethereum/diffHistory.md
  packages/backend/discovery/shape/ethereum/discovered.json
  packages/backend/discovery/shared-eigenlayer/ethereum/diffHistory.md
  packages/backend/discovery/shared-eigenlayer/ethereum/discovered.json
  packages/backend/discovery/shared-polygon-cdk/ethereum/diffHistory.md
  packages/backend/discovery/shared-polygon-cdk/ethereum/discovered.json
  packages/backend/discovery/shared-zk-stack/zksync2/diffHistory.md
  packages/backend/discovery/shared-zk-stack/zksync2/discovered.json
  packages/backend/discovery/soneium/ethereum/diffHistory.md
  packages/backend/discovery/soneium/ethereum/discovered.json
  packages/backend/discovery/sophon/ethereum/diffHistory.md
  packages/backend/discovery/sophon/ethereum/discovered.json
  packages/backend/discovery/stargatev2/ethereum/diffHistory.md
  packages/backend/discovery/stargatev2/ethereum/discovered.json
  packages/backend/discovery/starknet/ethereum/config.jsonc
  packages/backend/discovery/starknet/ethereum/diffHistory.md
  packages/backend/discovery/starknet/ethereum/discovered.json
  packages/backend/discovery/swell/ethereum/diffHistory.md
  packages/backend/discovery/swell/ethereum/discovered.json
  packages/backend/discovery/treasure/ethereum/diffHistory.md
  packages/backend/discovery/treasure/ethereum/discovered.json
  packages/backend/discovery/worldchain/ethereum/diffHistory.md
  packages/backend/discovery/worldchain/ethereum/discovered.json
  packages/backend/discovery/zora/ethereum/diffHistory.md
  packages/backend/discovery/zora/ethereum/discovered.json
  packages/config/src/projects/layer2s/starknet.ts
Labels: research

#6716 switch USDT on arbitrum from external-canonical to external-totalSupply
  packages/config/src/projects/layer2s/arbitrum.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6724 Add hyperlane nexus bridge (full review)
  packages/backend/discovery/_templates/hyperlane/HypERC20Collateral/shape/HypERC20Collateral.sol
  packages/backend/discovery/_templates/hyperlane/HypERC20Collateral/template.jsonc
  packages/backend/discovery/_templates/hyperlane/StaticAggregationIsm/shape/StaticAggregationIsm.sol
  packages/backend/discovery/_templates/hyperlane/StaticAggregationIsm/template.jsonc
  packages/backend/discovery/hyperlane/ethereum/config.jsonc
  packages/backend/discovery/hyperlane/ethereum/diffHistory.md
  packages/backend/discovery/hyperlane/ethereum/discovered.json
  packages/config/src/discovery/ProjectDiscovery.ts
  packages/config/src/projects/bridges/hyperlane.ts
  packages/config/src/projects/bridges/index.ts
  packages/discovery-types/src/Discovery.ts
  packages/discovery/schemas/contract.v2.schema.json
  packages/discovery/src/discovery/config/RawDiscoveryConfig.ts
  packages/frontend/public/icons/hyperlane.png
  packages/frontend/public/images/architecture/hyperlane.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#6734 add USDM, USDN to zksync era
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6732 update hyperlane multisig descriptions
  packages/config/discovery/hyperlane/ethereum/config.jsonc
  packages/config/discovery/hyperlane/ethereum/diffHistory.md
  packages/config/discovery/hyperlane/ethereum/discovered.json
  packages/config/src/projects/bridges/hyperlane.ts
Labels: research

#6737 new polygon cdk archi diagrams (agglayer)
  packages/config/src/projects/layer2s/polygonzkevm.ts
  packages/config/src/projects/layer2s/templates/polygonCDKStack.ts
  packages/frontend/public/images/architecture/polygon-cdk-rollup.png
  packages/frontend/public/images/architecture/polygon-cdk-validium.png
  packages/frontend/public/images/architecture/polygon-zkevm-rollup.png
  packages/frontend/public/images/architecture/polygon-zkevm-validium.png
  packages/frontend/public/images/architecture/polygonzkevm.png
Labels: research

#6759 Discovery updates 02/12
  packages/config/discovery/_templates/opstack/L1StandardBridge/shape/L1StandardBridge_v2_1_0_zircuit_nothrottle.sol
  packages/config/discovery/_templates/opstack/L2OutputOracle/shape/L2OutputOracle_v1_4_0_zircuit_getorf.sol
  packages/config/discovery/_templates/opstack/OptimismPortal/shape/OptimismPortal_v2_0_2.sol
  packages/config/discovery/_templates/opstack/OptimismPortal_soon/shape/OptimismPortal_v2_1_8_beta1_censor.sol
  packages/config/discovery/_templates/opstack/OptimismPortal_soon/template.jsonc
  packages/config/discovery/arenaz/ethereum/diffHistory.md
  packages/config/discovery/arenaz/ethereum/discovered.json
  packages/config/discovery/base/ethereum/diffHistory.md
  packages/config/discovery/base/ethereum/discovered.json
  packages/config/discovery/blessnet/arbitrum/config.jsonc
  packages/config/discovery/blessnet/arbitrum/diffHistory.md
  packages/config/discovery/blessnet/arbitrum/discovered.json
  packages/config/discovery/ink/ethereum/diffHistory.md
  packages/config/discovery/ink/ethereum/discovered.json
  packages/config/discovery/kinto/kinto/diffHistory.md
  packages/config/discovery/kinto/kinto/discovered.json
  packages/config/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/config/discovery/layerzerov2oft/ethereum/discovered.json
  packages/config/discovery/metal/ethereum/diffHistory.md
  packages/config/discovery/metal/ethereum/discovered.json
  packages/config/discovery/mode/ethereum/diffHistory.md
  packages/config/discovery/mode/ethereum/discovered.json
  packages/config/discovery/optimism/ethereum/diffHistory.md
  packages/config/discovery/optimism/ethereum/discovered.json
  packages/config/discovery/shape/ethereum/diffHistory.md
  packages/config/discovery/shape/ethereum/discovered.json
  packages/config/discovery/soneium/ethereum/diffHistory.md
  packages/config/discovery/soneium/ethereum/discovered.json
  packages/config/discovery/soon/ethereum/diffHistory.md
  packages/config/discovery/soon/ethereum/discovered.json
  packages/config/discovery/stargatev2/ethereum/diffHistory.md
  packages/config/discovery/stargatev2/ethereum/discovered.json
  packages/config/discovery/starknet/ethereum/diffHistory.md
  packages/config/discovery/starknet/ethereum/discovered.json
  packages/config/discovery/swell/ethereum/diffHistory.md
  packages/config/discovery/swell/ethereum/discovered.json
  packages/config/discovery/unichain/ethereum/diffHistory.md
  packages/config/discovery/unichain/ethereum/discovered.json
  packages/config/discovery/worldchain/ethereum/diffHistory.md
  packages/config/discovery/worldchain/ethereum/discovered.json
  packages/config/discovery/zircuit/ethereum/config.jsonc
  packages/config/discovery/zircuit/ethereum/diffHistory.md
  packages/config/discovery/zircuit/ethereum/discovered.json
  packages/config/discovery/zora/ethereum/diffHistory.md
  packages/config/discovery/zora/ethereum/discovered.json
  packages/config/src/projects/layer2s/starknet.ts
  packages/config/src/projects/layer2s/unichain.ts
  packages/config/src/projects/layer3s/blessnet.ts
Labels: research

#6782 add unichain usdc, associate UNI and WLD
  packages/config/src/projects/layer2s/unichain.ts
  packages/config/src/projects/layer2s/world.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6790 Discovery updates 02/14
  packages/config/discovery/base/ethereum/diffHistory.md
  packages/config/discovery/base/ethereum/discovered.json
  packages/config/discovery/fraxferry/ethereum/diffHistory.md
  packages/config/discovery/fraxferry/ethereum/discovered.json
  packages/config/discovery/lzomnichain/linea/diffHistory.md
  packages/config/discovery/lzomnichain/linea/discovered.json
  packages/config/discovery/lzomnichain/polygonzkevm/diffHistory.md
  packages/config/discovery/lzomnichain/polygonzkevm/discovered.json
  packages/config/discovery/mantle/ethereum/diffHistory.md
  packages/config/discovery/mantle/ethereum/discovered.json
  packages/config/discovery/phala/ethereum/config.jsonc
  packages/config/discovery/phala/ethereum/diffHistory.md
  packages/config/discovery/phala/ethereum/discovered.json
  packages/config/discovery/stargatev2/arbitrum/diffHistory.md
  packages/config/discovery/stargatev2/arbitrum/discovered.json
  packages/config/discovery/stargatev2/base/diffHistory.md
  packages/config/discovery/stargatev2/base/discovered.json
  packages/config/discovery/stargatev2/ethereum/diffHistory.md
  packages/config/discovery/stargatev2/ethereum/discovered.json
  packages/config/discovery/stargatev2/linea/diffHistory.md
  packages/config/discovery/stargatev2/linea/discovered.json
  packages/config/discovery/stargatev2/mantle/diffHistory.md
  packages/config/discovery/stargatev2/mantle/discovered.json
  packages/config/discovery/stargatev2/metis/diffHistory.md
  packages/config/discovery/stargatev2/metis/discovered.json
  packages/config/discovery/stargatev2/optimism/diffHistory.md
  packages/config/discovery/stargatev2/optimism/discovered.json
  packages/config/discovery/stargatev2/scroll/diffHistory.md
  packages/config/discovery/stargatev2/scroll/discovered.json
  packages/config/discovery/taiko/ethereum/config.jsonc
  packages/config/discovery/taiko/ethereum/diffHistory.md
  packages/config/discovery/taiko/ethereum/discovered.json
  packages/config/discovery/winr/arbitrum/config.jsonc
  packages/config/discovery/winr/arbitrum/diffHistory.md
  packages/config/discovery/winr/arbitrum/discovered.json
  packages/config/discovery/worldcoin/ethereum/diffHistory.md
  packages/config/discovery/worldcoin/ethereum/discovered.json
  packages/config/src/projects/bridges/fraxferry.ts
  packages/config/src/projects/layer2s/taiko.ts
  packages/config/src/test/snapshots/winr.riskView.snapshot
Labels: research

#6743 Kroma upgrade: optional SP1 for fault proofs
  packages/config/discovery/_templates/global/ProxyAdmin/shape/ProxyAdmin_kroma.sol
  packages/config/discovery/_templates/global/Timelock/shape/TimeLock.sol
  packages/config/discovery/_templates/global/Timelock/template.jsonc
  packages/config/discovery/_templates/opstack/L1CrossDomainMessenger/shape/L1CrossDomainMessenger_v1_0_0.sol
  packages/config/discovery/_templates/opstack/L1ERC721Bridge/shape/L1ERC721Bridge_v1_0_0.sol
  packages/config/discovery/_templates/opstack/L1StandardBridge/shape/L1StandardBridge_v1_0_0_kroma.sol
  packages/config/discovery/_templates/opstack/SystemConfig/shape/SystemConfig_v1_0_0.sol
  packages/config/discovery/_templates/succinct/SP1SuccinctGateway/template.jsonc
  packages/config/discovery/blobstream/arbitrum/config.jsonc
  packages/config/discovery/blobstream/arbitrum/diffHistory.md
  packages/config/discovery/blobstream/arbitrum/discovered.json
  packages/config/discovery/blobstream/base/diffHistory.md
  packages/config/discovery/blobstream/base/discovered.json
  packages/config/discovery/blobstream/ethereum/diffHistory.md
  packages/config/discovery/blobstream/ethereum/discovered.json
  packages/config/discovery/commonAddressNames.jsonc
  packages/config/discovery/kroma/ethereum/config.jsonc
  packages/config/discovery/kroma/ethereum/diffHistory.md
  packages/config/discovery/kroma/ethereum/discovered.json
  packages/config/discovery/phala/ethereum/diffHistory.md
  packages/config/discovery/phala/ethereum/discovered.json
  packages/config/discovery/vector/ethereum/diffHistory.md
  packages/config/discovery/vector/ethereum/discovered.json
  packages/config/src/projects/layer2s/kroma.ts
  packages/config/src/test/discovery/config.test.ts
  packages/config/src/test/snapshots/kroma.riskView.snapshot
  packages/frontend/public/images/architecture/kroma.png
Labels: research

#6798 fix some formatting
  packages/config/src/projects/layer2s/templates/orbitStack.ts
  packages/config/src/projects/layer2s/templates/polygonCDKStack.ts
Labels: research

#6833 Tokens 02/18 (yay, stone)
  packages/config/src/projects/layer2s/soneium.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6825 Discovery updates 02/18
  packages/config/discovery/_templates/circle/L1OrbitUSDCGateway/shape/L1OrbitUSDCGateway.sol
  packages/config/discovery/_templates/circle/L1OrbitUSDCGateway/template.jsonc
  packages/config/discovery/_templates/global/TimelockController/shape/TimelockController.sol
  packages/config/discovery/_templates/global/TimelockController/template.jsonc
  packages/config/discovery/apex/ethereum/diffHistory.md
  packages/config/discovery/apex/ethereum/discovered.json
  packages/config/discovery/game7/arbitrum/config.jsonc
  packages/config/discovery/game7/arbitrum/diffHistory.md
  packages/config/discovery/game7/arbitrum/discovered.json
  packages/config/discovery/kinto/ethereum/config.jsonc
  packages/config/discovery/kinto/ethereum/diffHistory.md
  packages/config/discovery/kinto/ethereum/discovered.json
  packages/config/discovery/kinto/kinto/config.jsonc
  packages/config/discovery/kinto/kinto/diffHistory.md
  packages/config/discovery/kinto/kinto/discovered.json
  packages/config/discovery/mantle/ethereum/diffHistory.md
  packages/config/discovery/mantle/ethereum/discovered.json
  packages/config/discovery/phala/ethereum/diffHistory.md
  packages/config/discovery/phala/ethereum/discovered.json
  packages/config/discovery/river/ethereum/diffHistory.md
  packages/config/discovery/river/ethereum/discovered.json
  packages/config/discovery/soneium/ethereum/diffHistory.md
  packages/config/discovery/soneium/ethereum/discovered.json
  packages/config/discovery/starknet/ethereum/diffHistory.md
  packages/config/discovery/starknet/ethereum/discovered.json
  packages/config/src/projects/layer2s/river.ts
  packages/config/src/test/snapshots/river.riskView.snapshot
Labels: research

#6843 Tokens: add USDe, weETH to morph, solv tokens to soneium
  packages/config/src/projects/layer2s/morph.ts
  packages/config/src/projects/layer2s/soneium.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6852 Discovery updates 02/19
  packages/config/discovery/base/ethereum/diffHistory.md
  packages/config/discovery/base/ethereum/discovered.json
  packages/config/discovery/fraxferry/ethereum/diffHistory.md
  packages/config/discovery/fraxferry/ethereum/discovered.json
  packages/config/discovery/hyperlane/ethereum/config.jsonc
  packages/config/discovery/hyperlane/ethereum/diffHistory.md
  packages/config/discovery/hyperlane/ethereum/discovered.json
  packages/config/discovery/kinto/kinto/config.jsonc
  packages/config/discovery/kinto/kinto/diffHistory.md
  packages/config/discovery/kinto/kinto/discovered.json
  packages/config/discovery/starknet/ethereum/config.jsonc
  packages/config/discovery/starknet/ethereum/diffHistory.md
  packages/config/discovery/starknet/ethereum/discovered.json
  packages/config/discovery/unichain/unichain/diffHistory.md
  packages/config/discovery/unichain/unichain/discovered.json
  packages/config/src/projects/layer2s/starknet.ts
Labels: trivial-discovery

#6871 Make executor non-permissioned for layerZerov2 and stargatev2
  packages/config/src/projects/bridges/layerzerov2oft.ts
  packages/config/src/projects/bridges/stargatev2.ts
Labels: research

#6873 fix sequencer version handler post Bold
  packages/discovery/src/discovery/handlers/user/ArbitrumSequencerVersionHandler.ts
Labels: research

#6874 Arbitrum One: Move permissions to the Outbox and explain
  packages/config/discovery/_templates/orbitstack/Timelock/template.jsonc
  packages/config/discovery/_templates/orbitstack/layer2/L2ProxyAdmin/shape/L2ProxyAdmin.sol
  packages/config/discovery/_templates/orbitstack/layer2/L2ProxyAdmin/shape/criteria.json
  packages/config/discovery/_templates/orbitstack/layer2/L2ProxyAdmin/template.jsonc
  packages/config/discovery/arbitrum/arbitrum/diffHistory.md
  packages/config/discovery/arbitrum/arbitrum/discovered.json
  packages/config/discovery/arbitrum/ethereum/config.jsonc
  packages/config/discovery/arbitrum/ethereum/diffHistory.md
  packages/config/discovery/arbitrum/ethereum/discovered.json
  packages/config/discovery/nova/ethereum/diffHistory.md
  packages/config/discovery/nova/ethereum/discovered.json
Labels: research

#6895 Lz janitor
  packages/config/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/config/discovery/layerzerov2oft/ethereum/discovered.json
  packages/config/src/projects/bridges/layerzerov2oft.ts
  packages/config/src/projects/bridges/stargatev2.ts
  packages/frontend/public/images/architecture/layerzerov2oft.png
  packages/frontend/public/images/architecture/stargatev2.png
Labels: research

#6901 add random native tokens to base
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#6924 Tokens 02/25
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/l2b/src/implementations/common/tokie.json
Labels: research

#6920 Tokens script results
  packages/backend/scripts/discover-tokens/discovered.json
  packages/backend/scripts/discover-tokens/index.ts
  packages/backend/scripts/discover-tokens/processedEscrows.json
Labels: research

#6936 connext is winding down, add warning
  packages/config/src/projects/bridges/amarok.ts
Labels: research

#6947 Discovery updates 02/26
  packages/config/discovery/soneium/ethereum/diffHistory.md
  packages/config/discovery/soneium/ethereum/discovered.json
  packages/config/discovery/soon/ethereum/diffHistory.md
  packages/config/discovery/soon/ethereum/discovered.json
Labels: trivial-discovery

#6985 Discovery updates 02/28
  packages/config/discovery/_templates/tokens/Lido/stETH/template.jsonc
  packages/config/discovery/layerzerov2oft/ethereum/diffHistory.md
  packages/config/discovery/layerzerov2oft/ethereum/discovered.json
  packages/config/discovery/shared-zk-stack/ethereum/diffHistory.md
  packages/config/discovery/shared-zk-stack/ethereum/discovered.json
  packages/config/discovery/shared-zk-stack/zksync2/config.jsonc
  packages/config/discovery/shared-zk-stack/zksync2/diffHistory.md
  packages/config/discovery/shared-zk-stack/zksync2/discovered.json
  packages/config/discovery/sonicgateway/ethereum/config.jsonc
  packages/config/discovery/sonicgateway/ethereum/diffHistory.md
  packages/config/discovery/sonicgateway/ethereum/discovered.json
  packages/config/discovery/stargatev2/ethereum/diffHistory.md
  packages/config/discovery/stargatev2/ethereum/discovered.json
  packages/config/discovery/tokens/ethereum/diffHistory.md
  packages/config/discovery/tokens/ethereum/discovered.json
  packages/config/src/projects/layer3s/bugbuster.ts
  packages/protocolbeat/src/panel-values/explorers.ts
Labels: trivial-discovery
