Repository l2beat/l2beat, pull requests merged in 2025-04, with the labels that each got.

#7317 Kintoscript update
  packages/l2b/src/implementations/scan-kinto-am/ScanKintoAmImpl.ts
Labels: research

#7379 add new rpc for real
  packages/config/src/projects/real/real.ts
Labels: research

#7381 Discovery updates 04/03
  packages/config/src/projects/across-v3/ethereum/diffHistory.md
  packages/config/src/projects/across-v3/ethereum/discovered.json
  packages/config/src/projects/blessnet/arbitrum/config.jsonc
  packages/config/src/projects/blessnet/arbitrum/diffHistory.md
  packages/config/src/projects/blessnet/arbitrum/discovered.json
  packages/config/src/projects/bob/ethereum/diffHistory.md
  packages/config/src/projects/bob/ethereum/discovered.json
  packages/config/src/projects/everclearbridge/ethereum/diffHistory.md
  packages/config/src/projects/everclearbridge/ethereum/discovered.json
  packages/config/src/projects/everclearbridge/everclear/diffHistory.md
  packages/config/src/projects/everclearbridge/everclear/discovered.json
  packages/config/src/projects/hyperlane/ethereum/config.jsonc
  packages/config/src/projects/hyperlane/ethereum/diffHistory.md
  packages/config/src/projects/hyperlane/ethereum/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/sonicgateway/ethereum/diffHistory.md
  packages/config/src/projects/sonicgateway/ethereum/discovered.json
  packages/config/src/projects/vector/ethereum/diffHistory.md
  packages/config/src/projects/vector/ethereum/discovered.json
  packages/config/src/projects/wirex/ethereum/diffHistory.md
  packages/config/src/projects/wirex/ethereum/discovered.json
Labels: trivial-discovery

#7391 Review superposition
  packages/config/src/projects/_templates/orbitstack/Bridge/shape/Bridge_superposition.sol
  packages/config/src/projects/_templates/orbitstack/Inbox/shape/Inbox_superposition.sol
  packages/config/src/projects/superposition/arbitrum/config.jsonc
  packages/config/src/projects/superposition/arbitrum/diffHistory.md
  packages/config/src/projects/superposition/arbitrum/discovered.json
  packages/config/src/projects/superposition/superposition.ts
  packages/config/src/test/snapshots/superposition.riskView.snapshot
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7393 review SNAXchain (full)
  packages/config/src/common/stateDerivations.ts
  packages/config/src/projects/snaxchain/ethereum/config.jsonc
  packages/config/src/projects/snaxchain/ethereum/diffHistory.md
  packages/config/src/projects/snaxchain/ethereum/discovered.json
  packages/config/src/projects/snaxchain/snaxchain.ts
  packages/config/src/test/snapshots/snaxchain.riskView.snapshot
Labels: research

#7400 redwarn funki
  packages/config/src/projects/funki/funki.ts
Labels: research

#7413 Discovery updates 04/06
  packages/config/src/projects/_templates/lightlink/CanonicalStateChain/template.jsonc
  packages/config/src/projects/automata/automata.ts
  packages/config/src/projects/automata/ethereum/config.jsonc
  packages/config/src/projects/automata/ethereum/diffHistory.md
  packages/config/src/projects/automata/ethereum/discovered.json
  packages/config/src/projects/celo/ethereum/config.jsonc
  packages/config/src/projects/celo/ethereum/diffHistory.md
  packages/config/src/projects/celo/ethereum/discovered.json
  packages/config/src/projects/cyber/cyber.ts
  packages/config/src/projects/cyber/ethereum/config.jsonc
  packages/config/src/projects/cyber/ethereum/diffHistory.md
  packages/config/src/projects/cyber/ethereum/discovered.json
  packages/config/src/projects/eigenda/ethereum/diffHistory.md
  packages/config/src/projects/eigenda/ethereum/discovered.json
  packages/config/src/projects/funki/ethereum/config.jsonc
  packages/config/src/projects/funki/ethereum/diffHistory.md
  packages/config/src/projects/funki/ethereum/discovered.json
  packages/config/src/projects/funki/funki.ts
  packages/config/src/projects/gmnetwork/ethereum/diffHistory.md
  packages/config/src/projects/gmnetwork/ethereum/discovered.json
  packages/config/src/projects/lightlink/ethereum/diffHistory.md
  packages/config/src/projects/lightlink/ethereum/discovered.json
  packages/config/src/projects/muster/arbitrum/diffHistory.md
  packages/config/src/projects/muster/arbitrum/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/redstone/ethereum/diffHistory.md
  packages/config/src/projects/redstone/ethereum/discovered.json
  packages/config/src/projects/scroll/scroll/config.jsonc
  packages/config/src/projects/scroll/scroll/diffHistory.md
  packages/config/src/projects/scroll/scroll/discovered.json
  packages/config/src/projects/settlus/ethereum/config.jsonc
  packages/config/src/projects/settlus/ethereum/diffHistory.md
  packages/config/src/projects/settlus/ethereum/discovered.json
  packages/config/src/projects/shared-eigenlayer/ethereum/diffHistory.md
  packages/config/src/projects/shared-eigenlayer/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/l2b-fetchzkstack_output.json
  packages/config/src/projects/soneium/ethereum/diffHistory.md
  packages/config/src/projects/soneium/ethereum/discovered.json
  packages/config/src/projects/swell/ethereum/diffHistory.md
  packages/config/src/projects/swell/ethereum/discovered.json
  packages/config/src/projects/swell/swell.ts
  packages/config/src/projects/ternoa/ethereum/diffHistory.md
  packages/config/src/projects/ternoa/ethereum/discovered.json
  packages/config/src/projects/worldcoin/ethereum/diffHistory.md
  packages/config/src/projects/worldcoin/ethereum/discovered.json
  packages/config/src/projects/xai/arbitrum/diffHistory.md
  packages/config/src/projects/xai/arbitrum/discovered.json
  packages/config/src/projects/xterio/ethereum/config.jsonc
  packages/config/src/projects/xterio/ethereum/diffHistory.md
  packages/config/src/projects/xterio/ethereum/discovered.json
  packages/config/src/projects/xterio/xterio.ts
  packages/config/src/templates/opStack.ts
Labels: trivial-discovery

#7428 Review zkcandy
  packages/config/src/projects/zkcandy/ethereum/config.jsonc
  packages/config/src/projects/zkcandy/ethereum/diffHistory.md
  packages/config/src/projects/zkcandy/ethereum/discovered.json
  packages/config/src/projects/zkcandy/zkcandy.ts
  packages/config/src/projects/zkcandy/zksync2/config.jsonc
  packages/config/src/projects/zkcandy/zksync2/diffHistory.md
  packages/config/src/projects/zkcandy/zksync2/discovered.json
  packages/config/src/test/snapshots/zkcandy.riskView.snapshot
Labels: research

#7431 update starknet trackedTxs
  packages/config/src/projects/starknet/starknet.ts
Labels: research

#7432 add soneium tokens: uBTC, USDT0
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7442 Discovery updates 04/09
  packages/config/src/projects/_templates/opstack/L2OutputOracle_soon/shapes.json
  packages/config/src/projects/_templates/opstack/L2OutputOracle_soon/template.jsonc
  packages/config/src/projects/edgeless/ethereum/diffHistory.md
  packages/config/src/projects/edgeless/ethereum/discovered.json
  packages/config/src/projects/everclearbridge/everclear/config.jsonc
  packages/config/src/projects/everclearbridge/everclear/diffHistory.md
  packages/config/src/projects/everclearbridge/everclear/discovered.json
  packages/config/src/projects/gmnetwork/ethereum/diffHistory.md
  packages/config/src/projects/muster/arbitrum/diffHistory.md
  packages/config/src/projects/muster/arbitrum/discovered.json
  packages/config/src/projects/oevnetwork/ethereum/diffHistory.md
  packages/config/src/projects/oevnetwork/ethereum/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/soon/ethereum/diffHistory.md
  packages/config/src/projects/soon/ethereum/discovered.json
  packages/config/src/projects/xai/arbitrum/diffHistory.md
  packages/config/src/projects/xai/arbitrum/discovered.json
  packages/config/src/test/snapshots/soon.riskView.snapshot
Labels: trivial-discovery

#7459 add kinto k token (native)
  packages/config/src/projects/kinto/kinto.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7467 add blend token to educhain
  packages/config/src/projects/educhain/educhain.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7473 Unichain upgrade (1.4.0-unichain), add wstETH
  packages/config/src/projects/unichain/ethereum/config.jsonc
  packages/config/src/projects/unichain/ethereum/diffHistory.md
  packages/config/src/projects/unichain/ethereum/discovered.json
  packages/config/src/projects/unichain/unichain.ts
Labels: research

#7475 Tokens 04/14
  packages/config/src/projects/ink/ink.ts
  packages/config/src/projects/lisk/ethereum/config.jsonc
  packages/config/src/projects/lisk/ethereum/diffHistory.md
  packages/config/src/projects/lisk/ethereum/discovered.json
  packages/config/src/projects/lisk/lisk.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7443 Adds Hashi and GnosisChain contracts discovery
  packages/config/src/projects/omni/ethereum/config.jsonc
  packages/config/src/projects/omni/ethereum/diffHistory.md
  packages/config/src/projects/omni/ethereum/discovered.json
  packages/config/src/projects/omni/gnosis/config.jsonc
  packages/config/src/projects/omni/gnosis/diffHistory.md
  packages/config/src/projects/omni/gnosis/discovered.json
  packages/config/src/projects/omni/omni.ts
Labels: research

#7478 change mantle reasonForOthers
  packages/config/src/projects/mantle/mantle.ts
Labels: research

#7487 Discovery updates 04/14
  packages/config/src/projects/bobanetwork/ethereum/diffHistory.md
  packages/config/src/projects/bobanetwork/ethereum/discovered.json
  packages/config/src/projects/everclearbridge/everclear/diffHistory.md
  packages/config/src/projects/everclearbridge/everclear/discovered.json
  packages/config/src/projects/kinto/kinto/config.jsonc
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/lisk/lisk.ts
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/l2b-fetchzkstack_output.json
  packages/l2b/src/implementations/fetchZkStack.ts
  packages/l2b/src/implementations/scan-kinto-am/ScanKintoAmImpl.ts
Labels: research

#7500 add weETH to unichain
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
Labels: research

#7496 Discodrive linea
  packages/config/src/projects/_templates/global/UpgradeableBeacon/shapes.json
  packages/config/src/projects/_templates/global/UpgradeableBeacon/template.jsonc
  packages/config/src/projects/_templates/linea/BridgedToken/shapes.json
  packages/config/src/projects/_templates/linea/BridgedToken/template.jsonc
  packages/config/src/projects/_templates/linea/CallForwardingProxy/shapes.json
  packages/config/src/projects/_templates/linea/CallForwardingProxy/template.jsonc
  packages/config/src/projects/_templates/linea/LineaRollup/template.jsonc
  packages/config/src/projects/_templates/linea/PlonkVerifierForMultiTypeDataAggregation/shapes.json
  packages/config/src/projects/_templates/linea/PlonkVerifierForMultiTypeDataAggregation/template.jsonc
  packages/config/src/projects/_templates/linea/Roles/criteria.json
  packages/config/src/projects/_templates/linea/Roles/shapes.json
  packages/config/src/projects/_templates/linea/Roles/template.jsonc
  packages/config/src/projects/_templates/linea/TokenBridge/template.jsonc
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/linea/ethereum/config.jsonc
  packages/config/src/projects/linea/ethereum/diffHistory.md
  packages/config/src/projects/linea/ethereum/discovered.json
  packages/config/src/projects/linea/linea.ts
Labels: research

#7505 use opstack.ts for base
  packages/config/src/projects/base/base.ts
  packages/config/src/projects/base/ethereum/config.jsonc
  packages/config/src/projects/base/ethereum/diffHistory.md
  packages/config/src/projects/base/ethereum/discovered.json
Labels: research

#7509 Discovery updates 04/16
  packages/config/src/projects/_templates/gnosisbridge/Yaho/shapes.json
  packages/config/src/projects/_templates/gnosisbridge/Yaho/template.jsonc
  packages/config/src/projects/_templates/gnosisbridge/Yaru/shapes.json
  packages/config/src/projects/_templates/gnosisbridge/Yaru/template.jsonc
  packages/config/src/projects/everclearbridge/ethereum/diffHistory.md
  packages/config/src/projects/everclearbridge/ethereum/discovered.json
  packages/config/src/projects/everclearbridge/everclear/config.jsonc
  packages/config/src/projects/everclearbridge/everclear/diffHistory.md
  packages/config/src/projects/everclearbridge/everclear/discovered.json
  packages/config/src/projects/grvt/grvt.ts
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/omni/ethereum/config.jsonc
  packages/config/src/projects/omni/ethereum/diffHistory.md
  packages/config/src/projects/omni/ethereum/discovered.json
  packages/config/src/projects/omni/gnosis/diffHistory.md
  packages/config/src/projects/omni/gnosis/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/ronin/ethereum/diffHistory.md
  packages/config/src/projects/ronin/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/l2b-fetchzkstack_output.json
  packages/config/src/projects/xdai/ethereum/config.jsonc
  packages/config/src/projects/xdai/ethereum/diffHistory.md
  packages/config/src/projects/xdai/ethereum/discovered.json
  packages/config/src/projects/zksync2/ethereum/diffHistory.md
  packages/config/src/projects/zksync2/ethereum/discovered.json
Labels: research

#7512 add ZK token incident
  packages/config/src/projects/zksync2/ethereum/config.jsonc
  packages/config/src/projects/zksync2/ethereum/diffHistory.md
  packages/config/src/projects/zksync2/ethereum/discovered.json
  packages/config/src/projects/zksync2/zksync2.ts
Labels: research

#7514 add rsETH to unichain and test tvs4
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/unichain.json
Labels: research

#7548 Discovery updates 04/18
  packages/config/src/projects/_templates/opstack/OptimismPortalAdminWithdraw/shapes.json
  packages/config/src/projects/_templates/opstack/OptimismPortalAdminWithdraw/template.jsonc
  packages/config/src/projects/omni/gnosis/config.jsonc
  packages/config/src/projects/omni/gnosis/diffHistory.md
  packages/config/src/projects/omni/gnosis/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/scroll/ethereum/diffHistory.md
  packages/config/src/projects/scroll/ethereum/discovered.json
  packages/config/src/projects/sonicgateway/ethereum/diffHistory.md
  packages/config/src/projects/sonicgateway/ethereum/discovered.json
  packages/config/src/projects/taiko/ethereum/diffHistory.md
  packages/config/src/projects/taiko/ethereum/discovered.json
  packages/config/src/projects/taiko/taiko.ts
  packages/config/src/projects/xdai/ethereum/config.jsonc
  packages/config/src/projects/xdai/ethereum/diffHistory.md
  packages/config/src/projects/xdai/ethereum/discovered.json
  packages/config/src/projects/xterio/ethereum/diffHistory.md
  packages/config/src/projects/xterio/ethereum/discovered.json
  packages/config/src/projects/xterio/xterio.ts
  packages/config/src/projects/zksync2/ethereum/config.jsonc
  packages/config/src/projects/zksync2/ethereum/diffHistory.md
  packages/config/src/projects/zksync2/ethereum/discovered.json
Labels: trivial-discovery

#7551 rm Bob tvs warn, add correct uniBTC diff
  packages/config/src/projects/_templates/global/Timelock/shapes.json
  packages/config/src/projects/_templates/tokens/Origin/wOETH/shapes.json
  packages/config/src/projects/_templates/tokens/Origin/wOETH/template.jsonc
  packages/config/src/projects/bob/bob.ts
  packages/config/src/projects/tokens/base/config.jsonc
  packages/config/src/projects/tokens/base/diffHistory.md
  packages/config/src/projects/tokens/base/discovered.json
  packages/config/src/tvs/json/bob.json
Labels: research

#7557 add Ape token (apechain and arbitrum, custom tvs)
  packages/config/src/projects/apechain/apechain.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/apechain.json
  packages/config/src/tvs/json/arbitrum.json
Labels: research

#7560 Discovery updates 04/22
  packages/config/src/projects/arbitrum/arbitrum/diffHistory.md
  packages/config/src/projects/arbitrum/arbitrum/discovered.json
  packages/config/src/projects/hyperlane/ethereum/config.jsonc
  packages/config/src/projects/hyperlane/ethereum/diffHistory.md
  packages/config/src/projects/hyperlane/ethereum/discovered.json
  packages/config/src/projects/ronin/ethereum/config.jsonc
  packages/config/src/projects/ronin/ethereum/diffHistory.md
  packages/config/src/projects/ronin/ethereum/discovered.json
  packages/config/src/projects/ronin/ronin.ts
  packages/config/src/projects/sanko/arbitrum/diffHistory.md
  packages/config/src/projects/sanko/arbitrum/discovered.json
  packages/config/src/projects/shared-zk-stack/zksync2/diffHistory.md
  packages/config/src/projects/shared-zk-stack/zksync2/discovered.json
  packages/config/src/projects/zkfair/ethereum/config.jsonc
  packages/config/src/projects/zkfair/ethereum/diffHistory.md
  packages/config/src/projects/zkfair/ethereum/discovered.json
  packages/config/src/projects/zkfair/zkfair.ts
Labels: trivial-discovery

#7563 Add gridy under review
  packages/backend/src/config/features/da.ts
  packages/config/src/processing/layer3s.ts
  packages/config/src/projects/gridy/gridy.ts
  packages/config/src/test/snapshots/gridy.riskView.snapshot
  packages/frontend/public/icons/gridy.png
  packages/frontend/public/icons/karnot.png
  packages/frontend/public/images/badges/Karnot.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#7583 fix start ts of apechain tvs
  packages/config/src/tvs/json/apechain.json
  packages/config/src/tvs/json/ink.json
Labels: research

#7570 Discovery updates 04/23
  packages/config/src/projects/_templates/opstack/L1CrossDomainMessenger/shapes.json
  packages/config/src/projects/_templates/opstack/L1ERC721Bridge/shapes.json
  packages/config/src/projects/_templates/opstack/L1StandardBridge/shapes.json
  packages/config/src/projects/_templates/opstack/OptimismPortal/shapes.json
  packages/config/src/projects/_templates/polygonposbridge/StakeManager_shibarium/template.jsonc
  packages/config/src/projects/across-v3/ethereum/diffHistory.md
  packages/config/src/projects/across-v3/ethereum/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/shibarium/ethereum/diffHistory.md
  packages/config/src/projects/shibarium/ethereum/discovered.json
  packages/config/src/projects/zircuit/ethereum/diffHistory.md
  packages/config/src/projects/zircuit/ethereum/discovered.json
Labels: trivial-discovery

#7603 Discovery updates 04/25
  packages/config/src/projects/blessnet/arbitrum/diffHistory.md
  packages/config/src/projects/blessnet/arbitrum/discovered.json
  packages/config/src/projects/inevm/arbitrum/diffHistory.md
  packages/config/src/projects/inevm/arbitrum/discovered.json
  packages/config/src/projects/molten/arbitrum/diffHistory.md
  packages/config/src/projects/molten/arbitrum/discovered.json
  packages/config/src/projects/paradex/paradex.ts
  packages/config/src/projects/ronin/ethereum/diffHistory.md
  packages/config/src/projects/ronin/ethereum/discovered.json
  packages/config/src/projects/ronin/ronin.ts
  packages/config/src/projects/shared-sharp-verifier/ethereum/diffHistory.md
  packages/config/src/projects/shared-sharp-verifier/ethereum/discovered.json
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/zksync2/zksync2.ts
Labels: trivial-discovery, research

#7600 Opstack isthmus upgrade
  packages/config/src/projects/_templates/opstack/L1CrossDomainMessenger/shapes.json
  packages/config/src/projects/_templates/opstack/L1ERC721Bridge/shapes.json
  packages/config/src/projects/_templates/opstack/L1StandardBridge/shapes.json
  packages/config/src/projects/_templates/opstack/MIPS/shapes.json
  packages/config/src/projects/_templates/opstack/OptimismPortal2/shapes.json
  packages/config/src/projects/_templates/opstack/SystemConfig/shapes.json
  packages/config/src/projects/base/ethereum/diffHistory.md
  packages/config/src/projects/base/ethereum/discovered.json
  packages/config/src/projects/ink/ethereum/diffHistory.md
  packages/config/src/projects/ink/ethereum/discovered.json
  packages/config/src/projects/optimism/ethereum/diffHistory.md
  packages/config/src/projects/optimism/ethereum/discovered.json
  packages/config/src/projects/race/ethereum/diffHistory.md
  packages/config/src/projects/race/ethereum/discovered.json
  packages/config/src/projects/soneium/ethereum/diffHistory.md
  packages/config/src/projects/soneium/ethereum/discovered.json
  packages/config/src/projects/unichain/ethereum/diffHistory.md
  packages/config/src/projects/unichain/ethereum/discovered.json
  packages/config/src/projects/zora/ethereum/diffHistory.md
  packages/config/src/projects/zora/ethereum/discovered.json
  packages/config/src/test/snapshots/powerloom.riskView.snapshot
  packages/config/src/test/snapshots/zora.riskView.snapshot
Labels: research

#7606 OP mainnet: delayedWETH owner moved, rm underreview
  packages/config/src/projects/optimism/ethereum/diffHistory.md
  packages/config/src/projects/optimism/ethereum/discovered.json
  packages/config/src/projects/optimism/optimism.ts
Labels: research

#7614 add USDC discovery (+CCTP contracts)
  packages/config/src/projects/_templates/tokens/circle/MasterMinter/shapes.json
  packages/config/src/projects/_templates/tokens/circle/MasterMinter/template.jsonc
  packages/config/src/projects/_templates/tokens/circle/MessageTransmitter/shapes.json
  packages/config/src/projects/_templates/tokens/circle/MessageTransmitter/template.jsonc
  packages/config/src/projects/_templates/tokens/circle/TokenMessenger/shapes.json
  packages/config/src/projects/_templates/tokens/circle/TokenMessenger/template.jsonc
  packages/config/src/projects/_templates/tokens/circle/TokenMinter/shapes.json
  packages/config/src/projects/_templates/tokens/circle/TokenMinter/template.jsonc
  packages/config/src/projects/_templates/tokens/circle/USDC/shapes.json
  packages/config/src/projects/_templates/tokens/circle/USDC/template.jsonc
  packages/config/src/projects/tokens/base/config.jsonc
  packages/config/src/projects/tokens/base/diffHistory.md
  packages/config/src/projects/tokens/base/discovered.json
Labels: research

#7587 Merge gnosis bridges
  packages/config/src/discovery/descriptions.ts
  packages/config/src/processing/bridges.ts
  packages/config/src/projects/_templates/gnosisbridge/BridgeValidators/shapes.json
  packages/config/src/projects/_templates/gnosisbridge/BridgeValidators/template.jsonc
  packages/config/src/projects/_templates/gnosisbridge/HashiManager/shapes.json
  packages/config/src/projects/_templates/gnosisbridge/HashiManager/template.jsonc
  packages/config/src/projects/_templates/gnosisbridge/Yaho/template.jsonc
  packages/config/src/projects/_templates/gnosisbridge/Yaru/template.jsonc
  packages/config/src/projects/ethereumConfig.jsonc
  packages/config/src/projects/globalConfig.jsonc
  packages/config/src/projects/omni/ethereum/config.jsonc
  packages/config/src/projects/omni/ethereum/diffHistory.md
  packages/config/src/projects/omni/ethereum/discovered.json
  packages/config/src/projects/omni/gnosis/config.jsonc
  packages/config/src/projects/omni/gnosis/diffHistory.md
  packages/config/src/projects/omni/gnosis/discovered.json
  packages/config/src/projects/omni/omni.ts
  packages/config/src/projects/xdai/ethereum/config.jsonc
  packages/config/src/projects/xdai/ethereum/diffHistory.md
  packages/config/src/projects/xdai/ethereum/discovered.json
  packages/config/src/projects/xdai/xdai.ts
  packages/discovery/schemas/contract.v2.schema.json
  packages/discovery/src/discovery/config/PermissionConfig.ts
  packages/discovery/src/discovery/config/StructureConfig.ts
  packages/frontend/public/icons/omni.png
  packages/frontend/public/images/architecture/omni.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#7635 Tokens 04/29
  packages/config/src/projects/real/real.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/arbitrum.json
  packages/config/src/tvs/json/base.json
  packages/config/src/tvs/json/blast.json
  packages/config/src/tvs/json/degate3.json
  packages/config/src/tvs/json/fraxtal.json
  packages/config/src/tvs/json/linea.json
  packages/config/src/tvs/json/lumia.json
  packages/config/src/tvs/json/mantapacific.json
  packages/config/src/tvs/json/mantle.json
  packages/config/src/tvs/json/mode.json
  packages/config/src/tvs/json/morph.json
  packages/config/src/tvs/json/optimism.json
  packages/config/src/tvs/json/polygon-pos.json
  packages/config/src/tvs/json/real.json
  packages/config/src/tvs/json/scroll.json
  packages/config/src/tvs/json/ternoa.json
  packages/config/src/tvs/json/unichain.json
  packages/config/src/tvs/json/zircuit.json
  packages/config/src/tvs/json/zkfair.json
  packages/config/src/tvs/json/zklinknova.json
Labels: research
