Repository l2beat/l2beat, pull requests merged in 2025-05, with the labels that each got.

#7653 Zkstack v27 upgrade
  packages/config/src/projects/_templates/shared-zk-stack/v26/BridgeHub/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/v26/ChainTypeManager/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/v26/L1AssetRouter/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/v26/L1GenesisUpgrade/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/v26/L1NativeTokenVault/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/v26/L1Nullifier/shapes.json
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/zksync2/diffHistory.md
  packages/config/src/projects/shared-zk-stack/zksync2/discovered.json
Labels: research

#7561 Update node info for sn stack
  packages/config/src/projects/paradex/paradex.ts
  packages/config/src/projects/starknet/starknet.ts
Labels: research

#7662 zk gov script timeline tweaks
  packages/l2b/src/implementations/zkgovproposal.ts
Labels: research

#7663 Linea statederiv from L1
  packages/config/src/projects/_templates/linea/Verifier/shapes.json
  packages/config/src/projects/_templates/linea/Verifier/template.jsonc
  packages/config/src/projects/linea/ethereum/diffHistory.md
  packages/config/src/projects/linea/ethereum/discovered.json
  packages/config/src/projects/linea/linea.ts
Labels: research

#7679 Discovery updates 05/05
  packages/config/src/projects/_templates/global/TimelockController/shapes.json
  packages/config/src/projects/vector/ethereum/diffHistory.md
  packages/config/src/projects/vector/ethereum/discovered.json
  packages/config/src/projects/worldcoin/ethereum/diffHistory.md
  packages/config/src/projects/worldcoin/ethereum/discovered.json
  packages/config/src/projects/worldcoin/optimism/diffHistory.md
  packages/config/src/projects/worldcoin/optimism/discovered.json
Labels: research

#7685 Tokens 05/06 (kBTC, Spiko on starknet)
  packages/config/src/projects/starknet/starknet.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/ink.json
  packages/config/src/tvs/json/optimism.json
  packages/config/src/tvs/json/starknet.json
  packages/config/src/tvs/json/unichain.json
Labels: research

#7680 Housekeeping: Arbitrum correction and Kinto asserts
  packages/config/src/projects/_templates/kinto/AccessManager/shapes.json
  packages/config/src/projects/_templates/kinto/AccessManager/template.jsonc
  packages/config/src/projects/_templates/kinto/KintoAppRegistry/shapes.json
  packages/config/src/projects/_templates/kinto/KintoAppRegistry/template.jsonc
  packages/config/src/projects/_templates/kinto/KintoID/shapes.json
  packages/config/src/projects/_templates/kinto/KintoID/template.jsonc
  packages/config/src/projects/arbitrum/ethereum/diffHistory.md
  packages/config/src/projects/kinto/kinto.ts
  packages/config/src/projects/kinto/kinto/config.jsonc
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
Labels: research

#7696 Discovery updates 06.05
  packages/config/src/projects/_templates/orbitstack/SequencerInbox_Celestia_Espresso/shapes.json
  packages/config/src/projects/geist/base/diffHistory.md
  packages/config/src/projects/geist/base/discovered.json
  packages/config/src/projects/rari/arbitrum/diffHistory.md
  packages/config/src/projects/rari/arbitrum/discovered.json
  packages/config/src/projects/rari/rari.ts
  packages/config/src/projects/stargatev2/arbitrum/diffHistory.md
  packages/config/src/projects/stargatev2/arbitrum/discovered.json
  packages/config/src/projects/stargatev2/base/diffHistory.md
  packages/config/src/projects/stargatev2/base/discovered.json
  packages/config/src/projects/stargatev2/ethereum/diffHistory.md
  packages/config/src/projects/stargatev2/ethereum/discovered.json
  packages/config/src/projects/stargatev2/linea/diffHistory.md
  packages/config/src/projects/stargatev2/linea/discovered.json
  packages/config/src/projects/stargatev2/mantle/diffHistory.md
  packages/config/src/projects/stargatev2/mantle/discovered.json
  packages/config/src/projects/stargatev2/optimism/diffHistory.md
  packages/config/src/projects/stargatev2/optimism/discovered.json
  packages/config/src/projects/stargatev2/scroll/diffHistory.md
  packages/config/src/projects/stargatev2/scroll/discovered.json
  packages/config/src/projects/vector/ethereum/diffHistory.md
  packages/config/src/projects/vector/ethereum/discovered.json
  packages/config/src/projects/zklinknova/mantle/diffHistory.md
  packages/config/src/projects/zklinknova/mantle/discovered.json
  packages/config/src/test/snapshots/rari.riskView.snapshot
Labels: research

#7688 Discovery updates 05/06
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/_templates/shared-zk-stack/DualVerifier/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/DualVerifier/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/L1VerifierFflonk/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/L1VerifierFflonk/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/L1VerifierPlonk/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/L1VerifierPlonk/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/v26/Diamond/shapes.json
  packages/config/src/projects/alienx/ethereum/diffHistory.md
  packages/config/src/projects/alienx/ethereum/discovered.json
  packages/config/src/projects/arbitrum/arbitrum/diffHistory.md
  packages/config/src/projects/arbitrum/arbitrum/discovered.json
  packages/config/src/projects/arbitrum/ethereum/diffHistory.md
  packages/config/src/projects/arbitrum/ethereum/discovered.json
  packages/config/src/projects/blessnet/arbitrum/diffHistory.md
  packages/config/src/projects/blessnet/arbitrum/discovered.json
  packages/config/src/projects/fraxtal/ethereum/diffHistory.md
  packages/config/src/projects/fraxtal/ethereum/discovered.json
  packages/config/src/projects/hychain/ethereum/diffHistory.md
  packages/config/src/projects/hychain/ethereum/discovered.json
  packages/config/src/projects/lyra/lyra.ts
  packages/config/src/projects/molten/arbitrum/diffHistory.md
  packages/config/src/projects/molten/arbitrum/discovered.json
  packages/config/src/projects/near/ethereum/diffHistory.md
  packages/config/src/projects/near/ethereum/discovered.json
  packages/config/src/projects/parallel/ethereum/diffHistory.md
  packages/config/src/projects/parallel/ethereum/discovered.json
  packages/config/src/projects/rari/rari.ts
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/socket/ethereum/config.jsonc
  packages/config/src/projects/socket/ethereum/diffHistory.md
  packages/config/src/projects/socket/ethereum/discovered.json
  packages/config/src/projects/socket/socket.ts
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/tokens/ethereum/diffHistory.md
  packages/config/src/projects/tokens/ethereum/discovered.json
  packages/config/src/projects/zksync2/ethereum/diffHistory.md
  packages/config/src/projects/zksync2/ethereum/discovered.json
  packages/config/src/projects/zksync2/zksync2/diffHistory.md
  packages/config/src/projects/zksync2/zksync2/discovered.json
  packages/config/src/templates/orbitStack.ts
  packages/config/src/templates/zkStack.ts
Labels: research

#7701 add Moonchain review
  packages/config/src/processing/layer3s.ts
  packages/config/src/projects/moonchain/moonchain.ts
  packages/config/src/projects/mxc/mxc.ts
  packages/config/src/test/snapshots/moonchain.riskView.snapshot
  packages/frontend/public/icons/moonchain.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#7708 Small updates / fixes
  packages/config/src/projects/moonchain/moonchain.ts
  packages/config/src/projects/rari/rari.ts
  packages/config/src/tvs/json/moonchain.json
  packages/config/src/tvs/json/socket.json
Labels: research

#7715 Daily updates for 07.05
  packages/config/src/projects/sonicgateway/ethereum/diffHistory.md
  packages/config/src/projects/sonicgateway/ethereum/discovered.json
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/tokens/base/diffHistory.md
  packages/config/src/projects/tokens/base/discovered.json
  packages/config/src/projects/tokens/ethereum/diffHistory.md
  packages/config/src/projects/tokens/ethereum/discovered.json
  packages/config/src/projects/vector/ethereum/diffHistory.md
  packages/config/src/projects/vector/ethereum/discovered.json
Labels: research

#7716 linea link fix
  packages/config/src/projects/linea/linea.ts
Labels: research

#7731 phala liveness fix
  packages/config/src/projects/phala/phala.ts
Labels: research

#7742 Discovery updates 05/09
  packages/config/src/projects/_templates/orbitstack/OneStepProverHostIo_Celestia/shapes.json
  packages/config/src/projects/_templates/orbitstack/OneStepProverHostIo_Celestia/template.jsonc
  packages/config/src/projects/aztec/ethereum/diffHistory.md
  packages/config/src/projects/aztec/ethereum/discovered.json
  packages/config/src/projects/galxegravity/ethereum/config.jsonc
  packages/config/src/projects/galxegravity/ethereum/diffHistory.md
  packages/config/src/projects/galxegravity/ethereum/discovered.json
  packages/config/src/projects/lens/ethereum/config.jsonc
  packages/config/src/projects/lens/ethereum/diffHistory.md
  packages/config/src/projects/lens/ethereum/discovered.json
  packages/config/src/projects/lens/zksync2/diffHistory.md
  packages/config/src/projects/lens/zksync2/discovered.json
  packages/config/src/projects/molten/arbitrum/config.jsonc
  packages/config/src/projects/molten/arbitrum/diffHistory.md
  packages/config/src/projects/molten/arbitrum/discovered.json
  packages/config/src/projects/shared-zk-stack/zksync2/diffHistory.md
  packages/config/src/projects/shared-zk-stack/zksync2/discovered.json
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/tokens/base/diffHistory.md
  packages/config/src/projects/tokens/base/discovered.json
  packages/config/src/projects/tokens/ethereum/diffHistory.md
  packages/config/src/projects/tokens/ethereum/discovered.json
Labels: trivial-discovery, research

#7746 add SUPR, archive ronin
  packages/config/src/projects/ronin/ronin.ts
  packages/config/src/projects/superseed/superseed.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/superseed.json
Labels: research

#7748 Starknet permissions & OP stack isthmus on L2
  packages/config/src/projects/_templates/opstack/Layer2/GasPriceOracle/shapes.json
  packages/config/src/projects/_templates/opstack/Layer2/GasPriceOracle/template.jsonc
  packages/config/src/projects/_templates/opstack/Layer2/L1Block/shapes.json
  packages/config/src/projects/_templates/opstack/Layer2/L1Block/template.jsonc
  packages/config/src/projects/_templates/opstack/Layer2/OperatorFeeVault/shapes.json
  packages/config/src/projects/_templates/opstack/Layer2/OperatorFeeVault/template.jsonc
  packages/config/src/projects/_templates/starknet/StarknetEthBridge/template.jsonc
  packages/config/src/projects/base/base/diffHistory.md
  packages/config/src/projects/base/base/discovered.json
  packages/config/src/projects/base/ethereum/diffHistory.md
  packages/config/src/projects/base/ethereum/discovered.json
  packages/config/src/projects/ink/ink/diffHistory.md
  packages/config/src/projects/ink/ink/discovered.json
  packages/config/src/projects/optimism/ethereum/diffHistory.md
  packages/config/src/projects/optimism/ethereum/discovered.json
  packages/config/src/projects/optimism/optimism/config.jsonc
  packages/config/src/projects/optimism/optimism/diffHistory.md
  packages/config/src/projects/optimism/optimism/discovered.json
  packages/config/src/projects/shared-sharp-verifier/ethereum/diffHistory.md
  packages/config/src/projects/shared-sharp-verifier/ethereum/discovered.json
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/unichain/unichain/diffHistory.md
  packages/config/src/projects/unichain/unichain/discovered.json
Labels: trivial-discovery, research

#7752 Discovery updates 05/12
  packages/config/src/projects/abstract/ethereum/diffHistory.md
  packages/config/src/projects/abstract/ethereum/discovered.json
  packages/config/src/projects/abstract/zksync2/diffHistory.md
  packages/config/src/projects/abstract/zksync2/discovered.json
  packages/config/src/projects/aztec/aztec.ts
  packages/config/src/projects/aztec/ethereum/config.jsonc
  packages/config/src/projects/aztec/ethereum/diffHistory.md
  packages/config/src/projects/aztec/ethereum/discovered.json
  packages/config/src/projects/ethereumConfig.jsonc
  packages/config/src/projects/globalConfig.jsonc
  packages/config/src/projects/morph/ethereum/config.jsonc
  packages/config/src/projects/morph/ethereum/diffHistory.md
  packages/config/src/projects/morph/ethereum/discovered.json
  packages/config/src/projects/morph/morph.ts
  packages/config/src/projects/omni/gnosis/diffHistory.md
  packages/config/src/projects/omni/gnosis/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/phala/ethereum/diffHistory.md
  packages/config/src/projects/phala/ethereum/discovered.json
  packages/config/src/projects/settlus/ethereum/config.jsonc
  packages/config/src/projects/settlus/ethereum/diffHistory.md
  packages/config/src/projects/settlus/ethereum/discovered.json
Labels: trivial-discovery

#7753 rm medium severities
  packages/config/src/projects/_templates/eigenlayer/EigenDAServiceManager/template.jsonc
  packages/config/src/projects/_templates/eigenlayer/RegistryCoordinator/template.jsonc
  packages/config/src/projects/_templates/eigenlayer/TokenHopper/template.jsonc
  packages/config/src/projects/_templates/kinto/KintoID/template.jsonc
  packages/config/src/projects/_templates/orbitstack/layer2/SecurityCouncilManager/template.jsonc
  packages/config/src/projects/_templates/polygon-cdk/PolygonRollupManager/template.jsonc
  packages/config/src/projects/_templates/polygon-cdk/PolygonRollupManager_pessimistic/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/v25/Diamond/template.jsonc
  packages/config/src/projects/amarok/ethereum/config.jsonc
  packages/config/src/projects/amarok/ethereum/diffHistory.md
  packages/config/src/projects/amarok/ethereum/discovered.json
  packages/config/src/projects/arbitrum/arbitrum/diffHistory.md
  packages/config/src/projects/arbitrum/arbitrum/discovered.json
  packages/config/src/projects/blast/ethereum/config.jsonc
  packages/config/src/projects/blast/ethereum/diffHistory.md
  packages/config/src/projects/blast/ethereum/discovered.json
  packages/config/src/projects/cbridge/ethereum/config.jsonc
  packages/config/src/projects/cbridge/ethereum/diffHistory.md
  packages/config/src/projects/cbridge/ethereum/discovered.json
  packages/config/src/projects/chainport/ethereum/config.jsonc
  packages/config/src/projects/chainport/ethereum/diffHistory.md
  packages/config/src/projects/chainport/ethereum/discovered.json
  packages/config/src/projects/eigenda/ethereum/diffHistory.md
  packages/config/src/projects/eigenda/ethereum/discovered.json
  packages/config/src/projects/immutablezkevm/ethereum/config.jsonc
  packages/config/src/projects/immutablezkevm/ethereum/diffHistory.md
  packages/config/src/projects/immutablezkevm/ethereum/discovered.json
  packages/config/src/projects/kinto/kinto/diffHistory.md
  packages/config/src/projects/kinto/kinto/discovered.json
  packages/config/src/projects/orbit/ethereum/config.jsonc
  packages/config/src/projects/orbit/ethereum/diffHistory.md
  packages/config/src/projects/orbit/ethereum/discovered.json
  packages/config/src/projects/shared-eigenlayer/ethereum/config.jsonc
  packages/config/src/projects/shared-eigenlayer/ethereum/diffHistory.md
  packages/config/src/projects/shared-eigenlayer/ethereum/discovered.json
  packages/config/src/projects/shared-polygon-cdk/ethereum/diffHistory.md
  packages/config/src/projects/shared-polygon-cdk/ethereum/discovered.json
  packages/config/src/projects/synapse/ethereum/config.jsonc
  packages/config/src/projects/synapse/ethereum/diffHistory.md
  packages/config/src/projects/synapse/ethereum/discovered.json
Labels: research

#7758 eoa warnings
  packages/config/src/projects/apex/apex.ts
  packages/config/src/projects/brine/brine.ts
  packages/config/src/projects/myria/myria.ts
  packages/config/src/projects/sorare/sorare.ts
Labels: trivial, research

#7786 Tokens 05/15
  packages/config/scripts/socketconvert/convertedVaults.txt
  packages/config/scripts/socketconvert/input.json
  packages/config/src/projects/abstract/abstract.ts
  packages/config/src/projects/lisk/lisk.ts
  packages/config/src/projects/polynomial/polynomial.ts
  packages/config/src/projects/swell/swell.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/abstract.json
  packages/config/src/tvs/json/lisk.json
  packages/config/src/tvs/json/optimism.json
  packages/config/src/tvs/json/polynomial.json
  packages/config/src/tvs/json/swell.json
  packages/l2b/src/commands/DeploymentTimestamp.ts
Labels: research

#7760 Starknet stage 1 review
  packages/config/src/common/riskView.ts
  packages/config/src/projects/_templates/shared-sharp-verifier/SHARPVerifierCallProxy/template.jsonc
  packages/config/src/projects/_templates/starknet/StarkgateManager/template.jsonc
  packages/config/src/projects/_templates/starknet/StarknetERC20Bridge/template.jsonc
  packages/config/src/projects/_templates/starknet/StarknetEthBridge/template.jsonc
  packages/config/src/projects/_templates/starknet/StarknetMultiBridge/template.jsonc
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/shared-sharp-verifier/ethereum/diffHistory.md
  packages/config/src/projects/shared-sharp-verifier/ethereum/discovered.json
  packages/config/src/projects/starknet/ethereum/config.jsonc
  packages/config/src/projects/starknet/ethereum/diffHistory.md
  packages/config/src/projects/starknet/ethereum/discovered.json
  packages/config/src/projects/starknet/starknet.ts
  packages/config/src/test/snapshots/abstract.riskView.snapshot
  packages/config/src/test/snapshots/apex.riskView.snapshot
  packages/config/src/test/snapshots/cronoszkevm.riskView.snapshot
  packages/config/src/test/snapshots/deversifi.riskView.snapshot
  packages/config/src/test/snapshots/grvt.riskView.snapshot
  packages/config/src/test/snapshots/immutablex.riskView.snapshot
  packages/config/src/test/snapshots/lens.riskView.snapshot
  packages/config/src/test/snapshots/myria.riskView.snapshot
  packages/config/src/test/snapshots/sophon.riskView.snapshot
  packages/config/src/test/snapshots/sorare.riskView.snapshot
  packages/config/src/test/snapshots/starknet.riskView.snapshot
  packages/config/src/test/snapshots/treasure.riskView.snapshot
  packages/config/src/test/snapshots/zeronetwork.riskView.snapshot
  packages/config/src/test/snapshots/zkcandy.riskView.snapshot
  packages/config/src/test/snapshots/zksync2.riskView.snapshot
  packages/frontend/public/images/architecture/starknet.png
  packages/frontend/public/images/upgrades-and-governance/starknet.png
Labels: research

#7804 Fix for kroma SP1Verifier discovery
  packages/config/src/projects/kroma/ethereum/config.jsonc
  packages/config/src/projects/kroma/ethereum/diffHistory.md
  packages/config/src/projects/kroma/ethereum/discovered.json
Labels: research

#7809 Discovery updates 05/16
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-copypasta.txt
  packages/config/scripts/socketcrawl/outfiles/socket-crawl-result.json
  packages/config/src/projects/abstract/abstract.ts
  packages/config/src/projects/abstract/ethereum/diffHistory.md
  packages/config/src/projects/abstract/ethereum/discovered.json
  packages/config/src/projects/abstract/zksync2/diffHistory.md
  packages/config/src/projects/abstract/zksync2/discovered.json
  packages/config/src/projects/across-v3/ethereum/config.jsonc
  packages/config/src/projects/across-v3/ethereum/diffHistory.md
  packages/config/src/projects/across-v3/ethereum/discovered.json
  packages/config/src/projects/arbitrum/arbitrum/diffHistory.md
  packages/config/src/projects/arbitrum/arbitrum/discovered.json
  packages/config/src/projects/arbitrum/ethereum/diffHistory.md
  packages/config/src/projects/arbitrum/ethereum/discovered.json
  packages/config/src/projects/arenaz/ethereum/diffHistory.md
  packages/config/src/projects/arenaz/ethereum/discovered.json
  packages/config/src/projects/lens/ethereum/diffHistory.md
  packages/config/src/projects/lens/ethereum/discovered.json
  packages/config/src/projects/lens/lens.ts
  packages/config/src/projects/lens/zksync2/diffHistory.md
  packages/config/src/projects/lens/zksync2/discovered.json
  packages/config/src/projects/metis/ethereum/config.jsonc
  packages/config/src/projects/metis/ethereum/diffHistory.md
  packages/config/src/projects/metis/ethereum/discovered.json
  packages/config/src/projects/metis/metis.ts
  packages/config/src/projects/omni/ethereum/diffHistory.md
  packages/config/src/projects/omni/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/zksync2/diffHistory.md
  packages/config/src/projects/shared-zk-stack/zksync2/discovered.json
  packages/config/src/projects/socket/ethereum/diffHistory.md
  packages/config/src/projects/socket/ethereum/discovered.json
  packages/config/src/projects/soneium/soneium.ts
  packages/config/src/projects/starknet/starknet.ts
  packages/config/src/projects/swell/ethereum/diffHistory.md
  packages/config/src/projects/swell/ethereum/discovered.json
  packages/config/src/projects/treasure/treasure.ts
  packages/config/src/tvs/json/soneium.json
  packages/config/src/tvs/json/treasure.json
Labels: research

#7815 Discovery updates 05/19
  packages/config/src/projects/across-v3/ethereum/diffHistory.md
  packages/config/src/projects/across-v3/ethereum/discovered.json
  packages/config/src/projects/geist/base/config.jsonc
  packages/config/src/projects/geist/base/diffHistory.md
  packages/config/src/projects/geist/base/discovered.json
  packages/config/src/projects/grvt/ethereum/diffHistory.md
  packages/config/src/projects/grvt/ethereum/discovered.json
  packages/config/src/projects/grvt/grvt.ts
  packages/config/src/projects/grvt/zksync2/diffHistory.md
  packages/config/src/projects/grvt/zksync2/discovered.json
  packages/config/src/projects/paradex/ethereum/diffHistory.md
  packages/config/src/projects/paradex/ethereum/discovered.json
  packages/config/src/projects/ronin/ronin.ts
  packages/config/src/projects/sophon/ethereum/diffHistory.md
  packages/config/src/projects/sophon/ethereum/discovered.json
  packages/config/src/projects/sophon/sophon.ts
  packages/config/src/projects/sophon/zksync2/diffHistory.md
  packages/config/src/projects/sophon/zksync2/discovered.json
Labels: research

#7829 add M-BTC to lisk
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/lisk.json
Labels: research

#7824 Near omnibridge review
  packages/config/src/processing/bridges.ts
  packages/config/src/projects/_templates/nearomni/BridgeToken/shapes.json
  packages/config/src/projects/_templates/nearomni/BridgeToken/template.jsonc
  packages/config/src/projects/_templates/nearomni/OmniBridge/shapes.json
  packages/config/src/projects/_templates/nearomni/OmniBridge/template.jsonc
  packages/config/src/projects/ethereumConfig.jsonc
  packages/config/src/projects/nearomni/ethereum/config.jsonc
  packages/config/src/projects/nearomni/ethereum/diffHistory.md
  packages/config/src/projects/nearomni/ethereum/discovered.json
  packages/config/src/projects/nearomni/nearomni.ts
  packages/frontend/public/icons/nearomni.png
  packages/frontend/public/images/architecture/nearomni.png
  packages/frontend/rewrite/scripts/tinify/metadata.json
  packages/frontend/rewrite/static/icons/nearomni.png
  packages/frontend/rewrite/static/images/architecture/nearomni.png
  packages/frontend/rewrite/static/meta-images/bridges/projects/nearomni/opengraph-image.png
  packages/frontend/scripts/logos/tinifiedLogos.json
Labels: research

#7882 Zkstack gateway disco
  packages/config/src/projects/_templates/shared-zk-stack/ChainAdmin/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/InitialGatewayTransactionFilterer/shapes.json
  packages/config/src/projects/_templates/shared-zk-stack/InitialGatewayTransactionFilterer/template.jsonc
  packages/config/src/projects/_templates/shared-zk-stack/v26/BridgeHub/template.jsonc
  packages/config/src/projects/gateway/ethereum/config.jsonc
  packages/config/src/projects/gateway/ethereum/diffHistory.md
  packages/config/src/projects/gateway/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/diffHistory.md
  packages/config/src/projects/shared-zk-stack/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/l2b-fetchzkstack_output.json
  packages/config/src/projects/shared-zk-stack/zksync2/diffHistory.md
  packages/config/src/test/discovery/config.test.ts
  packages/l2b/src/implementations/fetchZkStack.ts
Labels: research

#7937 add SOPH (sophon)
  packages/config/src/projects/globalTokens.jsonc
  packages/config/src/projects/sophon/sophon.ts
  packages/config/src/tokens/generated.json
  packages/config/src/tokens/tokens.jsonc
  packages/config/src/tvs/json/sophon.json
Labels: research

#7938 Zkstack upgrades
  packages/config/src/projects/abstract/ethereum/diffHistory.md
  packages/config/src/projects/abstract/ethereum/discovered.json
  packages/config/src/projects/abstract/zksync2/diffHistory.md
  packages/config/src/projects/abstract/zksync2/discovered.json
  packages/config/src/projects/cronoszkevm/cronoszkevm.ts
  packages/config/src/projects/cronoszkevm/ethereum/diffHistory.md
  packages/config/src/projects/cronoszkevm/ethereum/discovered.json
  packages/config/src/projects/cronoszkevm/zksync2/diffHistory.md
  packages/config/src/projects/cronoszkevm/zksync2/discovered.json
  packages/config/src/projects/gateway/ethereum/diffHistory.md
  packages/config/src/projects/gateway/ethereum/discovered.json
  packages/config/src/projects/grvt/ethereum/diffHistory.md
  packages/config/src/projects/grvt/ethereum/discovered.json
  packages/config/src/projects/lachain/ethereum/diffHistory.md
  packages/config/src/projects/lachain/ethereum/discovered.json
  packages/config/src/projects/lachain/zksync2/diffHistory.md
  packages/config/src/projects/lachain/zksync2/discovered.json
  packages/config/src/projects/lens/ethereum/diffHistory.md
  packages/config/src/projects/lens/ethereum/discovered.json
  packages/config/src/projects/shared-zk-stack/ethereum/l2b-fetchzkstack_output.json
  packages/config/src/projects/sophon/ethereum/diffHistory.md
  packages/config/src/projects/sophon/ethereum/discovered.json
  packages/config/src/projects/sophon/zksync2/diffHistory.md
  packages/config/src/projects/sophon/zksync2/discovered.json
  packages/config/src/projects/sxt/ethereum/diffHistory.md
  packages/config/src/projects/sxt/ethereum/discovered.json
  packages/config/src/projects/sxt/zksync2/diffHistory.md
  packages/config/src/projects/sxt/zksync2/discovered.json
  packages/config/src/projects/treasure/ethereum/diffHistory.md
  packages/config/src/projects/treasure/ethereum/discovered.json
  packages/config/src/projects/wonder/ethereum/diffHistory.md
  packages/config/src/projects/wonder/ethereum/discovered.json
  packages/config/src/projects/zeronetwork/ethereum/diffHistory.md
  packages/config/src/projects/zeronetwork/ethereum/discovered.json
  packages/config/src/projects/zeronetwork/zksync2/diffHistory.md
  packages/config/src/projects/zeronetwork/zksync2/discovered.json
  packages/config/src/projects/zkcandy/ethereum/diffHistory.md
  packages/config/src/projects/zkcandy/ethereum/discovered.json
  packages/config/src/projects/zkcandy/zkcandy.ts
  packages/config/src/projects/zkcandy/zksync2/diffHistory.md
  packages/config/src/projects/zkcandy/zksync2/discovered.json
  packages/config/src/projects/zksync2/ethereum/diffHistory.md
  packages/config/src/projects/zksync2/ethereum/discovered.json
Labels: research
